# These are supported funding model platforms
github: hafidznoor
custom: ["https://hafidznoor.lemonsqueezy.com/checkout/buy/f2b81ada-e8a9-4e29-b35c-7b7249b78404", "https://trakteer.id/hafidznoor/tip?quantity=10"]
