// Generated file — do not edit by hand.
// Source: data/logos.yml. Regenerate via `npm run build:flutter`.
//
// Logo SVGs are licensed CC-BY-NC-4.0 (see LICENSE-ASSETS at repo root).
// This Dart code is licensed MIT (see LICENSE at repo root).

import 'logo_meta.dart';
import 'category.dart';

const String catalogVersion = '2.1.4';

const List<LogoMeta> catalogLogos = <LogoMeta>[
  LogoMeta(slug: '2c2p', name: '2c2p', category: 'payment-gateway', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'acc', name: 'ACC', category: 'financing', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'acc-alt', name: 'ACC (Alt)', category: 'financing', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'adakami', name: 'AdaKami', category: 'financing', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'adakami-alt', name: 'AdaKami (Alt)', category: 'financing', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'adira-finance', name: 'Adira Finance', category: 'financing', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'aeon-credit-service', name: 'AEON Credit Service', category: 'financing', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'aetra-tangerang', name: 'Aetra Tangerang', category: 'utilities', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'afpi', name: 'AFPI', category: 'regulatory', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'akulaku', name: 'Akulaku', category: 'financing', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'akulaku-paylater', name: 'Akulaku Paylater', category: 'financing', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'aladin', name: 'Aladin', category: 'bank-logo', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'alfamart', name: 'Alfamart', category: 'supermarket', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'alfamidi', name: 'Alfamidi', category: 'supermarket', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'alipay-new', name: 'Alipay (New)', category: 'miscellaneous', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'alipay-old', name: 'Alipay (Old)', category: 'miscellaneous', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'allo', name: 'Allo', category: 'bank-logo', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'alto', name: 'ALTO', category: 'switching', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'amar-bank', name: 'Amar Bank', category: 'bank-logo', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'amercian-express-alt', name: 'Amercian Express (Alt)', category: 'card-payment', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'american-express', name: 'American Express', category: 'card-payment', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'american-express-alt-2', name: 'American Express (Alt-2)', category: 'card-payment', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'anteraja', name: 'Anteraja', category: 'logistic', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'anz', name: 'ANZ', category: 'bank-logo', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'app-store', name: 'App Store', category: 'game', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'apple-arcade', name: 'Apple Arcade', category: 'game', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'apple-card', name: 'Apple Card', category: 'card-payment', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'apple-music', name: 'Apple Music', category: 'entertainment', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'apple-pay', name: 'Apple Pay', category: 'miscellaneous', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'aspi', name: 'ASPI', category: 'regulatory', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'assa', name: 'ASSA', category: 'logistic', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'astra-pay', name: 'Astra Pay', category: 'e-wallet', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'atm-bersama', name: 'ATM Bersama', category: 'switching', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'axis', name: 'AXIS', category: 'mobile-telco', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'bangkok-bank', name: 'Bangkok Bank', category: 'bank-logo', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'bank-artha-graha-internasional', name: 'Bank Artha Graha Internasional', category: 'bank-logo', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'bank-bengkulu', name: 'Bank Bengkulu', category: 'bank-logo', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'bank-bjb', name: 'Bank BJB', category: 'bank-logo', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'bank-bjb-syariah', name: 'Bank BJB Syariah', category: 'bank-logo', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'bank-bpd-aceh', name: 'Bank BPD Aceh', category: 'bank-logo', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'bank-bpd-bali', name: 'Bank BPD Bali', category: 'bank-logo', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'bank-bpd-banten', name: 'Bank BPD Banten', category: 'bank-logo', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'bank-bpd-diy', name: 'Bank BPD DIY', category: 'bank-logo', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'bank-bpd-jambi', name: 'Bank BPD Jambi', category: 'bank-logo', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'bank-bpd-jateng', name: 'Bank BPD Jateng', category: 'bank-logo', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'bank-bpd-jatim', name: 'Bank BPD Jatim', category: 'bank-logo', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'bank-bpd-kalbar', name: 'Bank BPD Kalbar', category: 'bank-logo', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'bank-bpd-kalbar-alt', name: 'Bank BPD Kalbar (Alt)', category: 'bank-logo', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'bank-bpd-kalimantan-timur', name: 'Bank BPD Kalimantan Timur', category: 'bank-logo', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'bank-bpd-kalsel', name: 'Bank BPD Kalsel', category: 'bank-logo', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'bank-bpd-kalteng', name: 'Bank BPD Kalteng', category: 'bank-logo', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'bank-bpd-lampung', name: 'Bank BPD Lampung', category: 'bank-logo', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'bank-bpd-maluku-malut', name: 'Bank BPD Maluku Malut', category: 'bank-logo', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'bank-bpd-ntb-syariah', name: 'Bank BPD NTB Syariah', category: 'bank-logo', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'bank-bpd-ntb-syariah-alt', name: 'Bank BPD NTB Syariah (Alt)', category: 'bank-logo', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'bank-bpd-ntt', name: 'Bank BPD NTT', category: 'bank-logo', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'bank-bpd-papua', name: 'Bank BPD Papua', category: 'bank-logo', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'bank-bpd-riau-kepri', name: 'Bank BPD Riau Kepri', category: 'bank-logo', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'bank-bpd-riau-kepri-syariah', name: 'Bank BPD Riau Kepri Syariah', category: 'bank-logo', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'bank-bpd-sulselbar', name: 'Bank BPD Sulselbar', category: 'bank-logo', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'bank-bpd-sulteng', name: 'Bank BPD Sulteng', category: 'bank-logo', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'bank-bpd-sultra', name: 'Bank BPD Sultra', category: 'bank-logo', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'bank-bpd-sulutgo', name: 'Bank BPD Sulutgo', category: 'bank-logo', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'bank-bpd-sumsel-babel', name: 'Bank BPD Sumsel Babel', category: 'bank-logo', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'bank-bpd-sumsel-babel-alt-1', name: 'Bank BPD Sumsel Babel (Alt-1)', category: 'bank-logo', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'bank-bpd-sumsel-babel-alt-2', name: 'Bank BPD Sumsel Babel (Alt-2)', category: 'bank-logo', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'bank-bpd-sumut', name: 'Bank BPD Sumut', category: 'bank-logo', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'bank-bumi-artha', name: 'Bank Bumi Artha', category: 'bank-logo', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'bank-capital', name: 'Bank Capital', category: 'bank-logo', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'bank-capital-alt', name: 'Bank Capital (Alt)', category: 'bank-logo', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'bank-dki', name: 'Bank DKI', category: 'bank-logo', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'bank-ganesha', name: 'Bank Ganesha', category: 'bank-logo', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'bank-ina', name: 'Bank INA', category: 'bank-logo', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'bank-index-selindo', name: 'Bank Index Selindo', category: 'bank-logo', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'bank-index-selindo-alt', name: 'Bank Index Selindo (Alt)', category: 'bank-logo', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'bank-indonesia', name: 'Bank Indonesia', category: 'regulatory', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'bank-jasa-jakarta', name: 'Bank Jasa Jakarta', category: 'bank-logo', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'bank-lampung', name: 'Bank Lampung', category: 'bank-logo', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'bank-mas', name: 'Bank Mas', category: 'bank-logo', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'bank-maspion', name: 'Bank Maspion', category: 'bank-logo', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'bank-maspion-alt', name: 'Bank Maspion (Alt)', category: 'bank-logo', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'bank-mayapada', name: 'Bank Mayapada', category: 'bank-logo', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'bank-mayapada-alt', name: 'Bank Mayapada (Alt)', category: 'bank-logo', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'bank-mayora', name: 'Bank Mayora', category: 'bank-logo', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'bank-mestika-dharma', name: 'Bank Mestika Dharma', category: 'bank-logo', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'bank-nagari', name: 'Bank Nagari', category: 'bank-logo', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'bank-of-america', name: 'Bank of America', category: 'bank-logo', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'bank-of-china', name: 'Bank of China', category: 'bank-logo', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'bank-of-india', name: 'Bank of India', category: 'bank-logo', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'bank-of-india-indonesia', name: 'Bank of India Indonesia', category: 'bank-logo', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'bank-raya', name: 'Bank Raya', category: 'bank-logo', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'bank-resona-perdania', name: 'Bank Resona Perdania', category: 'bank-logo', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'bank-resona-perdania-alt', name: 'Bank Resona Perdania (Alt)', category: 'bank-logo', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'bank-sahabat-sampoerna', name: 'Bank Sahabat Sampoerna', category: 'bank-logo', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'bank-smbc-indonesia', name: 'Bank SMBC Indonesia', category: 'bank-logo', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'bank-victoria', name: 'Bank Victoria', category: 'bank-logo', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'bank-victoria-syariah', name: 'Bank Victoria Syariah', category: 'bank-logo', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'bank-woori-saudara', name: 'Bank Woori Saudara', category: 'bank-logo', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'bappebti', name: 'BAPPEBTI', category: 'regulatory', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'baznas', name: 'BAZNAS', category: 'donation', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'bca', name: 'BCA', category: 'bank-logo', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'bca-atm', name: 'BCA ATM', category: 'switching', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'bca-debit', name: 'BCA Debit', category: 'switching', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'bca-digital', name: 'BCA Digital', category: 'bank-logo', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'bca-finance', name: 'BCA Finance', category: 'financing', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'bca-flazz', name: 'BCA Flazz', category: 'prepaid-card', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'bca-flazz-alt', name: 'BCA Flazz (Alt)', category: 'prepaid-card', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'bca-klikpay', name: 'BCA KlikPay', category: 'direct-debit', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'bca-mobile', name: 'BCA Mobile', category: 'bank-app', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'bca-syariah', name: 'BCA Syariah', category: 'bank-logo', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'bea-cukai', name: 'Bea Cukai', category: 'government', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'bhinneka', name: 'Bhinneka', category: 'e-commerce', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'bi-fast', name: 'BI-FAST', category: 'switching', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'biznet', name: 'Biznet', category: 'isp', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'biznet-home', name: 'Biznet Home', category: 'isp', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'blibli', name: 'Blibli', category: 'e-commerce', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'blu-bca', name: 'Blu BCA', category: 'bank-logo', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'bluepay', name: 'Bluepay', category: 'e-wallet', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'bnc', name: 'BNC', category: 'bank-logo', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'bni', name: 'BNI', category: 'bank-logo', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'bni-mobile-banking', name: 'BNI Mobile Banking', category: 'bank-app', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'bni-tapcash', name: 'BNI TapCash', category: 'prepaid-card', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'bnp-paribas', name: 'BNP Paribas', category: 'bank-logo', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'bpd', name: 'BPD', category: 'regulatory', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'bri', name: 'BRI', category: 'bank-logo', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'bri-alt', name: 'BRI (Alt)', category: 'bank-logo', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'bri-brizzi', name: 'BRI BRIZZI', category: 'prepaid-card', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'bri-brizzi-alt', name: 'BRI BRIZZI (Alt)', category: 'prepaid-card', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'bri-direct-debit', name: 'BRI Direct Debit', category: 'direct-debit', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'bri-finance', name: 'BRI Finance', category: 'financing', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'bri-vertical', name: 'BRI (Vertical)', category: 'bank-logo', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'bright', name: 'Bright', category: 'supermarket', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'brimo', name: 'BRImo', category: 'bank-app', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'bsi', name: 'BSI', category: 'bank-logo', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'bsi-mobile', name: 'BSI Mobile', category: 'bank-app', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'btn', name: 'BTN', category: 'bank-logo', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'btn-alt', name: 'BTN (Alt)', category: 'bank-logo', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'btn-new', name: 'BTN (New)', category: 'bank-logo', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'btn-syariah', name: 'BTN Syariah', category: 'bank-logo', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'btn-syariah-new', name: 'BTN Syariah (New)', category: 'bank-logo', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'btpn', name: 'BTPN', category: 'bank-logo', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'btpn-syariah', name: 'BTPN Syariah', category: 'bank-logo', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'bukalapak', name: 'Bukalapak', category: 'e-commerce', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'bukalapak-new', name: 'Bukalapak (New)', category: 'e-commerce', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'bussan-auto-finance', name: 'Bussan Auto Finance', category: 'financing', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'by-u', name: 'by.U', category: 'mobile-telco', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'catchplay', name: 'Catchplay', category: 'entertainment', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'cbn', name: 'CBN', category: 'isp', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'ccb-indonesia', name: 'CCB Indonesia', category: 'bank-logo', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'ccb-indonesia-alt', name: 'CCB Indonesia (Alt)', category: 'bank-logo', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'cgv', name: 'CGV', category: 'entertainment', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'cimb-niaga', name: 'CIMB Niaga', category: 'bank-logo', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'cimb-niaga-syariah', name: 'CIMB Niaga Syariah', category: 'bank-logo', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'cinepolis', name: 'Cinepolis', category: 'entertainment', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'circle-k', name: 'Circle K', category: 'supermarket', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'circle-k-alt', name: 'Circle K (Alt)', category: 'supermarket', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'cirrus', name: 'Cirrus', category: 'card-payment', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'citibank', name: 'Citibank', category: 'bank-logo', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'citibank-alt', name: 'Citibank (Alt)', category: 'bank-logo', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'cititrans', name: 'Cititrans', category: 'transportation', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'commonwealth', name: 'Commonwealth', category: 'bank-logo', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'contactless', name: 'Contactless', category: 'card-payment', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'contactless-alt', name: 'Contactless (Alt)', category: 'card-payment', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'credit-suisse', name: 'Credit Suisse', category: 'bank-logo', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'ctbc-bank', name: 'CTBC Bank', category: 'bank-logo', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'daihatsu-financial-service', name: 'Daihatsu Financial Service', category: 'financing', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'dakota-cargo', name: 'Dakota Cargo', category: 'logistic', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'dakota-logistik', name: 'Dakota Logistik', category: 'logistic', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'damri', name: 'DAMRI', category: 'transportation', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'dan-plus-dan', name: 'Dan+Dan', category: 'supermarket', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'dana', name: 'DANA', category: 'e-wallet', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'danamon', name: 'Danamon', category: 'bank-logo', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'danamon-mufg', name: 'Danamon (MUFG)', category: 'bank-logo', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'danamon-syariah', name: 'Danamon Syariah', category: 'bank-logo', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'daytrans', name: 'DayTrans', category: 'transportation', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'dbs', name: 'DBS', category: 'bank-logo', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'deutsche-bank', name: 'Deutsche Bank', category: 'bank-logo', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'dhl-express', name: 'DHL Express', category: 'logistic', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'digibank', name: 'Digibank', category: 'bank-app', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'digibank-alt', name: 'Digibank (Alt)', category: 'bank-app', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'dipay', name: 'Dipay', category: 'e-wallet', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'discover', name: 'Discover', category: 'card-payment', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'discover-alt', name: 'Discover (Alt)', category: 'card-payment', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'disney-plus', name: 'Disney+', category: 'entertainment', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'disney-plus-hotstar', name: 'Disney+ Hotstar', category: 'entertainment', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'djp-online', name: 'DJP Online', category: 'government', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'djp-online-alt', name: 'DJP Online (Alt)', category: 'government', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'doku', name: 'DOKU', category: 'e-wallet', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'dompet-dhuafa', name: 'Dompet Dhuafa', category: 'donation', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'dompet-dhuafa-alt', name: 'Dompet Dhuafa (Alt)', category: 'donation', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'dutamoney', name: 'Dutamoney', category: 'e-wallet', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'e-toll-card', name: 'e-Toll Card', category: 'prepaid-card', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'ea-play', name: 'EA Play', category: 'game', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'ea-play-alt', name: 'EA Play (Alt)', category: 'game', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'ekonomi-syariah', name: 'Ekonomi Syariah', category: 'regulatory', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'ekonomi-syariah-alt', name: 'Ekonomi Syariah (Alt)', category: 'regulatory', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'ems', name: 'EMS', category: 'logistic', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'epic-games', name: 'Epic Games', category: 'game', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'epic-games-store', name: 'Epic Games Store', category: 'game', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'esl-express', name: 'ESL Express', category: 'logistic', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'espay', name: 'Espay', category: 'payment-gateway', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'family-mart', name: 'Family Mart', category: 'supermarket', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'fedex-express', name: 'FedEx Express', category: 'logistic', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'fif-astra', name: 'FIF Astra', category: 'financing', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'finmas', name: 'Finmas', category: 'financing', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'finpay', name: 'Finpay', category: 'payment-gateway', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'first-logistic', name: 'First Logistic', category: 'logistic', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'first-media', name: 'First Media', category: 'isp', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'flip', name: 'Flip', category: 'remittance', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'giant', name: 'Giant', category: 'supermarket', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'google-pay', name: 'Google Pay', category: 'miscellaneous', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'google-play', name: 'Google Play', category: 'game', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'google-play-alt', name: 'Google Play (Alt)', category: 'game', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'gopay', name: 'Gopay', category: 'e-wallet', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'gopay-alt', name: 'Gopay (Alt)', category: 'e-wallet', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'gopaylater', name: 'Gopaylater', category: 'financing', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'gpn', name: 'GPN', category: 'card-payment', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'grab-pay', name: 'Grab Pay', category: 'miscellaneous', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'hbo-go', name: 'HBO GO', category: 'entertainment', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'hero', name: 'Hero', category: 'supermarket', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'hibank', name: 'hibank', category: 'bank-logo', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'home-credit', name: 'Home Credit', category: 'financing', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'hoox', name: 'HOOX', category: 'entertainment', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'hsbc', name: 'HSBC', category: 'bank-logo', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'hypermart', name: 'Hypermart', category: 'supermarket', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'i-saku', name: 'I.Saku', category: 'e-wallet', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'ibk-bank', name: 'IBK Bank', category: 'bank-logo', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'icbc', name: 'ICBC', category: 'bank-logo', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'icbc-alt', name: 'ICBC (Alt)', category: 'bank-logo', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'id-express', name: 'ID Express', category: 'logistic', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'im3', name: 'IM3', category: 'mobile-telco', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'indihome-new', name: 'IndiHome (New)', category: 'isp', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'indihome-old', name: 'IndiHome (Old)', category: 'isp', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'indodana', name: 'Indodana', category: 'financing', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'indomaret', name: 'Indomaret', category: 'supermarket', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'indosat-hifi', name: 'Indosat Hifi', category: 'isp', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'indosat-m2', name: 'Indosat M2', category: 'isp', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'ing-bank', name: 'ING Bank', category: 'bank-logo', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'inklusi-keuangan', name: 'Inklusi Keuangan', category: 'regulatory', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'interlink', name: 'Interlink', category: 'miscellaneous', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'ipay88', name: 'ipay88', category: 'payment-gateway', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'j-and-t-cargo', name: 'J&T Cargo', category: 'logistic', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'j-and-t-express', name: 'J&T Express', category: 'logistic', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'j-trust-bank', name: 'J Trust Bank', category: 'bank-logo', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'jago', name: 'Jago', category: 'bank-logo', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'jago-app', name: 'Jago', category: 'bank-app', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'jakcard', name: 'Jakcard', category: 'prepaid-card', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'jaklingko', name: 'JakLingko', category: 'transportation', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'jakone-mobile', name: 'JakOne Mobile', category: 'bank-app', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'jakone-pay', name: 'JakOne Pay', category: 'e-wallet', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'jalin', name: 'Jalin', category: 'switching', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'jcb', name: 'JCB', category: 'card-payment', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'jenius', name: 'Jenius', category: 'bank-logo', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'jenius-app', name: 'Jenius', category: 'bank-app', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'jenius-pay', name: 'Jenius Pay', category: 'direct-debit', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'jne', name: 'JNE', category: 'logistic', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'jne-alt', name: 'JNE (Alt)', category: 'logistic', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'joox', name: 'JOOX', category: 'entertainment', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'jp-morgan-chase', name: 'JP Morgan Chase', category: 'bank-logo', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'kai', name: 'KAI', category: 'transportation', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'kai-bandara', name: 'KAI Bandara', category: 'transportation', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'kai-commuter-new', name: 'KAI Commuter (New)', category: 'transportation', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'kai-commuter-old', name: 'KAI Commuter (Old)', category: 'transportation', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'kai-logistik', name: 'KAI Logistik', category: 'logistic', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'kartu-as', name: 'Kartu As', category: 'mobile-telco', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'kartu-halo', name: 'Kartu Halo', category: 'mobile-telco', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'kaspro', name: 'Kaspro', category: 'e-wallet', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'kb-bukopin', name: 'KB Bukopin', category: 'bank-logo', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'kb-bukopin-alt', name: 'KB Bukopin (Alt)', category: 'bank-logo', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'kb-bukopin-syariah', name: 'KB Bukopin Syariah', category: 'bank-logo', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'keb-hana-bank', name: 'KEB Hana Bank', category: 'bank-logo', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'keb-hana-bank-alt', name: 'KEB Hana Bank (Alt)', category: 'bank-logo', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'kemenkeu', name: 'Kemenkeu', category: 'government', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'kitabisa', name: 'Kitabisa', category: 'donation', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'kitabisa-alt', name: 'Kitabisa (Alt)', category: 'donation', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'kominfo', name: 'KOMINFO', category: 'regulatory', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'kredit-pintar', name: 'Kredit Pintar', category: 'financing', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'kreditplus', name: 'KreditPlus', category: 'financing', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'kredivo', name: 'Kredivo', category: 'financing', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'krom', name: 'Krom', category: 'bank-logo', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'lalamove', name: 'Lalamove', category: 'logistic', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'langitmusik', name: 'Langitmusik', category: 'entertainment', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'lawson', name: 'Lawson', category: 'supermarket', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'lazada', name: 'Lazada', category: 'e-commerce', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'lazada-express', name: 'Lazada Express', category: 'logistic', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'lexus-financial-service', name: 'Lexus Financial Service', category: 'financing', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'lexus-financial-service-1', name: 'Lexus Financial Service-1', category: 'financing', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'line-bank', name: 'LINE Bank', category: 'bank-logo', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'line-bank-alt', name: 'LINE Bank (Alt)', category: 'bank-logo', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'line-pay', name: 'LINE Pay', category: 'miscellaneous', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'line-pay-alt', name: 'LINE Pay (Alt)', category: 'miscellaneous', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'link', name: 'Link', category: 'switching', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'link-new', name: 'Link (New)', category: 'switching', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'link-new-alt', name: 'Link (New Alt)', category: 'switching', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'link-old', name: 'Link (Old)', category: 'switching', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'linkaja', name: 'LinkAja', category: 'e-wallet', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'lion-parcel', name: 'Lion Parcel', category: 'logistic', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'live-on', name: 'Live.On', category: 'mobile-telco', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'lotte', name: 'Lotte', category: 'supermarket', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'lotte-grosir', name: 'Lotte Grosir', category: 'supermarket', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'lotte-mart', name: 'Lotte Mart', category: 'supermarket', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'lps', name: 'LPS', category: 'regulatory', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'lrt-jakarta', name: 'LRT Jakarta', category: 'transportation', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'maestro', name: 'Maestro', category: 'card-payment', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'mandiri', name: 'Mandiri', category: 'bank-logo', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'mandiri-e-cash', name: 'Mandiri E-Cash', category: 'direct-debit', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'mandiri-e-money', name: 'Mandiri e-money', category: 'prepaid-card', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'mandiri-livin', name: 'Mandiri Livin', category: 'bank-app', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'mandiri-taspen', name: 'Mandiri Taspen', category: 'bank-logo', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'mastercard', name: 'Mastercard', category: 'card-payment', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'mastercard-black', name: 'Mastercard Black', category: 'card-payment', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'mastercard-contactless', name: 'Mastercard Contactless', category: 'card-payment', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'mastercard-contactless-alt', name: 'Mastercard Contactless (Alt)', category: 'card-payment', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'mastercard-debit', name: 'Mastercard Debit', category: 'card-payment', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'mastercard-debit-alt', name: 'Mastercard Debit (Alt)', category: 'card-payment', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'mastercard-securecode', name: 'Mastercard SecureCode', category: 'card-payment', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'mastercard-securecode-new', name: 'Mastercard SecureCode (New)', category: 'card-payment', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'masterpass', name: 'Masterpass', category: 'card-payment', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'masterpass-alt', name: 'Masterpass (Alt)', category: 'card-payment', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'maxstream', name: 'Maxstream', category: 'entertainment', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'maybank', name: 'Maybank', category: 'bank-logo', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'mega', name: 'Mega', category: 'bank-logo', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'mega-syariah', name: 'Mega Syariah', category: 'bank-logo', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'melsa', name: 'Melsa', category: 'isp', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'mentari-ooredoo', name: 'Mentari Ooredoo', category: 'mobile-telco', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'meps', name: 'MEPS', category: 'switching', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'midtrans', name: 'Midtrans', category: 'payment-gateway', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'mizuho-bank', name: 'Mizuho Bank', category: 'bank-logo', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'mnc', name: 'MNC', category: 'bank-logo', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'mnc-bank', name: 'MNC Bank', category: 'bank-logo', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'mnc-vision', name: 'MNC Vision', category: 'entertainment', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'moneygram', name: 'MoneyGram', category: 'remittance', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'motion-banking', name: 'Motion Banking', category: 'bank-logo', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'motion-banking-alt', name: 'Motion Banking (Alt)', category: 'bank-logo', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'motion-pay', name: 'Motion Pay', category: 'e-wallet', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'mrt-jakarta', name: 'MRT Jakarta', category: 'transportation', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'mtix', name: 'MTIX', category: 'entertainment', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'mualamat', name: 'Mualamat', category: 'bank-logo', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'mufg', name: 'MUFG', category: 'bank-logo', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'mufg-alt', name: 'MUFG (Alt)', category: 'bank-logo', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'my-nintendo', name: 'My Nintendo', category: 'game', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'myrepublic', name: 'MyRepublic', category: 'isp', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'nanobank-syariah', name: 'Nanobank Syariah', category: 'bank-logo', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'nanobank-syariah-alt', name: 'Nanobank Syariah (Alt)', category: 'bank-logo', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'ncs', name: 'NCS', category: 'logistic', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'neobank', name: 'Neobank', category: 'bank-app', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'netflix', name: 'Netflix', category: 'entertainment', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'netflix-alt', name: 'Netflix (Alt)', category: 'entertainment', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'nets', name: 'NETS', category: 'miscellaneous', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'netzme', name: 'Netzme', category: 'e-wallet', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'nex-parabola', name: 'Nex Parabola', category: 'entertainment', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'nickelodeon', name: 'Nickelodeon', category: 'entertainment', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'ninja-xpress', name: 'Ninja Xpress', category: 'logistic', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'nintendo-online', name: 'Nintendo Online', category: 'game', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'nobu', name: 'NOBU', category: 'bank-logo', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'ocbc-nisp', name: 'OCBC NISP', category: 'bank-logo', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'octo-clicks', name: 'OCTO Clicks', category: 'bank-app', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'octo-clicks-direct-debit', name: 'OCTO Clicks', category: 'direct-debit', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'ojk', name: 'OJK', category: 'regulatory', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'ok-bank', name: 'OK Bank', category: 'bank-logo', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'oneklik', name: 'OneKlik', category: 'direct-debit', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'otto-pay', name: 'OTTO Pay', category: 'e-wallet', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'ovo-new', name: 'OVO (New)', category: 'e-wallet', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'ovo-new-alt', name: 'OVO (New Alt)', category: 'e-wallet', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'ovo-old', name: 'OVO (Old)', category: 'e-wallet', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'ovo-old-alt', name: 'OVO (Old Alt)', category: 'e-wallet', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'pam-jaya-new', name: 'PAM Jaya (New)', category: 'utilities', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'pam-jaya-old', name: 'PAM Jaya (Old)', category: 'utilities', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'pandu-logistics', name: 'Pandu Logistics', category: 'logistic', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'panin-dubai-syariah', name: 'Panin Dubai Syariah', category: 'bank-logo', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'paninbank', name: 'PaninBank', category: 'bank-logo', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'paydia', name: 'Paydia', category: 'e-wallet', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'payoneer', name: 'Payoneer', category: 'remittance', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'paypal', name: 'PayPal', category: 'remittance', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'paytren', name: 'Paytren', category: 'e-wallet', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'pcp-express', name: 'PCP Express', category: 'logistic', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'pdam', name: 'PDAM', category: 'utilities', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'pdam-kota-surabaya', name: 'PDAM Kota Surabaya', category: 'utilities', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'pegadaian', name: 'Pegadaian', category: 'financing', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'perbankan-syariah-ib', name: 'Perbankan Syariah (IB)', category: 'regulatory', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'permata', name: 'Permata', category: 'bank-logo', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'permata-bank-alt', name: 'Permata Bank (Alt)', category: 'bank-logo', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'permata-bank-new', name: 'Permata Bank (New)', category: 'bank-logo', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'pgn', name: 'PGN', category: 'utilities', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'playstation-plus', name: 'Playstation Plus', category: 'game', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'playstation-store', name: 'Playstation Store', category: 'game', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'pln', name: 'PLN', category: 'utilities', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'pos-indonesia-new', name: 'Pos Indonesia (New)', category: 'logistic', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'pos-indonesia-old', name: 'Pos Indonesia (Old)', category: 'logistic', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'pospay', name: 'Pospay', category: 'e-wallet', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'prima', name: 'PRIMA', category: 'switching', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'prima-bank', name: 'PRIMA Bank', category: 'bank-logo', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'prima-debit', name: 'PRIMA Debit', category: 'switching', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'prime-video', name: 'Prime Video', category: 'entertainment', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'prismalink', name: 'PrismaLink', category: 'payment-gateway', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'qnb', name: 'QNB', category: 'bank-logo', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'qris', name: 'QRIS', category: 'government', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'rex', name: 'REX', category: 'logistic', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'ria-money', name: 'Ria Money', category: 'remittance', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'rpx', name: 'RPX', category: 'logistic', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'rumah-zakat', name: 'Rumah Zakat', category: 'donation', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'rumah-zakat-alt', name: 'Rumah Zakat (Alt)', category: 'donation', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'samsung-card', name: 'Samsung Card', category: 'card-payment', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'samsung-pay', name: 'Samsung Pay', category: 'miscellaneous', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'samsung-pay-alt', name: 'Samsung Pay (Alt)', category: 'miscellaneous', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'sap-express', name: 'SAP Express', category: 'logistic', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'sbi-indonesia', name: 'SBI Indonesia', category: 'bank-logo', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'seabank', name: 'SeaBank', category: 'bank-logo', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'shinhan-bank', name: 'Shinhan Bank', category: 'bank-logo', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'shinhan-bank-alt', name: 'Shinhan Bank (Alt)', category: 'bank-logo', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'shopee', name: 'Shopee', category: 'e-commerce', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'shopee-alt', name: 'Shopee (Alt)', category: 'e-commerce', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'shopee-pay', name: 'Shopee Pay', category: 'e-wallet', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'sicepat-ekspres', name: 'Sicepat Ekspres', category: 'logistic', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'simpati', name: 'Simpati', category: 'mobile-telco', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'sinarmas', name: 'Sinarmas', category: 'bank-logo', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'sinarmas-syariah', name: 'Sinarmas Syariah', category: 'bank-logo', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'skrill', name: 'Skrill', category: 'remittance', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'smartfren', name: 'Smartfren', category: 'mobile-telco', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'smartfren-old', name: 'Smartfren (Old)', category: 'mobile-telco', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'speedcash', name: 'SpeedCash', category: 'e-wallet', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'spotify', name: 'Spotify', category: 'entertainment', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'spotify-alt', name: 'Spotify (Alt)', category: 'entertainment', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'spx-express', name: 'SPX Express', category: 'logistic', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'standard-chartered', name: 'Standard Chartered', category: 'bank-logo', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'steam', name: 'Steam', category: 'game', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'stripe', name: 'Stripe', category: 'payment-gateway', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'superbank', name: 'Superbank', category: 'bank-logo', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'superbank-alt', name: 'Superbank (Alt)', category: 'bank-logo', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'taf-toyota-astra-financial', name: 'TAF - Toyota Astra Financial', category: 'financing', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'telkomsel', name: 'Telkomsel', category: 'mobile-telco', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'telkomsel-alt', name: 'Telkomsel (Alt)', category: 'mobile-telco', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'telkomsel-halo', name: 'Telkomsel Halo', category: 'mobile-telco', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'telkomsel-orbit', name: 'Telkomsel Orbit', category: 'isp', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'telkomsel-prabayar', name: 'Telkomsel Prabayar', category: 'mobile-telco', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'tiki', name: 'TIKI', category: 'logistic', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'tokopedia', name: 'Tokopedia', category: 'e-commerce', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'toserba-yogya', name: 'Toserba Yogya', category: 'supermarket', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'toyota-financial-service', name: 'Toyota Financial Service', category: 'financing', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'transfez', name: 'Transfez', category: 'remittance', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'transjakarta', name: 'TransJakarta', category: 'transportation', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'transmart', name: 'Transmart', category: 'supermarket', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'transvision-new', name: 'TransVision (New)', category: 'entertainment', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'transvision-old', name: 'TransVision (Old)', category: 'entertainment', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'tri', name: 'Tri', category: 'mobile-telco', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'truemoney', name: 'TrueMoney', category: 'e-wallet', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'uangku', name: 'Uangku', category: 'e-wallet', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'ubisoft-plus', name: 'UBISOFT+', category: 'game', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'union-pay', name: 'Union Pay', category: 'card-payment', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'union-pay-contactless', name: 'Union Pay Contactless', category: 'card-payment', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'union-pay-contactless-en', name: 'Union Pay Contactless (EN)', category: 'card-payment', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'union-pay-en', name: 'Union Pay (EN)', category: 'card-payment', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'uob', name: 'UOB', category: 'bank-logo', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'uob-ez-pay', name: 'UOB EZ Pay', category: 'direct-debit', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'uob-tmrw', name: 'UOB TMRW', category: 'bank-app', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'verified-by-visa', name: 'Verified by VISA', category: 'card-payment', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'verified-by-visa-new', name: 'Verified by VISA (New)', category: 'card-payment', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'vidio', name: 'Vidio', category: 'entertainment', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'visa', name: 'VISA', category: 'card-payment', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'visa-checkout', name: 'VISA Checkout', category: 'card-payment', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'visa-debit', name: 'VISA Debit', category: 'card-payment', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'visa-pay', name: 'VISA Pay', category: 'card-payment', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'visa-paywave', name: 'VISA PayWave', category: 'card-payment', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'visa-plus', name: 'VISA Plus', category: 'card-payment', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'visa-secure-3ds', name: 'VISA Secure (3DS)', category: 'card-payment', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'visa-signature', name: 'VISA Signature', category: 'card-payment', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'vision-plus', name: 'Vision+', category: 'entertainment', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'viu', name: 'VIU', category: 'entertainment', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'wahana-express', name: 'Wahana Express', category: 'logistic', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'wahana-express-alt', name: 'Wahana Express (Alt)', category: 'logistic', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'welab-bank', name: 'Welab Bank', category: 'bank-logo', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'western-union', name: 'Western Union', category: 'remittance', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'whoosh', name: 'Whoosh', category: 'transportation', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'wirecard', name: 'Wirecard', category: 'miscellaneous', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'wirecard-1', name: 'Wirecard-1', category: 'miscellaneous', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'wirecard-2', name: 'Wirecard-2', category: 'miscellaneous', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'wise', name: 'Wise', category: 'remittance', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'wom-finance', name: 'WOM Finance', category: 'financing', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'wondr-by-bni', name: 'Wondr by BNI', category: 'bank-app', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'world-bank', name: 'World Bank', category: 'regulatory', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'world-bank-alt', name: 'World Bank (Alt)', category: 'regulatory', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'xbox-game-pass', name: 'XBOX Game Pass', category: 'game', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'xendit', name: 'Xendit', category: 'payment-gateway', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'xl', name: 'XL', category: 'mobile-telco', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'xl-prioritas', name: 'XL Prioritas', category: 'mobile-telco', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'xxi-21', name: 'XXI (21)', category: 'entertainment', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'yomart', name: 'Yomart', category: 'supermarket', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'yukk', name: 'Yukk', category: 'e-wallet', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'zalora', name: 'Zalora', category: 'e-commerce', aliases: const <String>[], tags: const <String>[]),
];

const List<Category> catalogCategories = <Category>[
  Category(slug: 'bank-app', displayName: 'Bank App', count: 14),
  Category(slug: 'bank-logo', displayName: 'Bank Logo', count: 153),
  Category(slug: 'card-payment', displayName: 'Card Payment', count: 37),
  Category(slug: 'direct-debit', displayName: 'Direct Debit', count: 7),
  Category(slug: 'donation', displayName: 'Donation', count: 7),
  Category(slug: 'e-commerce', displayName: 'E-Commerce', count: 9),
  Category(slug: 'e-wallet', displayName: 'E-Wallet', count: 27),
  Category(slug: 'entertainment', displayName: 'Entertainment', count: 26),
  Category(slug: 'financing', displayName: 'Financing', count: 26),
  Category(slug: 'game', displayName: 'Game', count: 15),
  Category(slug: 'government', displayName: 'Government', count: 5),
  Category(slug: 'isp', displayName: 'ISP', count: 11),
  Category(slug: 'logistic', displayName: 'Logistic', count: 32),
  Category(slug: 'miscellaneous', displayName: 'Miscellaneous', count: 14),
  Category(slug: 'mobile-telco', displayName: 'Mobile Telco', count: 17),
  Category(slug: 'payment-gateway', displayName: 'Payment Gateway', count: 8),
  Category(slug: 'prepaid-card', displayName: 'Prepaid Card', count: 8),
  Category(slug: 'regulatory', displayName: 'Regulatory', count: 14),
  Category(slug: 'remittance', displayName: 'Remittance', count: 9),
  Category(slug: 'supermarket', displayName: 'Supermarket', count: 18),
  Category(slug: 'switching', displayName: 'Switching', count: 13),
  Category(slug: 'transportation', displayName: 'Transportation', count: 12),
  Category(slug: 'utilities', displayName: 'Utilities', count: 7),
];
