// Generated file — do not edit by hand.
// Source: data/logos.yml. Regenerate via `npm run build:flutter`.
//
// Logo SVGs are licensed CC-BY-NC-4.0 (see LICENSE-ASSETS at repo root).
// This Dart code is licensed MIT (see LICENSE at repo root).

import 'logo_meta.dart';
import 'category.dart';

const String catalogVersion = '2.5.1';

const List<LogoMeta> catalogLogos = <LogoMeta>[
  LogoMeta(slug: '2c2p', name: '2c2p', category: 'payment-gateway', aliases: const <String>['2c2p-new'], tags: const <String>[]),
  LogoMeta(slug: '2c2p-alt', name: '2c2p (Alt)', category: 'payment-gateway', aliases: const <String>['2c2p-new-alt'], tags: const <String>[]),
  LogoMeta(slug: '2c2p-old', name: '2c2p (Old)', category: 'payment-gateway', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'acc', name: 'ACC', category: 'financing', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'acc-alt', name: 'ACC (Alt)', category: 'financing', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'adakami', name: 'AdaKami', category: 'financing', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'adakami-alt', name: 'AdaKami (Alt)', category: 'financing', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'adira-finance', name: 'Adira Finance', category: 'financing', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'aeon', name: 'AEON', category: 'supermarket', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'aeon-credit-service', name: 'AEON Credit Service', category: 'financing', aliases: const <String>['aeon-credit'], tags: const <String>[]),
  LogoMeta(slug: 'aetra-tangerang', name: 'Aetra Tangerang', category: 'utilities', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'afpi', name: 'AFPI', category: 'regulatory', aliases: const <String>['asosiasi-fintech-pendanaan-bersama-indonesia'], tags: const <String>[]),
  LogoMeta(slug: 'aia', name: 'AIA', category: 'insurance', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'akulaku', name: 'Akulaku', category: 'financing', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'akulaku-paylater', name: 'Akulaku Paylater', category: 'financing', aliases: const <String>['akulaku-pay-later'], tags: const <String>[]),
  LogoMeta(slug: 'aladin', name: 'Aladin', category: 'bank-logo', aliases: const <String>['947', 'netbidja', 'bank-aladin-syariah'], tags: const <String>[]),
  LogoMeta(slug: 'alfa-express', name: 'Alfa Express', category: 'supermarket', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'alfamart', name: 'Alfamart', category: 'supermarket', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'alfamidi', name: 'Alfamidi', category: 'supermarket', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'alfamidi-super', name: 'Alfamidi Super', category: 'supermarket', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'alipay', name: 'Alipay', category: 'miscellaneous', aliases: const <String>['alipay-new', 'ali-pay'], tags: const <String>[]),
  LogoMeta(slug: 'alipay-old', name: 'Alipay (Old)', category: 'miscellaneous', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'alipay-plus', name: 'Alipay+', category: 'miscellaneous', aliases: const <String>['alipayplus'], tags: const <String>[]),
  LogoMeta(slug: 'alipay-plus-old', name: 'Alipay+ (Old)', category: 'miscellaneous', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'alipay-plus-old-alt', name: 'Alipay+ (Old Alt)', category: 'miscellaneous', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'allianz', name: 'Allianz', category: 'insurance', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'allianz-alt', name: 'Allianz (Alt)', category: 'insurance', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'allo', name: 'Allo', category: 'bank-logo', aliases: const <String>['567', 'alobidja', 'allo-bank-indonesia'], tags: const <String>[]),
  LogoMeta(slug: 'alto', name: 'ALTO', category: 'switching', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'amar-bank', name: 'Amar Bank', category: 'bank-logo', aliases: const <String>['531', 'lomaidj1', 'bank-amar', 'bank-amar-indonesia'], tags: const <String>[]),
  LogoMeta(slug: 'american-express', name: 'American Express', category: 'card-payment', aliases: const <String>['amex'], tags: const <String>[]),
  LogoMeta(slug: 'american-express-alt', name: 'American Express (Alt)', category: 'card-payment', aliases: const <String>['amercian-express-alt'], tags: const <String>[]),
  LogoMeta(slug: 'american-express-alt-2', name: 'American Express (Alt-2)', category: 'card-payment', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'anteraja', name: 'AnterAja', category: 'logistic', aliases: const <String>['anter-aja'], tags: const <String>[]),
  LogoMeta(slug: 'anz', name: 'ANZ', category: 'bank-logo', aliases: const <String>['061', 'anzbidjx', 'anz-indonesia', 'bank-anz-indonesia'], tags: const <String>[]),
  LogoMeta(slug: 'app-store', name: 'App Store', category: 'game', aliases: const <String>['apple-app-store'], tags: const <String>[]),
  LogoMeta(slug: 'apple-arcade', name: 'Apple Arcade', category: 'game', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'apple-card', name: 'Apple Card', category: 'card-payment', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'apple-music', name: 'Apple Music', category: 'entertainment', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'apple-pay', name: 'Apple Pay', category: 'miscellaneous', aliases: const <String>['applepay'], tags: const <String>[]),
  LogoMeta(slug: 'aspi', name: 'ASPI', category: 'regulatory', aliases: const <String>['asosiasi-sistem-pembayaran-indonesia'], tags: const <String>[]),
  LogoMeta(slug: 'assa', name: 'ASSA', category: 'logistic', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'astra-life', name: 'Astra Life', category: 'insurance', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'astra-life-alt', name: 'Astra Life (Alt)', category: 'insurance', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'astra-pay', name: 'Astra Pay', category: 'e-wallet', aliases: const <String>['astrapay'], tags: const <String>[]),
  LogoMeta(slug: 'asuransi-sinarmas-insurtech', name: 'Asuransi Sinarmas Insurtech', category: 'insurance', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'atm-bersama', name: 'ATM Bersama', category: 'switching', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'atm-link', name: 'ATM Link', category: 'switching', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'axa', name: 'AXA', category: 'insurance', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'axis', name: 'AXIS', category: 'mobile-telco', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'ayo-ke-bank', name: 'AYO ke Bank', category: 'regulatory', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'bangkok-bank', name: 'Bangkok Bank', category: 'bank-logo', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'bank-artha-graha-internasional', name: 'Bank Artha Graha Internasional', category: 'bank-logo', aliases: const <String>['artgidja', '037', 'bag-internasional'], tags: const <String>[]),
  LogoMeta(slug: 'bank-bengkulu', name: 'Bank Bengkulu', category: 'bank-logo', aliases: const <String>['133', 'pdbkidj1', 'bpd-bengkulu'], tags: const <String>[]),
  LogoMeta(slug: 'bank-bjb', name: 'Bank BJB', category: 'bank-logo', aliases: const <String>['110', 'bank-jabar-banten', 'pdjbidja', 'bank-pembangunan-daerah-jabar-dan-banten'], tags: const <String>[]),
  LogoMeta(slug: 'bank-bjb-syariah', name: 'Bank BJB Syariah', category: 'bank-logo', aliases: const <String>['425', 'syjbidj1', 'bank-jabar-syariah', 'bank-jabar-banten-syariah'], tags: const <String>[]),
  LogoMeta(slug: 'bank-bpd-aceh', name: 'Bank BPD Aceh', category: 'bank-logo', aliases: const <String>['116', 'bank-aceh', 'syacidj1', 'bank-aceh-syariah'], tags: const <String>[]),
  LogoMeta(slug: 'bank-bpd-bali', name: 'Bank BPD Bali', category: 'bank-logo', aliases: const <String>['129', 'bank-bali', 'abalidbs', 'bpd-bali', 'bank-pembangunan-daerah-bali'], tags: const <String>[]),
  LogoMeta(slug: 'bank-bpd-banten', name: 'Bank BPD Banten', category: 'bank-logo', aliases: const <String>['137', 'bank-banten', 'pdbbidj1', 'bpd-banten', 'bank-pembangunan-daerah-banten'], tags: const <String>[]),
  LogoMeta(slug: 'bank-bpd-diy', name: 'Bank BPD DIY', category: 'bank-logo', aliases: const <String>['112', 'bpd-diy', 'pdykidj1', 'bank-pembangunan-daerah-diy'], tags: const <String>[]),
  LogoMeta(slug: 'bank-bpd-jambi', name: 'Bank BPD Jambi', category: 'bank-logo', aliases: const <String>['115', 'bank-jambi', 'pdjmidj1', 'bpd-jambi', 'bank-pembangunan-daerah-jambi'], tags: const <String>[]),
  LogoMeta(slug: 'bank-bpd-jateng', name: 'Bank BPD Jateng', category: 'bank-logo', aliases: const <String>['113', 'bank-jateng', 'pdjgidj1', 'bank-pembangunan-daerah-jawa-tengah'], tags: const <String>[]),
  LogoMeta(slug: 'bank-bpd-jatim', name: 'Bank BPD Jatim', category: 'bank-logo', aliases: const <String>['114', 'bank-jatim', 'pdjtidj1', 'bank-pembangunan-daerah-jatim'], tags: const <String>[]),
  LogoMeta(slug: 'bank-bpd-kalbar', name: 'Bank BPD Kalbar', category: 'bank-logo', aliases: const <String>['123', 'bank-kalbar', 'pdkbidj1', 'bpd-kalbar', 'bank-pembangunan-daerah-kalbar'], tags: const <String>[]),
  LogoMeta(slug: 'bank-bpd-kalbar-alt', name: 'Bank BPD Kalbar (Alt)', category: 'bank-logo', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'bank-bpd-kalimantan-timur', name: 'Bank BPD Kalimantan Timur', category: 'bank-logo', aliases: const <String>['124', 'bank-kaltim', 'pdktidj1', 'bpd-kaltimtara', 'bank-pembangunan-daerah-kaltim-dan-kaltara'], tags: const <String>[]),
  LogoMeta(slug: 'bank-bpd-kalsel', name: 'Bank BPD Kalsel', category: 'bank-logo', aliases: const <String>['122', 'bank-kalsel', 'pdksidj1', 'bpd-kalsel', 'bank-pembangunan-daerah-kalsel'], tags: const <String>[]),
  LogoMeta(slug: 'bank-bpd-kalteng', name: 'Bank BPD Kalteng', category: 'bank-logo', aliases: const <String>['125', 'bank-kalteng', 'pdkgidj1', 'bpd-kalteng', 'bpd-kalimantan-tengah'], tags: const <String>[]),
  LogoMeta(slug: 'bank-bpd-lampung', name: 'Bank BPD Lampung', category: 'bank-logo', aliases: const <String>['121', 'pdlpidj1', 'bank-pembangunan-daerah-lampung'], tags: const <String>[]),
  LogoMeta(slug: 'bank-bpd-maluku-malut', name: 'Bank BPD Maluku Malut', category: 'bank-logo', aliases: const <String>['131', 'bank-maluku', 'pdmlidj1', 'bank-maluku-malut', 'bank-pembangunan-daerah-maluku-dan-maluku-utara'], tags: const <String>[]),
  LogoMeta(slug: 'bank-bpd-ntb-syariah', name: 'Bank BPD NTB Syariah', category: 'bank-logo', aliases: const <String>['128', 'bank-ntb', 'pdnbidj1', 'bank-ntb-syariah', 'bank-pembangunan-daerah-nusa-tenggara-barat-syariah'], tags: const <String>[]),
  LogoMeta(slug: 'bank-bpd-ntb-syariah-alt', name: 'Bank BPD NTB Syariah (Alt)', category: 'bank-logo', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'bank-bpd-ntt', name: 'Bank BPD NTT', category: 'bank-logo', aliases: const <String>['130', 'bank-ntt', 'pdntidja', 'bpd-ntt', 'bank-pembangunan-daerah-ntt'], tags: const <String>[]),
  LogoMeta(slug: 'bank-bpd-papua', name: 'Bank BPD Papua', category: 'bank-logo', aliases: const <String>['132', 'bank-papua', 'pdijidj1', 'bpd-papua', 'bank-pembangunan-daerah-papua'], tags: const <String>[]),
  LogoMeta(slug: 'bank-bpd-riau-kepri', name: 'Bank BPD Riau Kepri', category: 'bank-logo', aliases: const <String>['119', 'bank-riau-kepri', 'pdriidja', 'bank-riau-kepri-syariah', 'bank-pembangunan-daerah-riau-kepri-syariah'], tags: const <String>[]),
  LogoMeta(slug: 'bank-bpd-riau-kepri-syariah', name: 'Bank BPD Riau Kepri Syariah', category: 'bank-logo', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'bank-bpd-sulselbar', name: 'Bank BPD Sulselbar', category: 'bank-logo', aliases: const <String>['126', 'bank-sulselbar', 'pdwsidja'], tags: const <String>[]),
  LogoMeta(slug: 'bank-bpd-sulteng', name: 'Bank BPD Sulteng', category: 'bank-logo', aliases: const <String>['134', 'bank-sulteng', 'pdwgidj1', 'bpd-sulteng', 'bpd-sulawesi-tengah'], tags: const <String>[]),
  LogoMeta(slug: 'bank-bpd-sultra', name: 'Bank BPD Sultra', category: 'bank-logo', aliases: const <String>['135', 'bank-sultra', 'pdwridj1', 'bpd-sultra', 'bpd-sulawesi-tenggara'], tags: const <String>[]),
  LogoMeta(slug: 'bank-bpd-sulutgo', name: 'Bank BPD Sulutgo', category: 'bank-logo', aliases: const <String>['127', 'bank-sulutgo', 'pdwuidj1', 'bpd-sulut', 'bpd-sulut-gorontalo'], tags: const <String>[]),
  LogoMeta(slug: 'bank-bpd-sumsel-babel', name: 'Bank BPD Sumsel Babel', category: 'bank-logo', aliases: const <String>['120', 'bank-sumsel-babel', 'bsspidsp', 'bpd-sumsel-babel', 'bpd-sumsel-dan-babel'], tags: const <String>[]),
  LogoMeta(slug: 'bank-bpd-sumsel-babel-alt', name: 'Bank BPD Sumsel Babel (Alt)', category: 'bank-logo', aliases: const <String>['bank-bpd-sumsel-babel-alt-1'], tags: const <String>[]),
  LogoMeta(slug: 'bank-bpd-sumsel-babel-alt-2', name: 'Bank BPD Sumsel Babel (Alt-2)', category: 'bank-logo', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'bank-bpd-sumut', name: 'Bank BPD Sumut', category: 'bank-logo', aliases: const <String>['117', 'bank-sumut', 'pdsuidj1', 'bank-pembangunan-daerah-sumut'], tags: const <String>[]),
  LogoMeta(slug: 'bank-bumi-artha', name: 'Bank Bumi Artha', category: 'bank-logo', aliases: const <String>['076', 'bbaiidja', 'bba', 'bank-bumi-arta'], tags: const <String>[]),
  LogoMeta(slug: 'bank-capital', name: 'Bank Capital', category: 'bank-logo', aliases: const <String>['054', 'bciaidja', 'bank-capital-indonesia'], tags: const <String>[]),
  LogoMeta(slug: 'bank-capital-alt', name: 'Bank Capital (Alt)', category: 'bank-logo', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'bank-dki-old', name: 'Bank DKI (Old)', category: 'bank-logo', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'bank-ganesha', name: 'Bank Ganesha', category: 'bank-logo', aliases: const <String>['161', 'gnesidja'], tags: const <String>[]),
  LogoMeta(slug: 'bank-ina', name: 'Bank INA', category: 'bank-logo', aliases: const <String>['513', 'iaptidja', 'bank-ina-perdana'], tags: const <String>[]),
  LogoMeta(slug: 'bank-index-selindo', name: 'Bank Index Selindo', category: 'bank-logo', aliases: const <String>['555', 'bidxidja', 'bank-index'], tags: const <String>[]),
  LogoMeta(slug: 'bank-index-selindo-alt', name: 'Bank Index Selindo (Alt)', category: 'bank-logo', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'bank-indonesia', name: 'Bank Indonesia', category: 'regulatory', aliases: const <String>['bi'], tags: const <String>[]),
  LogoMeta(slug: 'bank-jakarta', name: 'Bank Jakarta', category: 'bank-logo', aliases: const <String>['111', 'bank-dki-jakarta', 'bdkiidj1', 'bank-dki-1', 'bank-dki', 'bank-dki-alt'], tags: const <String>[]),
  LogoMeta(slug: 'bank-jasa-jakarta', name: 'Bank Jasa Jakarta', category: 'bank-logo', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'bank-lampung', name: 'Bank Lampung', category: 'bank-logo', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'bank-mas', name: 'Bank Mas', category: 'bank-logo', aliases: const <String>['bmseidja', '548', 'bank-multiarta-sentosa'], tags: const <String>[]),
  LogoMeta(slug: 'bank-maspion', name: 'Bank Maspion', category: 'bank-logo', aliases: const <String>['157', 'masdidj1'], tags: const <String>[]),
  LogoMeta(slug: 'bank-maspion-alt', name: 'Bank Maspion (Alt)', category: 'bank-logo', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'bank-mayapada', name: 'Bank Mayapada', category: 'bank-logo', aliases: const <String>['097', 'mayaidja'], tags: const <String>[]),
  LogoMeta(slug: 'bank-mayapada-alt', name: 'Bank Mayapada (Alt)', category: 'bank-logo', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'bank-mayora', name: 'Bank Mayora', category: 'bank-logo', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'bank-mestika-dharma', name: 'Bank Mestika Dharma', category: 'bank-logo', aliases: const <String>['151', 'medhids1', 'bank-mestika'], tags: const <String>[]),
  LogoMeta(slug: 'bank-nagari', name: 'Bank Nagari', category: 'bank-logo', aliases: const <String>['118', 'bank-sumbar', 'pdsbidj1'], tags: const <String>[]),
  LogoMeta(slug: 'bank-of-america', name: 'Bank of America', category: 'bank-logo', aliases: const <String>['033', 'bofaid2x', 'boa', 'bank-of-america-na'], tags: const <String>[]),
  LogoMeta(slug: 'bank-of-china', name: 'Bank of China', category: 'bank-logo', aliases: const <String>['bkchidja', '069', 'boc-limited', 'bank-of-china-hong-kong-limited'], tags: const <String>[]),
  LogoMeta(slug: 'bank-of-india', name: 'Bank of India', category: 'bank-logo', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'bank-of-india-indonesia', name: 'Bank of India Indonesia', category: 'bank-logo', aliases: const <String>['146', 'bkididja'], tags: const <String>[]),
  LogoMeta(slug: 'bank-raya', name: 'Bank Raya', category: 'bank-logo', aliases: const <String>['494', 'agtbidja', 'bank-raya-indonesia'], tags: const <String>[]),
  LogoMeta(slug: 'bank-resona-perdania', name: 'Bank Resona Perdania', category: 'bank-logo', aliases: const <String>['047', 'bpiaidja', 'bank-resona'], tags: const <String>[]),
  LogoMeta(slug: 'bank-resona-perdania-alt', name: 'Bank Resona Perdania (Alt)', category: 'bank-logo', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'bank-sahabat-sampoerna', name: 'Bank Sahabat Sampoerna', category: 'bank-logo', aliases: const <String>['523', 'sahmidja', 'bank-sampoerna'], tags: const <String>[]),
  LogoMeta(slug: 'bank-saqu', name: 'Bank Saqu', category: 'bank-logo', aliases: const <String>['jsabidj1', '472', 'bank-saqu-indonesia'], tags: const <String>[]),
  LogoMeta(slug: 'bank-saqu-alt', name: 'Bank Saqu (Alt)', category: 'bank-logo', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'bank-smbc-indonesia', name: 'Bank SMBC Indonesia', category: 'bank-logo', aliases: const <String>['suniidja', '213', 'bank-smbc'], tags: const <String>[]),
  LogoMeta(slug: 'bank-victoria', name: 'Bank Victoria', category: 'bank-logo', aliases: const <String>['victidj1', '566', 'bank-victoria-international'], tags: const <String>[]),
  LogoMeta(slug: 'bank-victoria-syariah', name: 'Bank Victoria Syariah', category: 'bank-logo', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'bank-woori-saudara', name: 'Bank Woori Saudara', category: 'bank-logo', aliases: const <String>['212', 'bsdridja', 'bank-woori-saudara-indonesia-1906'], tags: const <String>[]),
  LogoMeta(slug: 'bappebti', name: 'BAPPEBTI', category: 'regulatory', aliases: const <String>['badan-pengawas-perdagangan-berjangka-komoditi'], tags: const <String>[]),
  LogoMeta(slug: 'baznas', name: 'BAZNAS', category: 'donation', aliases: const <String>['badan-amil-zakat-nasional'], tags: const <String>[]),
  LogoMeta(slug: 'bca', name: 'BCA', category: 'bank-logo', aliases: const <String>['bank-central-asia', 'cenaidja', '014'], tags: const <String>[]),
  LogoMeta(slug: 'bca-atm', name: 'BCA ATM', category: 'switching', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'bca-debit', name: 'BCA Debit', category: 'switching', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'bca-digital', name: 'BCA Digital', category: 'bank-logo', aliases: const <String>['bbluidja', '501', 'bank-digital-bca'], tags: const <String>[]),
  LogoMeta(slug: 'bca-finance', name: 'BCA Finance', category: 'financing', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'bca-flazz', name: 'BCA Flazz', category: 'prepaid-card', aliases: const <String>['bca-flazz-new', 'flazz'], tags: const <String>[]),
  LogoMeta(slug: 'bca-flazz-alt', name: 'BCA Flazz (Alt)', category: 'prepaid-card', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'bca-flazz-old', name: 'BCA Flazz (Old)', category: 'prepaid-card', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'bca-klikpay', name: 'BCA KlikPay', category: 'direct-debit', aliases: const <String>['klikpay'], tags: const <String>[]),
  LogoMeta(slug: 'bca-life', name: 'BCA Life', category: 'insurance', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'bca-mobile', name: 'BCA Mobile', category: 'bank-app', aliases: const <String>['m-bca'], tags: const <String>[]),
  LogoMeta(slug: 'bca-syariah', name: 'BCA Syariah', category: 'bank-logo', aliases: const <String>['536', 'bsyaidja', 'bank-bca-syariah'], tags: const <String>[]),
  LogoMeta(slug: 'bea-cukai', name: 'Bea Cukai', category: 'government', aliases: const <String>['djbc'], tags: const <String>[]),
  LogoMeta(slug: 'bfi-finance', name: 'BFI Finance', category: 'financing', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'bhinneka', name: 'Bhinneka', category: 'e-commerce', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'bi-fast', name: 'BI-FAST', category: 'switching', aliases: const <String>['bifast'], tags: const <String>[]),
  LogoMeta(slug: 'biznet', name: 'Biznet', category: 'isp', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'biznet-home', name: 'Biznet Home', category: 'isp', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'blibli', name: 'Blibli', category: 'e-commerce', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'blu-bca', name: 'blu by BCA Digital', category: 'bank-logo', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'bluepay', name: 'Bluepay', category: 'e-wallet', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'bnc', name: 'BNC', category: 'bank-logo', aliases: const <String>['490', 'yudbidj1', 'bank-neo-commerce'], tags: const <String>[]),
  LogoMeta(slug: 'bni', name: 'BNI', category: 'bank-logo', aliases: const <String>['bank-negara-indonesia', 'bninidja', '009', 'bank-bni'], tags: const <String>[]),
  LogoMeta(slug: 'bni-mobile-banking', name: 'BNI Mobile Banking', category: 'bank-app', aliases: const <String>['bni-mobile'], tags: const <String>[]),
  LogoMeta(slug: 'bni-tapcash', name: 'BNI TapCash', category: 'prepaid-card', aliases: const <String>['tapcash'], tags: const <String>[]),
  LogoMeta(slug: 'bnp-paribas', name: 'BNP Paribas', category: 'bank-logo', aliases: const <String>['057', 'bnpaidja', 'bank-bnp-paribas-indonesia'], tags: const <String>[]),
  LogoMeta(slug: 'bpd', name: 'BPD', category: 'regulatory', aliases: const <String>['bank-pembangunan-daerah'], tags: const <String>[]),
  LogoMeta(slug: 'bpjs', name: 'BPJS', category: 'insurance', aliases: const <String>['bpjs-kesehatan'], tags: const <String>[]),
  LogoMeta(slug: 'bpjs-alt', name: 'BPJS (Alt)', category: 'insurance', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'bpjs-ketenagakerjaan', name: 'BPJS Ketenagakerjaan', category: 'insurance', aliases: const <String>['bpjamsostek', 'bpjs-tk'], tags: const <String>[]),
  LogoMeta(slug: 'bri', name: 'BRI', category: 'bank-logo', aliases: const <String>['bri-new', 'bank-rakyat-indonesia', 'brinidja', '002'], tags: const <String>[]),
  LogoMeta(slug: 'bri-alt', name: 'BRI (Alt)', category: 'bank-logo', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'bri-brizzi', name: 'BRI BRIZZI', category: 'prepaid-card', aliases: const <String>['brizzi'], tags: const <String>[]),
  LogoMeta(slug: 'bri-brizzi-alt', name: 'BRI BRIZZI (Alt)', category: 'prepaid-card', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'bri-direct-debit', name: 'BRI Direct Debit', category: 'direct-debit', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'bri-finance', name: 'BRI Finance', category: 'financing', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'bri-insurance', name: 'BRI Insurance', category: 'insurance', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'bri-life', name: 'BRI Life', category: 'insurance', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'bri-old', name: 'BRI (Old)', category: 'bank-logo', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'bri-vertical', name: 'BRI (Vertical)', category: 'bank-logo', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'bright', name: 'Bright', category: 'supermarket', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'brimo', name: 'BRImo', category: 'bank-app', aliases: const <String>['bri-mobile'], tags: const <String>[]),
  LogoMeta(slug: 'brins', name: 'BRINS', category: 'insurance', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'bsi', name: 'BSI', category: 'bank-logo', aliases: const <String>['bank-syariah-indonesia', 'bsmdidja', '451'], tags: const <String>[]),
  LogoMeta(slug: 'bsi-mobile', name: 'BSI Mobile', category: 'bank-app', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'bsn', name: 'BSN', category: 'bank-logo', aliases: const <String>['swagidj1', '405', 'bank-syariah-nasional'], tags: const <String>[]),
  LogoMeta(slug: 'bsn-alt', name: 'BSN (Alt)', category: 'bank-logo', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'btn', name: 'BTN', category: 'bank-logo', aliases: const <String>['btn-new', 'bank-tabungan-negara', 'btanidja', '200'], tags: const <String>[]),
  LogoMeta(slug: 'btn-alt', name: 'BTN (Alt)', category: 'bank-logo', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'btn-old', name: 'BTN (Old)', category: 'bank-logo', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'btn-syariah', name: 'BTN Syariah', category: 'bank-logo', aliases: const <String>['btn-syariah-new'], tags: const <String>[]),
  LogoMeta(slug: 'btn-syariah-old', name: 'BTN Syariah (Old)', category: 'bank-logo', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'btpn', name: 'BTPN', category: 'bank-logo', aliases: const <String>['bank-tabungan-pensiunan-nasional'], tags: const <String>[]),
  LogoMeta(slug: 'btpn-syariah', name: 'BTPN Syariah', category: 'bank-logo', aliases: const <String>['547', 'pubaidj1', 'bank-btpn-syariah'], tags: const <String>[]),
  LogoMeta(slug: 'bukalapak', name: 'Bukalapak', category: 'e-commerce', aliases: const <String>['bukalapak-new'], tags: const <String>[]),
  LogoMeta(slug: 'bukalapak-alt', name: 'Bukalapak (Alt)', category: 'e-commerce', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'bukalapak-old', name: 'Bukalapak (Old)', category: 'e-commerce', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'bumiputera', name: 'Bumiputera', category: 'insurance', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'bussan-auto-finance', name: 'Bussan Auto Finance', category: 'financing', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'by-u', name: 'by.U', category: 'mobile-telco', aliases: const <String>['byu'], tags: const <String>[]),
  LogoMeta(slug: 'byond-bsi', name: 'BYOND by BSI', category: 'bank-app', aliases: const <String>['byond'], tags: const <String>[]),
  LogoMeta(slug: 'byond-bsi-alt', name: 'BYOND by BSI (Alt)', category: 'bank-app', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'catchplay', name: 'Catchplay', category: 'entertainment', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'cbn', name: 'CBN', category: 'isp', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'ccb-indonesia', name: 'CCB Indonesia', category: 'bank-logo', aliases: const <String>['036', 'mcoridja', 'china-construction-bank', 'bank-china-construction-bank-indonesia'], tags: const <String>[]),
  LogoMeta(slug: 'ccb-indonesia-alt', name: 'CCB Indonesia (Alt)', category: 'bank-logo', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'cgv', name: 'CGV', category: 'entertainment', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'chubb', name: 'CHUBB', category: 'insurance', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'cimb-niaga', name: 'CIMB Niaga', category: 'bank-logo', aliases: const <String>['bank-cimb-niaga', 'bniaidja', '022', 'bank-cimb'], tags: const <String>[]),
  LogoMeta(slug: 'cimb-niaga-syariah', name: 'CIMB Niaga Syariah', category: 'bank-logo', aliases: const <String>['synaidj1', 'bank-cimb-niaga-uus', 'bank-cimb-niaga-unit-usaha-syariah'], tags: const <String>[]),
  LogoMeta(slug: 'cinepolis', name: 'Cinepolis', category: 'entertainment', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'circle-k', name: 'Circle K', category: 'supermarket', aliases: const <String>['circlek'], tags: const <String>[]),
  LogoMeta(slug: 'circle-k-alt', name: 'Circle K (Alt)', category: 'supermarket', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'cirrus', name: 'Cirrus', category: 'card-payment', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'citibank', name: 'Citibank', category: 'bank-logo', aliases: const <String>['citiidjx', '031', 'citibank-na'], tags: const <String>[]),
  LogoMeta(slug: 'citibank-alt', name: 'Citibank (Alt)', category: 'bank-logo', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'cititrans', name: 'Cititrans', category: 'transportation', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'commonwealth', name: 'Commonwealth', category: 'bank-logo', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'commonwealth-life', name: 'Commonwealth Life', category: 'insurance', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'contactless', name: 'Contactless', category: 'card-payment', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'contactless-alt', name: 'Contactless (Alt)', category: 'card-payment', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'credit-suisse', name: 'Credit Suisse', category: 'bank-logo', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'ctbc-bank', name: 'CTBC Bank', category: 'bank-logo', aliases: const <String>['ctcbidja', '949', 'ctbc-indonesia', 'bank-ctbc-indonesia'], tags: const <String>[]),
  LogoMeta(slug: 'daihatsu-financial-service', name: 'Daihatsu Financial Service', category: 'financing', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'dakota-cargo', name: 'Dakota Cargo', category: 'logistic', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'dakota-logistik', name: 'Dakota Logistik', category: 'logistic', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'damri', name: 'DAMRI', category: 'transportation', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'dan-plus-dan', name: 'Dan+Dan', category: 'supermarket', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'dana', name: 'DANA', category: 'e-wallet', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'danamon', name: 'Danamon', category: 'bank-logo', aliases: const <String>['bank-danamon', 'bdinidja', '011', 'bank-danamon-indonesia'], tags: const <String>[]),
  LogoMeta(slug: 'danamon-mufg', name: 'Danamon (MUFG)', category: 'bank-logo', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'danamon-syariah', name: 'Danamon Syariah', category: 'bank-logo', aliases: const <String>['sybdidj1', 'bank-danamon-uus', 'bank-danamon-indonesia-unit-usaha-syariah'], tags: const <String>[]),
  LogoMeta(slug: 'daytrans', name: 'DayTrans', category: 'transportation', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'dbs', name: 'DBS', category: 'bank-logo', aliases: const <String>['dbsbidja', '046', 'bank-dbs-indonesia'], tags: const <String>[]),
  LogoMeta(slug: 'dbs-paylah', name: 'DBS Paylah', category: 'miscellaneous', aliases: const <String>['paylah'], tags: const <String>[]),
  LogoMeta(slug: 'deutsche-bank', name: 'Deutsche Bank', category: 'bank-logo', aliases: const <String>['deutidja', '067', 'deutsche-bank-ag'], tags: const <String>[]),
  LogoMeta(slug: 'dhl-express', name: 'DHL Express', category: 'logistic', aliases: const <String>['dhl'], tags: const <String>[]),
  LogoMeta(slug: 'digibank', name: 'Digibank', category: 'bank-app', aliases: const <String>['dbs-digibank'], tags: const <String>[]),
  LogoMeta(slug: 'digibank-alt', name: 'Digibank (Alt)', category: 'bank-app', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'dipay', name: 'Dipay', category: 'e-wallet', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'discover', name: 'Discover', category: 'card-payment', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'discover-alt', name: 'Discover (Alt)', category: 'card-payment', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'disney-plus', name: 'Disney+', category: 'entertainment', aliases: const <String>['disneyplus'], tags: const <String>[]),
  LogoMeta(slug: 'disney-plus-hotstar', name: 'Disney+ Hotstar', category: 'entertainment', aliases: const <String>['hotstar'], tags: const <String>[]),
  LogoMeta(slug: 'djp-online', name: 'DJP Online', category: 'government', aliases: const <String>['djp'], tags: const <String>[]),
  LogoMeta(slug: 'djp-online-alt', name: 'DJP Online (Alt)', category: 'government', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'doku', name: 'DOKU', category: 'e-wallet', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'dompet-dhuafa', name: 'Dompet Dhuafa', category: 'donation', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'dompet-dhuafa-alt', name: 'Dompet Dhuafa (Alt)', category: 'donation', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'duitnow', name: 'DuitNow', category: 'qr-payment', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'duitnow-qr', name: 'DuitNow QR', category: 'qr-payment', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'dutamoney', name: 'Dutamoney', category: 'e-wallet', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'e-toll-card', name: 'e-Toll Card', category: 'prepaid-card', aliases: const <String>['etoll', 'e-toll'], tags: const <String>[]),
  LogoMeta(slug: 'ea-play', name: 'EA Play', category: 'game', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'ea-play-alt', name: 'EA Play (Alt)', category: 'game', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'ekonomi-syariah', name: 'Ekonomi Syariah', category: 'regulatory', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'ekonomi-syariah-alt', name: 'Ekonomi Syariah (Alt)', category: 'regulatory', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'ems', name: 'EMS', category: 'logistic', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'epic-games', name: 'Epic Games', category: 'game', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'epic-games-store', name: 'Epic Games Store', category: 'game', aliases: const <String>['epic-store'], tags: const <String>[]),
  LogoMeta(slug: 'esl-express', name: 'ESL Express', category: 'logistic', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'espay', name: 'Espay', category: 'payment-gateway', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'family-mart', name: 'Family Mart', category: 'supermarket', aliases: const <String>['familymart'], tags: const <String>[]),
  LogoMeta(slug: 'fedex-express', name: 'FedEx Express', category: 'logistic', aliases: const <String>['fedex'], tags: const <String>[]),
  LogoMeta(slug: 'fif-astra', name: 'FIF Astra', category: 'financing', aliases: const <String>['fif'], tags: const <String>[]),
  LogoMeta(slug: 'finmas', name: 'Finmas', category: 'financing', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'finpay', name: 'Finpay', category: 'payment-gateway', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'first-logistic', name: 'First Logistic', category: 'logistic', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'first-media', name: 'First Media', category: 'isp', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'flip', name: 'Flip', category: 'remittance', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'fwd', name: 'FWD', category: 'insurance', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'generali', name: 'Generali', category: 'insurance', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'giant', name: 'Giant', category: 'supermarket', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'google-pay', name: 'Google Pay', category: 'miscellaneous', aliases: const <String>['gpay', 'googlepay'], tags: const <String>[]),
  LogoMeta(slug: 'google-play', name: 'Google Play', category: 'game', aliases: const <String>['play-store', 'google-play-store'], tags: const <String>[]),
  LogoMeta(slug: 'google-play-alt', name: 'Google Play (Alt)', category: 'game', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'gopay', name: 'GoPay', category: 'e-wallet', aliases: const <String>['go-pay'], tags: const <String>[]),
  LogoMeta(slug: 'gopay-alt', name: 'GoPay (Alt)', category: 'e-wallet', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'gopaylater', name: 'GoPay Later', category: 'financing', aliases: const <String>['gopay-later'], tags: const <String>[]),
  LogoMeta(slug: 'gpn', name: 'GPN', category: 'card-payment', aliases: const <String>['gerbang-pembayaran-nasional'], tags: const <String>[]),
  LogoMeta(slug: 'grab-pay', name: 'Grab Pay', category: 'miscellaneous', aliases: const <String>['grabpay'], tags: const <String>[]),
  LogoMeta(slug: 'hbo-go', name: 'HBO GO', category: 'entertainment', aliases: const <String>['hbogo'], tags: const <String>[]),
  LogoMeta(slug: 'hero', name: 'Hero', category: 'supermarket', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'hibank', name: 'hibank', category: 'bank-logo', aliases: const <String>['hbniidja', '553', 'bank-hibank-indonesia'], tags: const <String>[]),
  LogoMeta(slug: 'home-credit', name: 'Home Credit', category: 'financing', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'hoox', name: 'HOOX', category: 'entertainment', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'hsbc', name: 'HSBC', category: 'bank-logo', aliases: const <String>['hsbcidja', '087', 'bank-hsbc-indonesia'], tags: const <String>[]),
  LogoMeta(slug: 'hypermart', name: 'Hypermart', category: 'supermarket', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'i-saku', name: 'i.saku', category: 'e-wallet', aliases: const <String>['isaku'], tags: const <String>[]),
  LogoMeta(slug: 'ibk-bank', name: 'IBK Bank', category: 'bank-logo', aliases: const <String>['ibkoidja', '945', 'bank-ibk', 'bank-ibk-indonesia'], tags: const <String>[]),
  LogoMeta(slug: 'icbc', name: 'ICBC', category: 'bank-logo', aliases: const <String>['164', 'icbkidja', 'bank-icbc', 'bank-icbc-indonesia'], tags: const <String>[]),
  LogoMeta(slug: 'icbc-alt', name: 'ICBC (Alt)', category: 'bank-logo', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'iconnet', name: 'Iconnet', category: 'isp', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'id-express', name: 'ID Express', category: 'logistic', aliases: const <String>['idexpress'], tags: const <String>[]),
  LogoMeta(slug: 'im3', name: 'IM3', category: 'mobile-telco', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'indah-cargo', name: 'Indah Cargo', category: 'logistic', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'indihome', name: 'IndiHome', category: 'isp', aliases: const <String>['indihome-new', 'indi-home'], tags: const <String>[]),
  LogoMeta(slug: 'indihome-old', name: 'IndiHome (Old)', category: 'isp', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'indodana', name: 'Indodana', category: 'financing', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'indogrosir', name: 'Indogrosir', category: 'supermarket', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'indomaret', name: 'Indomaret', category: 'supermarket', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'indosat-hifi', name: 'Indosat Hifi', category: 'isp', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'indosat-m2', name: 'Indosat M2', category: 'isp', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'ing-bank', name: 'ING Bank', category: 'bank-logo', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'inklusi-keuangan', name: 'Inklusi Keuangan', category: 'regulatory', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'interlink', name: 'Interlink', category: 'miscellaneous', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'ipay88', name: 'ipay88', category: 'payment-gateway', aliases: const <String>['i-pay88'], tags: const <String>[]),
  LogoMeta(slug: 'j-and-t-cargo', name: 'J&T Cargo', category: 'logistic', aliases: const <String>['jnt-cargo'], tags: const <String>[]),
  LogoMeta(slug: 'j-and-t-express', name: 'J&T Express', category: 'logistic', aliases: const <String>['jnt', 'jnt-express'], tags: const <String>[]),
  LogoMeta(slug: 'j-trust-bank', name: 'J Trust Bank', category: 'bank-logo', aliases: const <String>['095', 'cictidja', 'bank-jtrust', 'bank-jtrust-indonesia'], tags: const <String>[]),
  LogoMeta(slug: 'jago', name: 'Jago', category: 'bank-logo', aliases: const <String>['jagbidja', '542', 'bank-jago'], tags: const <String>[]),
  LogoMeta(slug: 'jago-app', name: 'Jago', category: 'bank-app', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'jakcard', name: 'Jakcard', category: 'prepaid-card', aliases: const <String>['jak-card'], tags: const <String>[]),
  LogoMeta(slug: 'jaklingko', name: 'JakLingko', category: 'transportation', aliases: const <String>['jak-lingko'], tags: const <String>[]),
  LogoMeta(slug: 'jakone-mobile', name: 'JakOne Mobile', category: 'bank-app', aliases: const <String>['jakone'], tags: const <String>[]),
  LogoMeta(slug: 'jakone-pay', name: 'JakOne Pay', category: 'e-wallet', aliases: const <String>['jakonepay'], tags: const <String>[]),
  LogoMeta(slug: 'jalin', name: 'Jalin', category: 'switching', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'jcb', name: 'JCB', category: 'card-payment', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'jenius', name: 'Jenius', category: 'bank-logo', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'jenius-app', name: 'Jenius', category: 'bank-app', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'jenius-pay', name: 'Jenius Pay', category: 'direct-debit', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'jne', name: 'JNE', category: 'logistic', aliases: const <String>['jalur-nugraha-ekakurir'], tags: const <String>[]),
  LogoMeta(slug: 'jne-alt', name: 'JNE (Alt)', category: 'logistic', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'joox', name: 'JOOX', category: 'entertainment', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'jp-morgan-chase', name: 'JP Morgan Chase', category: 'bank-logo', aliases: const <String>['032', 'chasidjx', 'jpmorgan-bank', 'jpmorgan-chase-bank-na'], tags: const <String>[]),
  LogoMeta(slug: 'kai', name: 'KAI', category: 'transportation', aliases: const <String>['kereta-api-indonesia'], tags: const <String>[]),
  LogoMeta(slug: 'kai-bandara', name: 'KAI Bandara', category: 'transportation', aliases: const <String>['railink'], tags: const <String>[]),
  LogoMeta(slug: 'kai-commuter', name: 'KAI Commuter', category: 'transportation', aliases: const <String>['kai-commuter-new', 'krl', 'commuterline'], tags: const <String>[]),
  LogoMeta(slug: 'kai-commuter-old', name: 'KAI Commuter (Old)', category: 'transportation', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'kai-logistik', name: 'KAI Logistik', category: 'logistic', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'kartu-as', name: 'Kartu As', category: 'mobile-telco', aliases: const <String>['kartuas'], tags: const <String>[]),
  LogoMeta(slug: 'kartu-halo', name: 'Kartu Halo', category: 'mobile-telco', aliases: const <String>['kartuhalo'], tags: const <String>[]),
  LogoMeta(slug: 'kaspro', name: 'Kaspro', category: 'e-wallet', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'kb-bukopin', name: 'KB Bukopin', category: 'bank-logo', aliases: const <String>['bbukidja', '441', 'kb-indonesia', 'bank-kb-indonesia'], tags: const <String>[]),
  LogoMeta(slug: 'kb-bukopin-alt', name: 'KB Bukopin (Alt)', category: 'bank-logo', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'kb-bukopin-syariah', name: 'KB Bukopin Syariah', category: 'bank-logo', aliases: const <String>['521', 'sdobidj1', 'kbbs', 'bank-kb-bukopin-syariah'], tags: const <String>[]),
  LogoMeta(slug: 'keb-hana-bank', name: 'KEB Hana Bank', category: 'bank-logo', aliases: const <String>['hnbnidja', '484', 'bank-keb-hana', 'bank-keb-hana-indonesia'], tags: const <String>[]),
  LogoMeta(slug: 'keb-hana-bank-alt', name: 'KEB Hana Bank (Alt)', category: 'bank-logo', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'kemenkeu', name: 'Kemenkeu', category: 'government', aliases: const <String>['kementerian-keuangan'], tags: const <String>[]),
  LogoMeta(slug: 'khqr', name: 'KHQR', category: 'qr-payment', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'kitabisa', name: 'Kitabisa', category: 'donation', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'kitabisa-alt', name: 'Kitabisa (Alt)', category: 'donation', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'kominfo', name: 'KOMINFO', category: 'regulatory', aliases: const <String>['komdigi', 'kementerian-komunikasi-dan-informatika'], tags: const <String>[]),
  LogoMeta(slug: 'korlantas-polri', name: 'Korlantas Polri', category: 'government', aliases: const <String>['korlantas'], tags: const <String>[]),
  LogoMeta(slug: 'kredit-pintar', name: 'Kredit Pintar', category: 'financing', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'kreditplus', name: 'KreditPlus', category: 'financing', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'kredivo', name: 'Kredivo', category: 'financing', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'krom', name: 'Krom', category: 'bank-logo', aliases: const <String>['459', 'bustidj1', 'krom-bank-indonesia'], tags: const <String>[]),
  LogoMeta(slug: 'lalamove', name: 'Lalamove', category: 'logistic', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'langitmusik', name: 'Langitmusik', category: 'entertainment', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'lao-qr', name: 'LAO QR', category: 'qr-payment', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'lawson', name: 'Lawson', category: 'supermarket', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'lazada', name: 'Lazada', category: 'e-commerce', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'lazada-express', name: 'Lazada Express', category: 'logistic', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'lexus-financial-service', name: 'Lexus Financial Service', category: 'financing', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'lexus-financial-service-alt', name: 'Lexus Financial Service (Alt)', category: 'financing', aliases: const <String>['lexus-financial-service-1'], tags: const <String>[]),
  LogoMeta(slug: 'line-bank', name: 'LINE Bank', category: 'bank-logo', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'line-bank-alt', name: 'LINE Bank (Alt)', category: 'bank-logo', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'line-pay', name: 'LINE Pay', category: 'miscellaneous', aliases: const <String>['linepay'], tags: const <String>[]),
  LogoMeta(slug: 'line-pay-alt', name: 'LINE Pay (Alt)', category: 'miscellaneous', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'link', name: 'Link', category: 'switching', aliases: const <String>['link-new'], tags: const <String>[]),
  LogoMeta(slug: 'link-alt', name: 'Link (Alt)', category: 'switching', aliases: const <String>['link-new-alt'], tags: const <String>[]),
  LogoMeta(slug: 'link-old', name: 'Link (Old)', category: 'switching', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'linkaja', name: 'LinkAja', category: 'e-wallet', aliases: const <String>['link-aja'], tags: const <String>[]),
  LogoMeta(slug: 'lion-parcel', name: 'Lion Parcel', category: 'logistic', aliases: const <String>['lionparcel'], tags: const <String>[]),
  LogoMeta(slug: 'live-on', name: 'Live.On', category: 'mobile-telco', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'lotte', name: 'Lotte', category: 'supermarket', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'lotte-grosir', name: 'Lotte Grosir', category: 'supermarket', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'lotte-mart', name: 'Lotte Mart', category: 'supermarket', aliases: const <String>['lottemart'], tags: const <String>[]),
  LogoMeta(slug: 'lps', name: 'LPS', category: 'regulatory', aliases: const <String>['lembaga-penjamin-simpanan'], tags: const <String>[]),
  LogoMeta(slug: 'lrt-jakarta', name: 'LRT Jakarta', category: 'transportation', aliases: const <String>['lrt'], tags: const <String>[]),
  LogoMeta(slug: 'maestro', name: 'Maestro', category: 'card-payment', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'mandiri', name: 'Mandiri', category: 'bank-logo', aliases: const <String>['bank-mandiri', 'bmriidja', '008'], tags: const <String>[]),
  LogoMeta(slug: 'mandiri-e-cash', name: 'Mandiri E-Cash', category: 'direct-debit', aliases: const <String>['mandiri-ecash'], tags: const <String>[]),
  LogoMeta(slug: 'mandiri-e-money', name: 'Mandiri e-money', category: 'prepaid-card', aliases: const <String>['mandiri-emoney', 'emoney'], tags: const <String>[]),
  LogoMeta(slug: 'mandiri-inhealth', name: 'Mandiri Inhealth', category: 'insurance', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'mandiri-livin', name: 'Livin\' by Mandiri', category: 'bank-app', aliases: const <String>['mandiri-livin-new', 'livin', 'livin-by-mandiri'], tags: const <String>[]),
  LogoMeta(slug: 'mandiri-livin-old', name: 'Livin\' by Mandiri (Old)', category: 'bank-app', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'mandiri-taspen', name: 'Mandiri Taspen', category: 'bank-logo', aliases: const <String>['sihbidj1', '564', 'bank-mandiri-taspen'], tags: const <String>[]),
  LogoMeta(slug: 'manulife', name: 'Manulife', category: 'insurance', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'manulife-alt', name: 'Manulife (Alt)', category: 'insurance', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'mastercard', name: 'Mastercard', category: 'card-payment', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'mastercard-black', name: 'Mastercard Black', category: 'card-payment', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'mastercard-contactless', name: 'Mastercard Contactless', category: 'card-payment', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'mastercard-contactless-alt', name: 'Mastercard Contactless (Alt)', category: 'card-payment', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'mastercard-debit', name: 'Mastercard Debit', category: 'card-payment', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'mastercard-debit-alt', name: 'Mastercard Debit (Alt)', category: 'card-payment', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'mastercard-securecode', name: 'Mastercard SecureCode', category: 'card-payment', aliases: const <String>['mastercard-securecode-new', 'securecode'], tags: const <String>[]),
  LogoMeta(slug: 'mastercard-securecode-old', name: 'Mastercard SecureCode (Old)', category: 'card-payment', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'masterpass', name: 'Masterpass', category: 'card-payment', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'masterpass-alt', name: 'Masterpass (Alt)', category: 'card-payment', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'maxstream', name: 'Maxstream', category: 'entertainment', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'maybank', name: 'Maybank', category: 'bank-logo', aliases: const <String>['016', 'ibbkidja', 'bank-maybank', 'bank-maybank-indonesia'], tags: const <String>[]),
  LogoMeta(slug: 'mega', name: 'Mega', category: 'bank-logo', aliases: const <String>['bank-mega', 'megaidja', '426'], tags: const <String>[]),
  LogoMeta(slug: 'mega-syariah', name: 'Mega Syariah', category: 'bank-logo', aliases: const <String>['506', 'butgidj1', 'bank-mega-syariah'], tags: const <String>[]),
  LogoMeta(slug: 'melsa', name: 'Melsa', category: 'isp', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'mentari-ooredoo', name: 'Mentari Ooredoo', category: 'mobile-telco', aliases: const <String>['mentari'], tags: const <String>[]),
  LogoMeta(slug: 'meps', name: 'MEPS', category: 'switching', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'midtrans', name: 'Midtrans', category: 'payment-gateway', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'mizuho-bank', name: 'Mizuho Bank', category: 'bank-logo', aliases: const <String>['mhccidja', '048', 'bank-mizuho', 'bank-mizuho-indonesia'], tags: const <String>[]),
  LogoMeta(slug: 'mnc', name: 'MNC', category: 'bank-logo', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'mnc-bank', name: 'MNC Bank', category: 'bank-logo', aliases: const <String>['485', 'bumiidja', 'bank-mnc-internasional'], tags: const <String>[]),
  LogoMeta(slug: 'mnc-vision', name: 'MNC Vision', category: 'entertainment', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'moneygram', name: 'MoneyGram', category: 'remittance', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'motion-banking', name: 'Motion Banking', category: 'bank-logo', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'motion-banking-alt', name: 'Motion Banking (Alt)', category: 'bank-logo', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'motion-pay', name: 'Motion Pay', category: 'e-wallet', aliases: const <String>['motionpay'], tags: const <String>[]),
  LogoMeta(slug: 'mrt-jakarta', name: 'MRT Jakarta', category: 'transportation', aliases: const <String>['mrt'], tags: const <String>[]),
  LogoMeta(slug: 'mtix', name: 'm.tix', category: 'entertainment', aliases: const <String>['m-tix'], tags: const <String>[]),
  LogoMeta(slug: 'muamalat', name: 'Bank Muamalat', category: 'bank-logo', aliases: const <String>['bank-muamalat', 'mualamat', 'muabidja', '147', 'bank-muamalat-indonesia'], tags: const <String>[]),
  LogoMeta(slug: 'mufg', name: 'MUFG', category: 'bank-logo', aliases: const <String>['042', 'botkidjx', 'mufg-bank-ltd'], tags: const <String>[]),
  LogoMeta(slug: 'mufg-alt', name: 'MUFG (Alt)', category: 'bank-logo', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'my-nintendo', name: 'My Nintendo', category: 'game', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'myrepublic', name: 'MyRepublic', category: 'isp', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'nanobank-syariah', name: 'Nanobank Syariah', category: 'bank-logo', aliases: const <String>['nanoidj1', '253', 'nano-bank', 'bank-nano-syariah'], tags: const <String>[]),
  LogoMeta(slug: 'nanobank-syariah-alt', name: 'Nanobank Syariah (Alt)', category: 'bank-logo', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'ncs', name: 'NCS', category: 'logistic', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'neobank', name: 'Neobank', category: 'bank-app', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'netflix', name: 'Netflix', category: 'entertainment', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'netflix-alt', name: 'Netflix (Alt)', category: 'entertainment', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'nets', name: 'NETS', category: 'miscellaneous', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'netzme', name: 'Netzme', category: 'e-wallet', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'nex-parabola', name: 'Nex Parabola', category: 'entertainment', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'nickelodeon', name: 'Nickelodeon', category: 'entertainment', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'ninja-xpress', name: 'Ninja Xpress', category: 'logistic', aliases: const <String>['ninja-express'], tags: const <String>[]),
  LogoMeta(slug: 'nintendo-online', name: 'Nintendo Online', category: 'game', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'nobu', name: 'NOBU', category: 'bank-logo', aliases: const <String>['503', 'lfibidj1', 'bank-nationalnobu'], tags: const <String>[]),
  LogoMeta(slug: 'ocbc-nisp', name: 'OCBC NISP', category: 'bank-logo', aliases: const <String>['nispidja', '028', 'bank-ocbc-nisp'], tags: const <String>[]),
  LogoMeta(slug: 'ocbc-pay-anyone', name: 'OCBC Pay Anyone', category: 'miscellaneous', aliases: const <String>['pay-anyone'], tags: const <String>[]),
  LogoMeta(slug: 'octo-clicks', name: 'OCTO Clicks', category: 'bank-app', aliases: const <String>['octo'], tags: const <String>[]),
  LogoMeta(slug: 'ojk', name: 'OJK', category: 'regulatory', aliases: const <String>['otoritas-jasa-keuangan'], tags: const <String>[]),
  LogoMeta(slug: 'ok-bank', name: 'OK Bank', category: 'bank-logo', aliases: const <String>['lmanidj1', '526', 'bank-oke', 'bank-oke-indonesia'], tags: const <String>[]),
  LogoMeta(slug: 'oneklik', name: 'OneKlik', category: 'direct-debit', aliases: const <String>['one-klik'], tags: const <String>[]),
  LogoMeta(slug: 'otto-pay', name: 'OTTO Pay', category: 'e-wallet', aliases: const <String>['ottopay'], tags: const <String>[]),
  LogoMeta(slug: 'ovo', name: 'OVO', category: 'e-wallet', aliases: const <String>['ovo-new'], tags: const <String>[]),
  LogoMeta(slug: 'ovo-alt', name: 'OVO (Alt)', category: 'e-wallet', aliases: const <String>['ovo-new-alt'], tags: const <String>[]),
  LogoMeta(slug: 'ovo-old', name: 'OVO (Old)', category: 'e-wallet', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'ovo-old-alt', name: 'OVO (Old Alt)', category: 'e-wallet', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'oxygen-id', name: 'Oxygen.id', category: 'isp', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'oxygen-id-home', name: 'Oxygen.id Home', category: 'isp', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'pam-jaya', name: 'PAM Jaya', category: 'utilities', aliases: const <String>['pam-jaya-new'], tags: const <String>[]),
  LogoMeta(slug: 'pam-jaya-old', name: 'PAM Jaya (Old)', category: 'utilities', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'pandu-logistics', name: 'Pandu Logistics', category: 'logistic', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'panin-dubai-syariah', name: 'Panin Dubai Syariah', category: 'bank-logo', aliases: const <String>['517', 'arfaidj1', 'bank-panin-dubai-syariah'], tags: const <String>[]),
  LogoMeta(slug: 'paninbank', name: 'PaninBank', category: 'bank-logo', aliases: const <String>['pinbidja', '019', 'panin-bank'], tags: const <String>[]),
  LogoMeta(slug: 'paydia', name: 'Paydia', category: 'e-wallet', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'payoneer', name: 'Payoneer', category: 'remittance', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'paypal', name: 'PayPal', category: 'remittance', aliases: const <String>['paypal-new'], tags: const <String>[]),
  LogoMeta(slug: 'paypal-old', name: 'PayPal (Old)', category: 'remittance', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'paytren', name: 'Paytren', category: 'e-wallet', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'pcp-express', name: 'PCP Express', category: 'logistic', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'pdam', name: 'PDAM', category: 'utilities', aliases: const <String>['perusahaan-daerah-air-minum'], tags: const <String>[]),
  LogoMeta(slug: 'pdam-kota-surabaya', name: 'PDAM Kota Surabaya', category: 'utilities', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'pegadaian', name: 'Pegadaian', category: 'financing', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'perbankan-syariah-ib', name: 'Perbankan Syariah (IB)', category: 'regulatory', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'permata', name: 'Permata Bank', category: 'bank-logo', aliases: const <String>['permata-bank-new', 'bank-permata', 'bbbaidja', '013'], tags: const <String>[]),
  LogoMeta(slug: 'permata-alt', name: 'Permata Bank (Alt)', category: 'bank-logo', aliases: const <String>['permata-bank-alt'], tags: const <String>[]),
  LogoMeta(slug: 'permata-old', name: 'Permata Bank (Old)', category: 'bank-logo', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'pgn', name: 'PGN', category: 'utilities', aliases: const <String>['perusahaan-gas-negara'], tags: const <String>[]),
  LogoMeta(slug: 'playstation-plus', name: 'PlayStation Plus', category: 'game', aliases: const <String>['ps-plus'], tags: const <String>[]),
  LogoMeta(slug: 'playstation-store', name: 'PlayStation Store', category: 'game', aliases: const <String>['ps-store'], tags: const <String>[]),
  LogoMeta(slug: 'pln', name: 'PLN', category: 'utilities', aliases: const <String>['perusahaan-listrik-negara'], tags: const <String>[]),
  LogoMeta(slug: 'pos-indonesia', name: 'Pos Indonesia', category: 'logistic', aliases: const <String>['pos-indonesia-new', 'posindo'], tags: const <String>[]),
  LogoMeta(slug: 'pos-indonesia-old', name: 'Pos Indonesia (Old)', category: 'logistic', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'pospay', name: 'Pospay', category: 'e-wallet', aliases: const <String>['pos-pay'], tags: const <String>[]),
  LogoMeta(slug: 'prima', name: 'PRIMA', category: 'switching', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'prima-bank', name: 'PRIMA Bank', category: 'bank-logo', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'prima-debit', name: 'PRIMA Debit', category: 'switching', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'prime-video', name: 'Prime Video', category: 'entertainment', aliases: const <String>['amazon-prime-video'], tags: const <String>[]),
  LogoMeta(slug: 'prismalink', name: 'PrismaLink', category: 'payment-gateway', aliases: const <String>['prisma-link'], tags: const <String>[]),
  LogoMeta(slug: 'prudential', name: 'Prudential', category: 'insurance', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'qnb', name: 'QNB', category: 'bank-logo', aliases: const <String>['167', 'awanidja', 'bank-qnb', 'bank-qnb-indonesia'], tags: const <String>[]),
  LogoMeta(slug: 'qoala', name: 'Qoala', category: 'insurance', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'qr-ph', name: 'QR Ph', category: 'qr-payment', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'qris', name: 'QRIS', category: 'qr-payment', aliases: const <String>['quick-response-code-indonesian-standard'], tags: const <String>[]),
  LogoMeta(slug: 'rex', name: 'REX', category: 'logistic', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'ria-money', name: 'Ria Money', category: 'remittance', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'rpx', name: 'RPX', category: 'logistic', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'rumah-zakat', name: 'Rumah Zakat', category: 'donation', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'rumah-zakat-alt', name: 'Rumah Zakat (Alt)', category: 'donation', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'samsung-card', name: 'Samsung Card', category: 'card-payment', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'samsung-pay', name: 'Samsung Pay', category: 'miscellaneous', aliases: const <String>['samsungpay'], tags: const <String>[]),
  LogoMeta(slug: 'samsung-pay-alt', name: 'Samsung Pay (Alt)', category: 'miscellaneous', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'sap-express', name: 'SAP Express', category: 'logistic', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'sbi-indonesia', name: 'SBI Indonesia', category: 'bank-logo', aliases: const <String>['sbididja', '498', 'bank-sbi', 'bank-sbi-indonesia'], tags: const <String>[]),
  LogoMeta(slug: 'seabank', name: 'SeaBank', category: 'bank-logo', aliases: const <String>['sspiidja', '535', 'bank-seabank-indonesia'], tags: const <String>[]),
  LogoMeta(slug: 'seabank-alt', name: 'SeaBank (Alt)', category: 'bank-logo', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'sequis', name: 'Sequis', category: 'insurance', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'sgqr', name: 'SGQR', category: 'qr-payment', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'sgqr-plus', name: 'SGQR+', category: 'qr-payment', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'shinhan-bank', name: 'Shinhan Bank', category: 'bank-logo', aliases: const <String>['152', 'meekidj1', 'bank-shinhan', 'bank-shinhan-indonesia'], tags: const <String>[]),
  LogoMeta(slug: 'shinhan-bank-alt', name: 'Shinhan Bank (Alt)', category: 'bank-logo', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'shopee', name: 'Shopee', category: 'e-commerce', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'shopee-alt', name: 'Shopee (Alt)', category: 'e-commerce', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'shopee-pay', name: 'Shopee Pay', category: 'e-wallet', aliases: const <String>['shopeepay'], tags: const <String>[]),
  LogoMeta(slug: 'sicepat-ekspres', name: 'SiCepat Ekspres', category: 'logistic', aliases: const <String>['sicepat'], tags: const <String>[]),
  LogoMeta(slug: 'simpati', name: 'simPATI', category: 'mobile-telco', aliases: const <String>['simpati-new'], tags: const <String>[]),
  LogoMeta(slug: 'simpati-old', name: 'simPATI (Old)', category: 'mobile-telco', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'sinarmas', name: 'Sinarmas', category: 'bank-logo', aliases: const <String>['sbjkidja', '153', 'bank-sinarmas'], tags: const <String>[]),
  LogoMeta(slug: 'sinarmas-syariah', name: 'Sinarmas Syariah', category: 'bank-logo', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'skrill', name: 'Skrill', category: 'remittance', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'smartfren', name: 'Smartfren', category: 'mobile-telco', aliases: const <String>['smart-fren'], tags: const <String>[]),
  LogoMeta(slug: 'smartfren-old', name: 'Smartfren (Old)', category: 'mobile-telco', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'speedcash', name: 'SpeedCash', category: 'e-wallet', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'spotify', name: 'Spotify', category: 'entertainment', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'spotify-alt', name: 'Spotify (Alt)', category: 'entertainment', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'spx-express', name: 'SPX Express', category: 'logistic', aliases: const <String>['shopee-express', 'spx'], tags: const <String>[]),
  LogoMeta(slug: 'standard-chartered', name: 'Standard Chartered', category: 'bank-logo', aliases: const <String>['050', 'scblidjx', 'standchard', 'standard-chartered-bank'], tags: const <String>[]),
  LogoMeta(slug: 'steam', name: 'Steam', category: 'game', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'stripe', name: 'Stripe', category: 'payment-gateway', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'sun-life', name: 'Sun Life', category: 'insurance', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'super-indo', name: 'Super Indo', category: 'supermarket', aliases: const <String>['superindo'], tags: const <String>[]),
  LogoMeta(slug: 'superbank', name: 'Superbank', category: 'bank-logo', aliases: const <String>['famaidj1', '562', 'super-bank', 'super-bank-indonesia'], tags: const <String>[]),
  LogoMeta(slug: 'superbank-alt', name: 'Superbank (Alt)', category: 'bank-logo', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'swift', name: 'SWIFT', category: 'remittance', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'swift-alt', name: 'SWIFT (Alt)', category: 'remittance', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'taf-toyota-astra-financial', name: 'TAF - Toyota Astra Financial', category: 'financing', aliases: const <String>['taf', 'toyota-astra-financial'], tags: const <String>[]),
  LogoMeta(slug: 'taspen', name: 'Taspen', category: 'insurance', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'telkomsel', name: 'Telkomsel', category: 'mobile-telco', aliases: const <String>['tsel'], tags: const <String>[]),
  LogoMeta(slug: 'telkomsel-alt', name: 'Telkomsel (Alt)', category: 'mobile-telco', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'telkomsel-halo', name: 'Telkomsel Halo', category: 'mobile-telco', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'telkomsel-orbit', name: 'Telkomsel Orbit', category: 'isp', aliases: const <String>['orbit'], tags: const <String>[]),
  LogoMeta(slug: 'telkomsel-prabayar', name: 'Telkomsel Prabayar', category: 'mobile-telco', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'thai-qr-payment', name: 'Thai QR Payment', category: 'qr-payment', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'thai-qr-payment-alt', name: 'Thai QR Payment (Alt)', category: 'qr-payment', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'the-foodhall', name: 'The Foodhall', category: 'supermarket', aliases: const <String>['foodhall'], tags: const <String>[]),
  LogoMeta(slug: 'tiki', name: 'TIKI', category: 'logistic', aliases: const <String>['titipan-kilat'], tags: const <String>[]),
  LogoMeta(slug: 'tiktok-shop', name: 'TikTok Shop', category: 'e-commerce', aliases: const <String>['tiktokshop'], tags: const <String>[]),
  LogoMeta(slug: 'tokopedia', name: 'Tokopedia', category: 'e-commerce', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'tokopedia-alt', name: 'Tokopedia (Alt)', category: 'e-commerce', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'topremit', name: 'Topremit', category: 'remittance', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'topremit-alt', name: 'Topremit (Alt)', category: 'remittance', aliases: const <String>['topremit-1'], tags: const <String>[]),
  LogoMeta(slug: 'toserba-yogya', name: 'Toserba Yogya', category: 'supermarket', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'toyota-financial-service', name: 'Toyota Financial Service', category: 'financing', aliases: const <String>['tfs'], tags: const <String>[]),
  LogoMeta(slug: 'transfez', name: 'Transfez', category: 'remittance', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'transjakarta', name: 'TransJakarta', category: 'transportation', aliases: const <String>['trans-jakarta', 'busway'], tags: const <String>[]),
  LogoMeta(slug: 'transmart', name: 'Transmart', category: 'supermarket', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'transvision', name: 'TransVision', category: 'entertainment', aliases: const <String>['transvision-new'], tags: const <String>[]),
  LogoMeta(slug: 'transvision-old', name: 'TransVision (Old)', category: 'entertainment', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'tri', name: 'Tri', category: 'mobile-telco', aliases: const <String>['three'], tags: const <String>[]),
  LogoMeta(slug: 'truemoney', name: 'TrueMoney', category: 'e-wallet', aliases: const <String>['true-money'], tags: const <String>[]),
  LogoMeta(slug: 'uangku', name: 'Uangku', category: 'e-wallet', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'ubisoft-plus', name: 'UBISOFT+', category: 'game', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'union-pay', name: 'UnionPay', category: 'card-payment', aliases: const <String>['unionpay'], tags: const <String>[]),
  LogoMeta(slug: 'union-pay-contactless', name: 'UnionPay Contactless', category: 'card-payment', aliases: const <String>['unionpay-contactless'], tags: const <String>[]),
  LogoMeta(slug: 'union-pay-contactless-en', name: 'UnionPay Contactless (EN)', category: 'card-payment', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'union-pay-en', name: 'UnionPay (EN)', category: 'card-payment', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'uob', name: 'UOB', category: 'bank-logo', aliases: const <String>['023', 'bbijidja', 'uob-indonesia', 'bank-uob-indonesia'], tags: const <String>[]),
  LogoMeta(slug: 'uob-ez-pay', name: 'UOB EZ Pay', category: 'direct-debit', aliases: const <String>['uob-ezpay'], tags: const <String>[]),
  LogoMeta(slug: 'uob-tmrw', name: 'UOB TMRW', category: 'bank-app', aliases: const <String>['tmrw'], tags: const <String>[]),
  LogoMeta(slug: 'verified-by-visa', name: 'Verified by VISA', category: 'card-payment', aliases: const <String>['verified-by-visa-new', 'vbv'], tags: const <String>[]),
  LogoMeta(slug: 'verified-by-visa-old', name: 'Verified by VISA (Old)', category: 'card-payment', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'verifone', name: 'Verifone', category: 'miscellaneous', aliases: const <String>['verifone-new'], tags: const <String>[]),
  LogoMeta(slug: 'verifone-old', name: 'Verifone (Old)', category: 'miscellaneous', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'vidio', name: 'Vidio', category: 'entertainment', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'vietqr', name: 'VietQR', category: 'qr-payment', aliases: const <String>['viet-qr'], tags: const <String>[]),
  LogoMeta(slug: 'visa', name: 'VISA', category: 'card-payment', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'visa-checkout', name: 'VISA Checkout', category: 'card-payment', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'visa-debit', name: 'VISA Debit', category: 'card-payment', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'visa-pay', name: 'VISA Pay', category: 'card-payment', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'visa-paywave', name: 'VISA PayWave', category: 'card-payment', aliases: const <String>['paywave'], tags: const <String>[]),
  LogoMeta(slug: 'visa-plus', name: 'VISA Plus', category: 'card-payment', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'visa-secure-3ds', name: 'VISA Secure (3DS)', category: 'card-payment', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'visa-signature', name: 'VISA Signature', category: 'card-payment', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'vision-plus', name: 'Vision+', category: 'entertainment', aliases: const <String>['visionplus'], tags: const <String>[]),
  LogoMeta(slug: 'viu', name: 'VIU', category: 'entertainment', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'wahana-express', name: 'Wahana Express', category: 'logistic', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'wahana-express-alt', name: 'Wahana Express (Alt)', category: 'logistic', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'wechat-pay', name: 'WeChat Pay', category: 'miscellaneous', aliases: const <String>['wechatpay', 'weixin-pay'], tags: const <String>[]),
  LogoMeta(slug: 'wechat-pay-alt', name: 'WeChat Pay (Alt)', category: 'miscellaneous', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'welab-bank', name: 'Welab Bank', category: 'bank-logo', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'western-union', name: 'Western Union', category: 'remittance', aliases: const <String>['wu'], tags: const <String>[]),
  LogoMeta(slug: 'whoosh', name: 'Whoosh', category: 'transportation', aliases: const <String>['kcic'], tags: const <String>[]),
  LogoMeta(slug: 'wirecard', name: 'Wirecard', category: 'miscellaneous', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'wise', name: 'Wise', category: 'remittance', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'wom-finance', name: 'WOM Finance', category: 'financing', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'wondr-by-bni', name: 'Wondr by BNI', category: 'bank-app', aliases: const <String>['wondr'], tags: const <String>[]),
  LogoMeta(slug: 'world-bank', name: 'World Bank', category: 'regulatory', aliases: const <String>['bank-dunia'], tags: const <String>[]),
  LogoMeta(slug: 'world-bank-alt', name: 'World Bank (Alt)', category: 'regulatory', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'xbox-game-pass', name: 'XBOX Game Pass', category: 'game', aliases: const <String>['game-pass'], tags: const <String>[]),
  LogoMeta(slug: 'xendit', name: 'Xendit', category: 'payment-gateway', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'xl', name: 'XL', category: 'mobile-telco', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'xl-prioritas', name: 'XL Prioritas', category: 'mobile-telco', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'xl-satu', name: 'XL Satu', category: 'isp', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'xl-smart', name: 'XL Smart', category: 'mobile-telco', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'xl-smart-alt', name: 'XL SMART (Alt)', category: 'mobile-telco', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'xxi-21', name: 'XXI (21)', category: 'entertainment', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'yomart', name: 'Yomart', category: 'supermarket', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'yukk', name: 'Yukk', category: 'e-wallet', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'zalora', name: 'Zalora', category: 'e-commerce', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'zurich', name: 'Zurich', category: 'insurance', aliases: const <String>[], tags: const <String>[]),
  LogoMeta(slug: 'zurich-alt', name: 'Zurich (Alt)', category: 'insurance', aliases: const <String>[], tags: const <String>[]),
];

const List<Category> catalogCategories = <Category>[
  Category(slug: 'bank-app', displayName: 'Bank App', count: 17),
  Category(slug: 'bank-logo', displayName: 'Bank Logo', count: 160),
  Category(slug: 'card-payment', displayName: 'Card Payment', count: 37),
  Category(slug: 'direct-debit', displayName: 'Direct Debit', count: 6),
  Category(slug: 'donation', displayName: 'Donation', count: 7),
  Category(slug: 'e-commerce', displayName: 'E-Commerce', count: 12),
  Category(slug: 'e-wallet', displayName: 'E-Wallet', count: 27),
  Category(slug: 'entertainment', displayName: 'Entertainment', count: 26),
  Category(slug: 'financing', displayName: 'Financing', count: 27),
  Category(slug: 'game', displayName: 'Game', count: 15),
  Category(slug: 'government', displayName: 'Government', count: 5),
  Category(slug: 'insurance', displayName: 'Insurance', count: 29),
  Category(slug: 'isp', displayName: 'ISP', count: 15),
  Category(slug: 'logistic', displayName: 'Logistic', count: 33),
  Category(slug: 'miscellaneous', displayName: 'Miscellaneous', count: 21),
  Category(slug: 'mobile-telco', displayName: 'Mobile Telco', count: 20),
  Category(slug: 'payment-gateway', displayName: 'Payment Gateway', count: 10),
  Category(slug: 'prepaid-card', displayName: 'Prepaid Card', count: 9),
  Category(slug: 'qr-payment', displayName: 'QR Payment', count: 11),
  Category(slug: 'regulatory', displayName: 'Regulatory', count: 15),
  Category(slug: 'remittance', displayName: 'Remittance', count: 14),
  Category(slug: 'supermarket', displayName: 'Supermarket', count: 24),
  Category(slug: 'switching', displayName: 'Switching', count: 13),
  Category(slug: 'transportation', displayName: 'Transportation', count: 12),
  Category(slug: 'utilities', displayName: 'Utilities', count: 7),
];
