// Generated file — do not edit by hand.
// Source: data/logos.yml. Regenerate via `npm run build:ios`.
//
// Logo SVGs are licensed CC-BY-NC-4.0 (see LICENSE-ASSETS at repo root).
// This Swift code is licensed MIT (see LICENSE at repo root).

import Foundation

internal enum Catalog {
    static let version: String = "2.4.0"

    static let logos: [LogoMeta] = [
        LogoMeta(slug: "2c2p", name: "2c2p", category: "payment-gateway", aliases: ["2c2p-new"], tags: []),
        LogoMeta(slug: "2c2p-alt", name: "2c2p (Alt)", category: "payment-gateway", aliases: ["2c2p-new-alt"], tags: []),
        LogoMeta(slug: "2c2p-old", name: "2c2p (Old)", category: "payment-gateway", aliases: [], tags: []),
        LogoMeta(slug: "acc", name: "ACC", category: "financing", aliases: [], tags: []),
        LogoMeta(slug: "acc-alt", name: "ACC (Alt)", category: "financing", aliases: [], tags: []),
        LogoMeta(slug: "adakami", name: "AdaKami", category: "financing", aliases: [], tags: []),
        LogoMeta(slug: "adakami-alt", name: "AdaKami (Alt)", category: "financing", aliases: [], tags: []),
        LogoMeta(slug: "adira-finance", name: "Adira Finance", category: "financing", aliases: [], tags: []),
        LogoMeta(slug: "aeon", name: "AEON", category: "supermarket", aliases: [], tags: []),
        LogoMeta(slug: "aeon-credit-service", name: "AEON Credit Service", category: "financing", aliases: ["aeon-credit"], tags: []),
        LogoMeta(slug: "aetra-tangerang", name: "Aetra Tangerang", category: "utilities", aliases: [], tags: []),
        LogoMeta(slug: "afpi", name: "AFPI", category: "regulatory", aliases: ["asosiasi-fintech-pendanaan-bersama-indonesia"], tags: []),
        LogoMeta(slug: "aia", name: "AIA", category: "insurance", aliases: [], tags: []),
        LogoMeta(slug: "akulaku", name: "Akulaku", category: "financing", aliases: [], tags: []),
        LogoMeta(slug: "akulaku-paylater", name: "Akulaku Paylater", category: "financing", aliases: ["akulaku-pay-later"], tags: []),
        LogoMeta(slug: "aladin", name: "Aladin", category: "bank-logo", aliases: ["947", "netbidja", "bank-aladin-syariah"], tags: []),
        LogoMeta(slug: "alfa-express", name: "Alfa Express", category: "supermarket", aliases: [], tags: []),
        LogoMeta(slug: "alfamart", name: "Alfamart", category: "supermarket", aliases: [], tags: []),
        LogoMeta(slug: "alfamidi", name: "Alfamidi", category: "supermarket", aliases: [], tags: []),
        LogoMeta(slug: "alfamidi-super", name: "Alfamidi Super", category: "supermarket", aliases: [], tags: []),
        LogoMeta(slug: "alipay", name: "Alipay", category: "miscellaneous", aliases: ["alipay-new", "ali-pay"], tags: []),
        LogoMeta(slug: "alipay-old", name: "Alipay (Old)", category: "miscellaneous", aliases: [], tags: []),
        LogoMeta(slug: "alipay-plus", name: "Alipay+", category: "miscellaneous", aliases: ["alipayplus"], tags: []),
        LogoMeta(slug: "alipay-plus-old", name: "Alipay+ (Old)", category: "miscellaneous", aliases: [], tags: []),
        LogoMeta(slug: "alipay-plus-old-alt", name: "Alipay+ (Old Alt)", category: "miscellaneous", aliases: [], tags: []),
        LogoMeta(slug: "allianz", name: "Allianz", category: "insurance", aliases: [], tags: []),
        LogoMeta(slug: "allianz-alt", name: "Allianz (Alt)", category: "insurance", aliases: [], tags: []),
        LogoMeta(slug: "allo", name: "Allo", category: "bank-logo", aliases: ["567", "alobidja", "allo-bank-indonesia"], tags: []),
        LogoMeta(slug: "alto", name: "ALTO", category: "switching", aliases: [], tags: []),
        LogoMeta(slug: "amar-bank", name: "Amar Bank", category: "bank-logo", aliases: ["531", "lomaidj1", "bank-amar", "bank-amar-indonesia"], tags: []),
        LogoMeta(slug: "american-express", name: "American Express", category: "card-payment", aliases: ["amex"], tags: []),
        LogoMeta(slug: "american-express-alt", name: "American Express (Alt)", category: "card-payment", aliases: ["amercian-express-alt"], tags: []),
        LogoMeta(slug: "american-express-alt-2", name: "American Express (Alt-2)", category: "card-payment", aliases: [], tags: []),
        LogoMeta(slug: "anteraja", name: "AnterAja", category: "logistic", aliases: ["anter-aja"], tags: []),
        LogoMeta(slug: "anz", name: "ANZ", category: "bank-logo", aliases: ["061", "anzbidjx", "anz-indonesia", "bank-anz-indonesia"], tags: []),
        LogoMeta(slug: "app-store", name: "App Store", category: "game", aliases: ["apple-app-store"], tags: []),
        LogoMeta(slug: "apple-arcade", name: "Apple Arcade", category: "game", aliases: [], tags: []),
        LogoMeta(slug: "apple-card", name: "Apple Card", category: "card-payment", aliases: [], tags: []),
        LogoMeta(slug: "apple-music", name: "Apple Music", category: "entertainment", aliases: [], tags: []),
        LogoMeta(slug: "apple-pay", name: "Apple Pay", category: "miscellaneous", aliases: ["applepay"], tags: []),
        LogoMeta(slug: "aspi", name: "ASPI", category: "regulatory", aliases: ["asosiasi-sistem-pembayaran-indonesia"], tags: []),
        LogoMeta(slug: "assa", name: "ASSA", category: "logistic", aliases: [], tags: []),
        LogoMeta(slug: "astra-life", name: "Astra Life", category: "insurance", aliases: [], tags: []),
        LogoMeta(slug: "astra-life-alt", name: "Astra Life (Alt)", category: "insurance", aliases: [], tags: []),
        LogoMeta(slug: "astra-pay", name: "Astra Pay", category: "e-wallet", aliases: ["astrapay"], tags: []),
        LogoMeta(slug: "asuransi-sinarmas-insurtech", name: "Asuransi Sinarmas Insurtech", category: "insurance", aliases: [], tags: []),
        LogoMeta(slug: "atm-bersama", name: "ATM Bersama", category: "switching", aliases: [], tags: []),
        LogoMeta(slug: "atm-link", name: "ATM Link", category: "switching", aliases: [], tags: []),
        LogoMeta(slug: "axa", name: "AXA", category: "insurance", aliases: [], tags: []),
        LogoMeta(slug: "axis", name: "AXIS", category: "mobile-telco", aliases: [], tags: []),
        LogoMeta(slug: "ayo-ke-bank", name: "AYO ke Bank", category: "regulatory", aliases: [], tags: []),
        LogoMeta(slug: "bangkok-bank", name: "Bangkok Bank", category: "bank-logo", aliases: [], tags: []),
        LogoMeta(slug: "bank-artha-graha-internasional", name: "Bank Artha Graha Internasional", category: "bank-logo", aliases: ["artgidja", "037", "bag-internasional"], tags: []),
        LogoMeta(slug: "bank-bengkulu", name: "Bank Bengkulu", category: "bank-logo", aliases: ["133", "pdbkidj1", "bpd-bengkulu"], tags: []),
        LogoMeta(slug: "bank-bjb", name: "Bank BJB", category: "bank-logo", aliases: ["110", "bank-jabar-banten", "pdjbidja", "bank-pembangunan-daerah-jabar-dan-banten"], tags: []),
        LogoMeta(slug: "bank-bjb-syariah", name: "Bank BJB Syariah", category: "bank-logo", aliases: ["425", "syjbidj1", "bank-jabar-syariah", "bank-jabar-banten-syariah"], tags: []),
        LogoMeta(slug: "bank-bpd-aceh", name: "Bank BPD Aceh", category: "bank-logo", aliases: ["116", "bank-aceh", "syacidj1", "bank-aceh-syariah"], tags: []),
        LogoMeta(slug: "bank-bpd-bali", name: "Bank BPD Bali", category: "bank-logo", aliases: ["129", "bank-bali", "abalidbs", "bpd-bali", "bank-pembangunan-daerah-bali"], tags: []),
        LogoMeta(slug: "bank-bpd-banten", name: "Bank BPD Banten", category: "bank-logo", aliases: ["137", "bank-banten", "pdbbidj1", "bpd-banten", "bank-pembangunan-daerah-banten"], tags: []),
        LogoMeta(slug: "bank-bpd-diy", name: "Bank BPD DIY", category: "bank-logo", aliases: ["112", "bpd-diy", "pdykidj1", "bank-pembangunan-daerah-diy"], tags: []),
        LogoMeta(slug: "bank-bpd-jambi", name: "Bank BPD Jambi", category: "bank-logo", aliases: ["115", "bank-jambi", "pdjmidj1", "bpd-jambi", "bank-pembangunan-daerah-jambi"], tags: []),
        LogoMeta(slug: "bank-bpd-jateng", name: "Bank BPD Jateng", category: "bank-logo", aliases: ["113", "bank-jateng", "pdjgidj1", "bank-pembangunan-daerah-jawa-tengah"], tags: []),
        LogoMeta(slug: "bank-bpd-jatim", name: "Bank BPD Jatim", category: "bank-logo", aliases: ["114", "bank-jatim", "pdjtidj1", "bank-pembangunan-daerah-jatim"], tags: []),
        LogoMeta(slug: "bank-bpd-kalbar", name: "Bank BPD Kalbar", category: "bank-logo", aliases: ["123", "bank-kalbar", "pdkbidj1", "bpd-kalbar", "bank-pembangunan-daerah-kalbar"], tags: []),
        LogoMeta(slug: "bank-bpd-kalbar-alt", name: "Bank BPD Kalbar (Alt)", category: "bank-logo", aliases: [], tags: []),
        LogoMeta(slug: "bank-bpd-kalimantan-timur", name: "Bank BPD Kalimantan Timur", category: "bank-logo", aliases: ["124", "bank-kaltim", "pdktidj1", "bpd-kaltimtara", "bank-pembangunan-daerah-kaltim-dan-kaltara"], tags: []),
        LogoMeta(slug: "bank-bpd-kalsel", name: "Bank BPD Kalsel", category: "bank-logo", aliases: ["122", "bank-kalsel", "pdksidj1", "bpd-kalsel", "bank-pembangunan-daerah-kalsel"], tags: []),
        LogoMeta(slug: "bank-bpd-kalteng", name: "Bank BPD Kalteng", category: "bank-logo", aliases: ["125", "bank-kalteng", "pdkgidj1", "bpd-kalteng", "bpd-kalimantan-tengah"], tags: []),
        LogoMeta(slug: "bank-bpd-lampung", name: "Bank BPD Lampung", category: "bank-logo", aliases: ["121", "pdlpidj1", "bank-pembangunan-daerah-lampung"], tags: []),
        LogoMeta(slug: "bank-bpd-maluku-malut", name: "Bank BPD Maluku Malut", category: "bank-logo", aliases: ["131", "bank-maluku", "pdmlidj1", "bank-maluku-malut", "bank-pembangunan-daerah-maluku-dan-maluku-utara"], tags: []),
        LogoMeta(slug: "bank-bpd-ntb-syariah", name: "Bank BPD NTB Syariah", category: "bank-logo", aliases: ["128", "bank-ntb", "pdnbidj1", "bank-ntb-syariah", "bank-pembangunan-daerah-nusa-tenggara-barat-syariah"], tags: []),
        LogoMeta(slug: "bank-bpd-ntb-syariah-alt", name: "Bank BPD NTB Syariah (Alt)", category: "bank-logo", aliases: [], tags: []),
        LogoMeta(slug: "bank-bpd-ntt", name: "Bank BPD NTT", category: "bank-logo", aliases: ["130", "bank-ntt", "pdntidja", "bpd-ntt", "bank-pembangunan-daerah-ntt"], tags: []),
        LogoMeta(slug: "bank-bpd-papua", name: "Bank BPD Papua", category: "bank-logo", aliases: ["132", "bank-papua", "pdijidj1", "bpd-papua", "bank-pembangunan-daerah-papua"], tags: []),
        LogoMeta(slug: "bank-bpd-riau-kepri", name: "Bank BPD Riau Kepri", category: "bank-logo", aliases: ["119", "bank-riau-kepri", "pdriidja", "bank-riau-kepri-syariah", "bank-pembangunan-daerah-riau-kepri-syariah"], tags: []),
        LogoMeta(slug: "bank-bpd-riau-kepri-syariah", name: "Bank BPD Riau Kepri Syariah", category: "bank-logo", aliases: [], tags: []),
        LogoMeta(slug: "bank-bpd-sulselbar", name: "Bank BPD Sulselbar", category: "bank-logo", aliases: ["126", "bank-sulselbar", "pdwsidja"], tags: []),
        LogoMeta(slug: "bank-bpd-sulteng", name: "Bank BPD Sulteng", category: "bank-logo", aliases: ["134", "bank-sulteng", "pdwgidj1", "bpd-sulteng", "bpd-sulawesi-tengah"], tags: []),
        LogoMeta(slug: "bank-bpd-sultra", name: "Bank BPD Sultra", category: "bank-logo", aliases: ["135", "bank-sultra", "pdwridj1", "bpd-sultra", "bpd-sulawesi-tenggara"], tags: []),
        LogoMeta(slug: "bank-bpd-sulutgo", name: "Bank BPD Sulutgo", category: "bank-logo", aliases: ["127", "bank-sulutgo", "pdwuidj1", "bpd-sulut", "bpd-sulut-gorontalo"], tags: []),
        LogoMeta(slug: "bank-bpd-sumsel-babel", name: "Bank BPD Sumsel Babel", category: "bank-logo", aliases: ["120", "bank-sumsel-babel", "bsspidsp", "bpd-sumsel-babel", "bpd-sumsel-dan-babel"], tags: []),
        LogoMeta(slug: "bank-bpd-sumsel-babel-alt", name: "Bank BPD Sumsel Babel (Alt)", category: "bank-logo", aliases: ["bank-bpd-sumsel-babel-alt-1"], tags: []),
        LogoMeta(slug: "bank-bpd-sumsel-babel-alt-2", name: "Bank BPD Sumsel Babel (Alt-2)", category: "bank-logo", aliases: [], tags: []),
        LogoMeta(slug: "bank-bpd-sumut", name: "Bank BPD Sumut", category: "bank-logo", aliases: ["117", "bank-sumut", "pdsuidj1", "bank-pembangunan-daerah-sumut"], tags: []),
        LogoMeta(slug: "bank-bumi-artha", name: "Bank Bumi Artha", category: "bank-logo", aliases: ["076", "bbaiidja", "bba", "bank-bumi-arta"], tags: []),
        LogoMeta(slug: "bank-capital", name: "Bank Capital", category: "bank-logo", aliases: ["054", "bciaidja", "bank-capital-indonesia"], tags: []),
        LogoMeta(slug: "bank-capital-alt", name: "Bank Capital (Alt)", category: "bank-logo", aliases: [], tags: []),
        LogoMeta(slug: "bank-dki-old", name: "Bank DKI (Old)", category: "bank-logo", aliases: [], tags: []),
        LogoMeta(slug: "bank-ganesha", name: "Bank Ganesha", category: "bank-logo", aliases: ["161", "gnesidja"], tags: []),
        LogoMeta(slug: "bank-ina", name: "Bank INA", category: "bank-logo", aliases: ["513", "iaptidja", "bank-ina-perdana"], tags: []),
        LogoMeta(slug: "bank-index-selindo", name: "Bank Index Selindo", category: "bank-logo", aliases: ["555", "bidxidja", "bank-index"], tags: []),
        LogoMeta(slug: "bank-index-selindo-alt", name: "Bank Index Selindo (Alt)", category: "bank-logo", aliases: [], tags: []),
        LogoMeta(slug: "bank-indonesia", name: "Bank Indonesia", category: "regulatory", aliases: ["bi"], tags: []),
        LogoMeta(slug: "bank-jakarta", name: "Bank Jakarta", category: "bank-logo", aliases: ["111", "bank-dki-jakarta", "bdkiidj1", "bank-dki-1", "bank-dki", "bank-dki-alt"], tags: []),
        LogoMeta(slug: "bank-jasa-jakarta", name: "Bank Jasa Jakarta", category: "bank-logo", aliases: [], tags: []),
        LogoMeta(slug: "bank-lampung", name: "Bank Lampung", category: "bank-logo", aliases: [], tags: []),
        LogoMeta(slug: "bank-mas", name: "Bank Mas", category: "bank-logo", aliases: ["bmseidja", "548", "bank-multiarta-sentosa"], tags: []),
        LogoMeta(slug: "bank-maspion", name: "Bank Maspion", category: "bank-logo", aliases: ["157", "masdidj1"], tags: []),
        LogoMeta(slug: "bank-maspion-alt", name: "Bank Maspion (Alt)", category: "bank-logo", aliases: [], tags: []),
        LogoMeta(slug: "bank-mayapada", name: "Bank Mayapada", category: "bank-logo", aliases: ["097", "mayaidja"], tags: []),
        LogoMeta(slug: "bank-mayapada-alt", name: "Bank Mayapada (Alt)", category: "bank-logo", aliases: [], tags: []),
        LogoMeta(slug: "bank-mayora", name: "Bank Mayora", category: "bank-logo", aliases: [], tags: []),
        LogoMeta(slug: "bank-mestika-dharma", name: "Bank Mestika Dharma", category: "bank-logo", aliases: ["151", "medhids1", "bank-mestika"], tags: []),
        LogoMeta(slug: "bank-nagari", name: "Bank Nagari", category: "bank-logo", aliases: ["118", "bank-sumbar", "pdsbidj1"], tags: []),
        LogoMeta(slug: "bank-of-america", name: "Bank of America", category: "bank-logo", aliases: ["033", "bofaid2x", "boa", "bank-of-america-na"], tags: []),
        LogoMeta(slug: "bank-of-china", name: "Bank of China", category: "bank-logo", aliases: ["bkchidja", "069", "boc-limited", "bank-of-china-hong-kong-limited"], tags: []),
        LogoMeta(slug: "bank-of-india", name: "Bank of India", category: "bank-logo", aliases: [], tags: []),
        LogoMeta(slug: "bank-of-india-indonesia", name: "Bank of India Indonesia", category: "bank-logo", aliases: ["146", "bkididja"], tags: []),
        LogoMeta(slug: "bank-raya", name: "Bank Raya", category: "bank-logo", aliases: ["494", "agtbidja", "bank-raya-indonesia"], tags: []),
        LogoMeta(slug: "bank-resona-perdania", name: "Bank Resona Perdania", category: "bank-logo", aliases: ["047", "bpiaidja", "bank-resona"], tags: []),
        LogoMeta(slug: "bank-resona-perdania-alt", name: "Bank Resona Perdania (Alt)", category: "bank-logo", aliases: [], tags: []),
        LogoMeta(slug: "bank-sahabat-sampoerna", name: "Bank Sahabat Sampoerna", category: "bank-logo", aliases: ["523", "sahmidja", "bank-sampoerna"], tags: []),
        LogoMeta(slug: "bank-saqu", name: "Bank Saqu", category: "bank-logo", aliases: ["jsabidj1", "472", "bank-saqu-indonesia"], tags: []),
        LogoMeta(slug: "bank-saqu-alt", name: "Bank Saqu (Alt)", category: "bank-logo", aliases: [], tags: []),
        LogoMeta(slug: "bank-smbc-indonesia", name: "Bank SMBC Indonesia", category: "bank-logo", aliases: ["suniidja", "213", "bank-smbc"], tags: []),
        LogoMeta(slug: "bank-victoria", name: "Bank Victoria", category: "bank-logo", aliases: ["victidj1", "566", "bank-victoria-international"], tags: []),
        LogoMeta(slug: "bank-victoria-syariah", name: "Bank Victoria Syariah", category: "bank-logo", aliases: [], tags: []),
        LogoMeta(slug: "bank-woori-saudara", name: "Bank Woori Saudara", category: "bank-logo", aliases: ["212", "bsdridja", "bank-woori-saudara-indonesia-1906"], tags: []),
        LogoMeta(slug: "bappebti", name: "BAPPEBTI", category: "regulatory", aliases: ["badan-pengawas-perdagangan-berjangka-komoditi"], tags: []),
        LogoMeta(slug: "baznas", name: "BAZNAS", category: "donation", aliases: ["badan-amil-zakat-nasional"], tags: []),
        LogoMeta(slug: "bca", name: "BCA", category: "bank-logo", aliases: ["bank-central-asia", "cenaidja", "014"], tags: []),
        LogoMeta(slug: "bca-atm", name: "BCA ATM", category: "switching", aliases: [], tags: []),
        LogoMeta(slug: "bca-debit", name: "BCA Debit", category: "switching", aliases: [], tags: []),
        LogoMeta(slug: "bca-digital", name: "BCA Digital", category: "bank-logo", aliases: ["bbluidja", "501", "bank-digital-bca"], tags: []),
        LogoMeta(slug: "bca-finance", name: "BCA Finance", category: "financing", aliases: [], tags: []),
        LogoMeta(slug: "bca-flazz", name: "BCA Flazz", category: "prepaid-card", aliases: ["bca-flazz-new", "flazz"], tags: []),
        LogoMeta(slug: "bca-flazz-alt", name: "BCA Flazz (Alt)", category: "prepaid-card", aliases: [], tags: []),
        LogoMeta(slug: "bca-flazz-old", name: "BCA Flazz (Old)", category: "prepaid-card", aliases: [], tags: []),
        LogoMeta(slug: "bca-klikpay", name: "BCA KlikPay", category: "direct-debit", aliases: ["klikpay"], tags: []),
        LogoMeta(slug: "bca-life", name: "BCA Life", category: "insurance", aliases: [], tags: []),
        LogoMeta(slug: "bca-mobile", name: "BCA Mobile", category: "bank-app", aliases: ["m-bca"], tags: []),
        LogoMeta(slug: "bca-syariah", name: "BCA Syariah", category: "bank-logo", aliases: ["536", "bsyaidja", "bank-bca-syariah"], tags: []),
        LogoMeta(slug: "bea-cukai", name: "Bea Cukai", category: "government", aliases: ["djbc"], tags: []),
        LogoMeta(slug: "bfi-finance", name: "BFI Finance", category: "financing", aliases: [], tags: []),
        LogoMeta(slug: "bhinneka", name: "Bhinneka", category: "e-commerce", aliases: [], tags: []),
        LogoMeta(slug: "bi-fast", name: "BI-FAST", category: "switching", aliases: ["bifast"], tags: []),
        LogoMeta(slug: "biznet", name: "Biznet", category: "isp", aliases: [], tags: []),
        LogoMeta(slug: "biznet-home", name: "Biznet Home", category: "isp", aliases: [], tags: []),
        LogoMeta(slug: "blibli", name: "Blibli", category: "e-commerce", aliases: [], tags: []),
        LogoMeta(slug: "blu-bca", name: "blu by BCA Digital", category: "bank-logo", aliases: [], tags: []),
        LogoMeta(slug: "bluepay", name: "Bluepay", category: "e-wallet", aliases: [], tags: []),
        LogoMeta(slug: "bnc", name: "BNC", category: "bank-logo", aliases: ["490", "yudbidj1", "bank-neo-commerce"], tags: []),
        LogoMeta(slug: "bni", name: "BNI", category: "bank-logo", aliases: ["bank-negara-indonesia", "bninidja", "009", "bank-bni"], tags: []),
        LogoMeta(slug: "bni-mobile-banking", name: "BNI Mobile Banking", category: "bank-app", aliases: ["bni-mobile"], tags: []),
        LogoMeta(slug: "bni-tapcash", name: "BNI TapCash", category: "prepaid-card", aliases: ["tapcash"], tags: []),
        LogoMeta(slug: "bnp-paribas", name: "BNP Paribas", category: "bank-logo", aliases: ["057", "bnpaidja", "bank-bnp-paribas-indonesia"], tags: []),
        LogoMeta(slug: "bpd", name: "BPD", category: "regulatory", aliases: ["bank-pembangunan-daerah"], tags: []),
        LogoMeta(slug: "bpjs", name: "BPJS", category: "insurance", aliases: ["bpjs-kesehatan"], tags: []),
        LogoMeta(slug: "bpjs-alt", name: "BPJS (Alt)", category: "insurance", aliases: [], tags: []),
        LogoMeta(slug: "bpjs-ketenagakerjaan", name: "BPJS Ketenagakerjaan", category: "insurance", aliases: ["bpjamsostek", "bpjs-tk"], tags: []),
        LogoMeta(slug: "bri", name: "BRI", category: "bank-logo", aliases: ["bri-new", "bank-rakyat-indonesia", "brinidja", "002"], tags: []),
        LogoMeta(slug: "bri-alt", name: "BRI (Alt)", category: "bank-logo", aliases: [], tags: []),
        LogoMeta(slug: "bri-brizzi", name: "BRI BRIZZI", category: "prepaid-card", aliases: ["brizzi"], tags: []),
        LogoMeta(slug: "bri-brizzi-alt", name: "BRI BRIZZI (Alt)", category: "prepaid-card", aliases: [], tags: []),
        LogoMeta(slug: "bri-direct-debit", name: "BRI Direct Debit", category: "direct-debit", aliases: [], tags: []),
        LogoMeta(slug: "bri-finance", name: "BRI Finance", category: "financing", aliases: [], tags: []),
        LogoMeta(slug: "bri-insurance", name: "BRI Insurance", category: "insurance", aliases: [], tags: []),
        LogoMeta(slug: "bri-life", name: "BRI Life", category: "insurance", aliases: [], tags: []),
        LogoMeta(slug: "bri-old", name: "BRI (Old)", category: "bank-logo", aliases: [], tags: []),
        LogoMeta(slug: "bri-vertical", name: "BRI (Vertical)", category: "bank-logo", aliases: [], tags: []),
        LogoMeta(slug: "bright", name: "Bright", category: "supermarket", aliases: [], tags: []),
        LogoMeta(slug: "brimo", name: "BRImo", category: "bank-app", aliases: ["bri-mobile"], tags: []),
        LogoMeta(slug: "brins", name: "BRINS", category: "insurance", aliases: [], tags: []),
        LogoMeta(slug: "bsi", name: "BSI", category: "bank-logo", aliases: ["bank-syariah-indonesia", "bsmdidja", "451"], tags: []),
        LogoMeta(slug: "bsi-mobile", name: "BSI Mobile", category: "bank-app", aliases: [], tags: []),
        LogoMeta(slug: "bsn", name: "BSN", category: "bank-logo", aliases: ["swagidj1", "405", "bank-syariah-nasional"], tags: []),
        LogoMeta(slug: "bsn-alt", name: "BSN (Alt)", category: "bank-logo", aliases: [], tags: []),
        LogoMeta(slug: "btn", name: "BTN", category: "bank-logo", aliases: ["btn-new", "bank-tabungan-negara", "btanidja", "200"], tags: []),
        LogoMeta(slug: "btn-alt", name: "BTN (Alt)", category: "bank-logo", aliases: [], tags: []),
        LogoMeta(slug: "btn-old", name: "BTN (Old)", category: "bank-logo", aliases: [], tags: []),
        LogoMeta(slug: "btn-syariah", name: "BTN Syariah", category: "bank-logo", aliases: ["btn-syariah-new"], tags: []),
        LogoMeta(slug: "btn-syariah-old", name: "BTN Syariah (Old)", category: "bank-logo", aliases: [], tags: []),
        LogoMeta(slug: "btpn", name: "BTPN", category: "bank-logo", aliases: ["bank-tabungan-pensiunan-nasional"], tags: []),
        LogoMeta(slug: "btpn-syariah", name: "BTPN Syariah", category: "bank-logo", aliases: ["547", "pubaidj1", "bank-btpn-syariah"], tags: []),
        LogoMeta(slug: "bukalapak", name: "Bukalapak", category: "e-commerce", aliases: ["bukalapak-new"], tags: []),
        LogoMeta(slug: "bukalapak-alt", name: "Bukalapak (Alt)", category: "e-commerce", aliases: [], tags: []),
        LogoMeta(slug: "bukalapak-old", name: "Bukalapak (Old)", category: "e-commerce", aliases: [], tags: []),
        LogoMeta(slug: "bumiputera", name: "Bumiputera", category: "insurance", aliases: [], tags: []),
        LogoMeta(slug: "bussan-auto-finance", name: "Bussan Auto Finance", category: "financing", aliases: [], tags: []),
        LogoMeta(slug: "by-u", name: "by.U", category: "mobile-telco", aliases: ["byu"], tags: []),
        LogoMeta(slug: "byond-bsi", name: "BYOND by BSI", category: "bank-app", aliases: ["byond"], tags: []),
        LogoMeta(slug: "byond-bsi-alt", name: "BYOND by BSI (Alt)", category: "bank-app", aliases: [], tags: []),
        LogoMeta(slug: "catchplay", name: "Catchplay", category: "entertainment", aliases: [], tags: []),
        LogoMeta(slug: "cbn", name: "CBN", category: "isp", aliases: [], tags: []),
        LogoMeta(slug: "ccb-indonesia", name: "CCB Indonesia", category: "bank-logo", aliases: ["036", "mcoridja", "china-construction-bank", "bank-china-construction-bank-indonesia"], tags: []),
        LogoMeta(slug: "ccb-indonesia-alt", name: "CCB Indonesia (Alt)", category: "bank-logo", aliases: [], tags: []),
        LogoMeta(slug: "cgv", name: "CGV", category: "entertainment", aliases: [], tags: []),
        LogoMeta(slug: "chubb", name: "CHUBB", category: "insurance", aliases: [], tags: []),
        LogoMeta(slug: "cimb-niaga", name: "CIMB Niaga", category: "bank-logo", aliases: ["bank-cimb-niaga", "bniaidja", "022", "bank-cimb"], tags: []),
        LogoMeta(slug: "cimb-niaga-syariah", name: "CIMB Niaga Syariah", category: "bank-logo", aliases: ["synaidj1", "bank-cimb-niaga-uus", "bank-cimb-niaga-unit-usaha-syariah"], tags: []),
        LogoMeta(slug: "cinepolis", name: "Cinepolis", category: "entertainment", aliases: [], tags: []),
        LogoMeta(slug: "circle-k", name: "Circle K", category: "supermarket", aliases: ["circlek"], tags: []),
        LogoMeta(slug: "circle-k-alt", name: "Circle K (Alt)", category: "supermarket", aliases: [], tags: []),
        LogoMeta(slug: "cirrus", name: "Cirrus", category: "card-payment", aliases: [], tags: []),
        LogoMeta(slug: "citibank", name: "Citibank", category: "bank-logo", aliases: ["citiidjx", "031", "citibank-na"], tags: []),
        LogoMeta(slug: "citibank-alt", name: "Citibank (Alt)", category: "bank-logo", aliases: [], tags: []),
        LogoMeta(slug: "cititrans", name: "Cititrans", category: "transportation", aliases: [], tags: []),
        LogoMeta(slug: "commonwealth", name: "Commonwealth", category: "bank-logo", aliases: [], tags: []),
        LogoMeta(slug: "commonwealth-life", name: "Commonwealth Life", category: "insurance", aliases: [], tags: []),
        LogoMeta(slug: "contactless", name: "Contactless", category: "card-payment", aliases: [], tags: []),
        LogoMeta(slug: "contactless-alt", name: "Contactless (Alt)", category: "card-payment", aliases: [], tags: []),
        LogoMeta(slug: "credit-suisse", name: "Credit Suisse", category: "bank-logo", aliases: [], tags: []),
        LogoMeta(slug: "ctbc-bank", name: "CTBC Bank", category: "bank-logo", aliases: ["ctcbidja", "949", "ctbc-indonesia", "bank-ctbc-indonesia"], tags: []),
        LogoMeta(slug: "daihatsu-financial-service", name: "Daihatsu Financial Service", category: "financing", aliases: [], tags: []),
        LogoMeta(slug: "dakota-cargo", name: "Dakota Cargo", category: "logistic", aliases: [], tags: []),
        LogoMeta(slug: "dakota-logistik", name: "Dakota Logistik", category: "logistic", aliases: [], tags: []),
        LogoMeta(slug: "damri", name: "DAMRI", category: "transportation", aliases: [], tags: []),
        LogoMeta(slug: "dan-plus-dan", name: "Dan+Dan", category: "supermarket", aliases: [], tags: []),
        LogoMeta(slug: "dana", name: "DANA", category: "e-wallet", aliases: [], tags: []),
        LogoMeta(slug: "danamon", name: "Danamon", category: "bank-logo", aliases: ["bank-danamon", "bdinidja", "011", "bank-danamon-indonesia"], tags: []),
        LogoMeta(slug: "danamon-mufg", name: "Danamon (MUFG)", category: "bank-logo", aliases: [], tags: []),
        LogoMeta(slug: "danamon-syariah", name: "Danamon Syariah", category: "bank-logo", aliases: ["sybdidj1", "bank-danamon-uus", "bank-danamon-indonesia-unit-usaha-syariah"], tags: []),
        LogoMeta(slug: "daytrans", name: "DayTrans", category: "transportation", aliases: [], tags: []),
        LogoMeta(slug: "dbs", name: "DBS", category: "bank-logo", aliases: ["dbsbidja", "046", "bank-dbs-indonesia"], tags: []),
        LogoMeta(slug: "dbs-paylah", name: "DBS Paylah", category: "miscellaneous", aliases: ["paylah"], tags: []),
        LogoMeta(slug: "deutsche-bank", name: "Deutsche Bank", category: "bank-logo", aliases: ["deutidja", "067", "deutsche-bank-ag"], tags: []),
        LogoMeta(slug: "dhl-express", name: "DHL Express", category: "logistic", aliases: ["dhl"], tags: []),
        LogoMeta(slug: "digibank", name: "Digibank", category: "bank-app", aliases: ["dbs-digibank"], tags: []),
        LogoMeta(slug: "digibank-alt", name: "Digibank (Alt)", category: "bank-app", aliases: [], tags: []),
        LogoMeta(slug: "dipay", name: "Dipay", category: "e-wallet", aliases: [], tags: []),
        LogoMeta(slug: "discover", name: "Discover", category: "card-payment", aliases: [], tags: []),
        LogoMeta(slug: "discover-alt", name: "Discover (Alt)", category: "card-payment", aliases: [], tags: []),
        LogoMeta(slug: "disney-plus", name: "Disney+", category: "entertainment", aliases: ["disneyplus"], tags: []),
        LogoMeta(slug: "disney-plus-hotstar", name: "Disney+ Hotstar", category: "entertainment", aliases: ["hotstar"], tags: []),
        LogoMeta(slug: "djp-online", name: "DJP Online", category: "government", aliases: ["djp"], tags: []),
        LogoMeta(slug: "djp-online-alt", name: "DJP Online (Alt)", category: "government", aliases: [], tags: []),
        LogoMeta(slug: "doku", name: "DOKU", category: "e-wallet", aliases: [], tags: []),
        LogoMeta(slug: "dompet-dhuafa", name: "Dompet Dhuafa", category: "donation", aliases: [], tags: []),
        LogoMeta(slug: "dompet-dhuafa-alt", name: "Dompet Dhuafa (Alt)", category: "donation", aliases: [], tags: []),
        LogoMeta(slug: "duitnow", name: "DuitNow", category: "qr-payment", aliases: [], tags: []),
        LogoMeta(slug: "duitnow-qr", name: "DuitNow QR", category: "qr-payment", aliases: [], tags: []),
        LogoMeta(slug: "dutamoney", name: "Dutamoney", category: "e-wallet", aliases: [], tags: []),
        LogoMeta(slug: "e-toll-card", name: "e-Toll Card", category: "prepaid-card", aliases: ["etoll", "e-toll"], tags: []),
        LogoMeta(slug: "ea-play", name: "EA Play", category: "game", aliases: [], tags: []),
        LogoMeta(slug: "ea-play-alt", name: "EA Play (Alt)", category: "game", aliases: [], tags: []),
        LogoMeta(slug: "ekonomi-syariah", name: "Ekonomi Syariah", category: "regulatory", aliases: [], tags: []),
        LogoMeta(slug: "ekonomi-syariah-alt", name: "Ekonomi Syariah (Alt)", category: "regulatory", aliases: [], tags: []),
        LogoMeta(slug: "ems", name: "EMS", category: "logistic", aliases: [], tags: []),
        LogoMeta(slug: "epic-games", name: "Epic Games", category: "game", aliases: [], tags: []),
        LogoMeta(slug: "epic-games-store", name: "Epic Games Store", category: "game", aliases: ["epic-store"], tags: []),
        LogoMeta(slug: "esl-express", name: "ESL Express", category: "logistic", aliases: [], tags: []),
        LogoMeta(slug: "espay", name: "Espay", category: "payment-gateway", aliases: [], tags: []),
        LogoMeta(slug: "family-mart", name: "Family Mart", category: "supermarket", aliases: ["familymart"], tags: []),
        LogoMeta(slug: "fedex-express", name: "FedEx Express", category: "logistic", aliases: ["fedex"], tags: []),
        LogoMeta(slug: "fif-astra", name: "FIF Astra", category: "financing", aliases: ["fif"], tags: []),
        LogoMeta(slug: "finmas", name: "Finmas", category: "financing", aliases: [], tags: []),
        LogoMeta(slug: "finpay", name: "Finpay", category: "payment-gateway", aliases: [], tags: []),
        LogoMeta(slug: "first-logistic", name: "First Logistic", category: "logistic", aliases: [], tags: []),
        LogoMeta(slug: "first-media", name: "First Media", category: "isp", aliases: [], tags: []),
        LogoMeta(slug: "flip", name: "Flip", category: "remittance", aliases: [], tags: []),
        LogoMeta(slug: "fwd", name: "FWD", category: "insurance", aliases: [], tags: []),
        LogoMeta(slug: "generali", name: "Generali", category: "insurance", aliases: [], tags: []),
        LogoMeta(slug: "giant", name: "Giant", category: "supermarket", aliases: [], tags: []),
        LogoMeta(slug: "google-pay", name: "Google Pay", category: "miscellaneous", aliases: ["gpay", "googlepay"], tags: []),
        LogoMeta(slug: "google-play", name: "Google Play", category: "game", aliases: ["play-store", "google-play-store"], tags: []),
        LogoMeta(slug: "google-play-alt", name: "Google Play (Alt)", category: "game", aliases: [], tags: []),
        LogoMeta(slug: "gopay", name: "GoPay", category: "e-wallet", aliases: ["go-pay"], tags: []),
        LogoMeta(slug: "gopay-alt", name: "GoPay (Alt)", category: "e-wallet", aliases: [], tags: []),
        LogoMeta(slug: "gopaylater", name: "GoPay Later", category: "financing", aliases: ["gopay-later"], tags: []),
        LogoMeta(slug: "gpn", name: "GPN", category: "card-payment", aliases: ["gerbang-pembayaran-nasional"], tags: []),
        LogoMeta(slug: "grab-pay", name: "Grab Pay", category: "miscellaneous", aliases: ["grabpay"], tags: []),
        LogoMeta(slug: "hbo-go", name: "HBO GO", category: "entertainment", aliases: ["hbogo"], tags: []),
        LogoMeta(slug: "hero", name: "Hero", category: "supermarket", aliases: [], tags: []),
        LogoMeta(slug: "hibank", name: "hibank", category: "bank-logo", aliases: ["hbniidja", "553", "bank-hibank-indonesia"], tags: []),
        LogoMeta(slug: "home-credit", name: "Home Credit", category: "financing", aliases: [], tags: []),
        LogoMeta(slug: "hoox", name: "HOOX", category: "entertainment", aliases: [], tags: []),
        LogoMeta(slug: "hsbc", name: "HSBC", category: "bank-logo", aliases: ["hsbcidja", "087", "bank-hsbc-indonesia"], tags: []),
        LogoMeta(slug: "hypermart", name: "Hypermart", category: "supermarket", aliases: [], tags: []),
        LogoMeta(slug: "i-saku", name: "i.saku", category: "e-wallet", aliases: ["isaku"], tags: []),
        LogoMeta(slug: "ibk-bank", name: "IBK Bank", category: "bank-logo", aliases: ["ibkoidja", "945", "bank-ibk", "bank-ibk-indonesia"], tags: []),
        LogoMeta(slug: "icbc", name: "ICBC", category: "bank-logo", aliases: ["164", "icbkidja", "bank-icbc", "bank-icbc-indonesia"], tags: []),
        LogoMeta(slug: "icbc-alt", name: "ICBC (Alt)", category: "bank-logo", aliases: [], tags: []),
        LogoMeta(slug: "iconnet", name: "Iconnet", category: "isp", aliases: [], tags: []),
        LogoMeta(slug: "id-express", name: "ID Express", category: "logistic", aliases: ["idexpress"], tags: []),
        LogoMeta(slug: "im3", name: "IM3", category: "mobile-telco", aliases: [], tags: []),
        LogoMeta(slug: "indah-cargo", name: "Indah Cargo", category: "logistic", aliases: [], tags: []),
        LogoMeta(slug: "indihome", name: "IndiHome", category: "isp", aliases: ["indihome-new", "indi-home"], tags: []),
        LogoMeta(slug: "indihome-old", name: "IndiHome (Old)", category: "isp", aliases: [], tags: []),
        LogoMeta(slug: "indodana", name: "Indodana", category: "financing", aliases: [], tags: []),
        LogoMeta(slug: "indogrosir", name: "Indogrosir", category: "supermarket", aliases: [], tags: []),
        LogoMeta(slug: "indomaret", name: "Indomaret", category: "supermarket", aliases: [], tags: []),
        LogoMeta(slug: "indosat-hifi", name: "Indosat Hifi", category: "isp", aliases: [], tags: []),
        LogoMeta(slug: "indosat-m2", name: "Indosat M2", category: "isp", aliases: [], tags: []),
        LogoMeta(slug: "ing-bank", name: "ING Bank", category: "bank-logo", aliases: [], tags: []),
        LogoMeta(slug: "inklusi-keuangan", name: "Inklusi Keuangan", category: "regulatory", aliases: [], tags: []),
        LogoMeta(slug: "interlink", name: "Interlink", category: "miscellaneous", aliases: [], tags: []),
        LogoMeta(slug: "ipay88", name: "ipay88", category: "payment-gateway", aliases: ["i-pay88"], tags: []),
        LogoMeta(slug: "j-and-t-cargo", name: "J&T Cargo", category: "logistic", aliases: ["jnt-cargo"], tags: []),
        LogoMeta(slug: "j-and-t-express", name: "J&T Express", category: "logistic", aliases: ["jnt", "jnt-express"], tags: []),
        LogoMeta(slug: "j-trust-bank", name: "J Trust Bank", category: "bank-logo", aliases: ["095", "cictidja", "bank-jtrust", "bank-jtrust-indonesia"], tags: []),
        LogoMeta(slug: "jago", name: "Jago", category: "bank-logo", aliases: ["jagbidja", "542", "bank-jago"], tags: []),
        LogoMeta(slug: "jago-app", name: "Jago", category: "bank-app", aliases: [], tags: []),
        LogoMeta(slug: "jakcard", name: "Jakcard", category: "prepaid-card", aliases: ["jak-card"], tags: []),
        LogoMeta(slug: "jaklingko", name: "JakLingko", category: "transportation", aliases: ["jak-lingko"], tags: []),
        LogoMeta(slug: "jakone-mobile", name: "JakOne Mobile", category: "bank-app", aliases: ["jakone"], tags: []),
        LogoMeta(slug: "jakone-pay", name: "JakOne Pay", category: "e-wallet", aliases: ["jakonepay"], tags: []),
        LogoMeta(slug: "jalin", name: "Jalin", category: "switching", aliases: [], tags: []),
        LogoMeta(slug: "jcb", name: "JCB", category: "card-payment", aliases: [], tags: []),
        LogoMeta(slug: "jenius", name: "Jenius", category: "bank-logo", aliases: [], tags: []),
        LogoMeta(slug: "jenius-app", name: "Jenius", category: "bank-app", aliases: [], tags: []),
        LogoMeta(slug: "jenius-pay", name: "Jenius Pay", category: "direct-debit", aliases: [], tags: []),
        LogoMeta(slug: "jne", name: "JNE", category: "logistic", aliases: ["jalur-nugraha-ekakurir"], tags: []),
        LogoMeta(slug: "jne-alt", name: "JNE (Alt)", category: "logistic", aliases: [], tags: []),
        LogoMeta(slug: "joox", name: "JOOX", category: "entertainment", aliases: [], tags: []),
        LogoMeta(slug: "jp-morgan-chase", name: "JP Morgan Chase", category: "bank-logo", aliases: ["032", "chasidjx", "jpmorgan-bank", "jpmorgan-chase-bank-na"], tags: []),
        LogoMeta(slug: "kai", name: "KAI", category: "transportation", aliases: ["kereta-api-indonesia"], tags: []),
        LogoMeta(slug: "kai-bandara", name: "KAI Bandara", category: "transportation", aliases: ["railink"], tags: []),
        LogoMeta(slug: "kai-commuter", name: "KAI Commuter", category: "transportation", aliases: ["kai-commuter-new", "krl", "commuterline"], tags: []),
        LogoMeta(slug: "kai-commuter-old", name: "KAI Commuter (Old)", category: "transportation", aliases: [], tags: []),
        LogoMeta(slug: "kai-logistik", name: "KAI Logistik", category: "logistic", aliases: [], tags: []),
        LogoMeta(slug: "kartu-as", name: "Kartu As", category: "mobile-telco", aliases: ["kartuas"], tags: []),
        LogoMeta(slug: "kartu-halo", name: "Kartu Halo", category: "mobile-telco", aliases: ["kartuhalo"], tags: []),
        LogoMeta(slug: "kaspro", name: "Kaspro", category: "e-wallet", aliases: [], tags: []),
        LogoMeta(slug: "kb-bukopin", name: "KB Bukopin", category: "bank-logo", aliases: ["bbukidja", "441", "kb-indonesia", "bank-kb-indonesia"], tags: []),
        LogoMeta(slug: "kb-bukopin-alt", name: "KB Bukopin (Alt)", category: "bank-logo", aliases: [], tags: []),
        LogoMeta(slug: "kb-bukopin-syariah", name: "KB Bukopin Syariah", category: "bank-logo", aliases: ["521", "sdobidj1", "kbbs", "bank-kb-bukopin-syariah"], tags: []),
        LogoMeta(slug: "keb-hana-bank", name: "KEB Hana Bank", category: "bank-logo", aliases: ["hnbnidja", "484", "bank-keb-hana", "bank-keb-hana-indonesia"], tags: []),
        LogoMeta(slug: "keb-hana-bank-alt", name: "KEB Hana Bank (Alt)", category: "bank-logo", aliases: [], tags: []),
        LogoMeta(slug: "kemenkeu", name: "Kemenkeu", category: "government", aliases: ["kementerian-keuangan"], tags: []),
        LogoMeta(slug: "khqr", name: "KHQR", category: "qr-payment", aliases: [], tags: []),
        LogoMeta(slug: "kitabisa", name: "Kitabisa", category: "donation", aliases: [], tags: []),
        LogoMeta(slug: "kitabisa-alt", name: "Kitabisa (Alt)", category: "donation", aliases: [], tags: []),
        LogoMeta(slug: "kominfo", name: "KOMINFO", category: "regulatory", aliases: ["komdigi", "kementerian-komunikasi-dan-informatika"], tags: []),
        LogoMeta(slug: "korlantas-polri", name: "Korlantas Polri", category: "government", aliases: ["korlantas"], tags: []),
        LogoMeta(slug: "kredit-pintar", name: "Kredit Pintar", category: "financing", aliases: [], tags: []),
        LogoMeta(slug: "kreditplus", name: "KreditPlus", category: "financing", aliases: [], tags: []),
        LogoMeta(slug: "kredivo", name: "Kredivo", category: "financing", aliases: [], tags: []),
        LogoMeta(slug: "krom", name: "Krom", category: "bank-logo", aliases: ["459", "bustidj1", "krom-bank-indonesia"], tags: []),
        LogoMeta(slug: "lalamove", name: "Lalamove", category: "logistic", aliases: [], tags: []),
        LogoMeta(slug: "langitmusik", name: "Langitmusik", category: "entertainment", aliases: [], tags: []),
        LogoMeta(slug: "lao-qr", name: "LAO QR", category: "qr-payment", aliases: [], tags: []),
        LogoMeta(slug: "lawson", name: "Lawson", category: "supermarket", aliases: [], tags: []),
        LogoMeta(slug: "lazada", name: "Lazada", category: "e-commerce", aliases: [], tags: []),
        LogoMeta(slug: "lazada-express", name: "Lazada Express", category: "logistic", aliases: [], tags: []),
        LogoMeta(slug: "lexus-financial-service", name: "Lexus Financial Service", category: "financing", aliases: [], tags: []),
        LogoMeta(slug: "lexus-financial-service-alt", name: "Lexus Financial Service (Alt)", category: "financing", aliases: ["lexus-financial-service-1"], tags: []),
        LogoMeta(slug: "line-bank", name: "LINE Bank", category: "bank-logo", aliases: [], tags: []),
        LogoMeta(slug: "line-bank-alt", name: "LINE Bank (Alt)", category: "bank-logo", aliases: [], tags: []),
        LogoMeta(slug: "line-pay", name: "LINE Pay", category: "miscellaneous", aliases: ["linepay"], tags: []),
        LogoMeta(slug: "line-pay-alt", name: "LINE Pay (Alt)", category: "miscellaneous", aliases: [], tags: []),
        LogoMeta(slug: "link", name: "Link", category: "switching", aliases: ["link-new"], tags: []),
        LogoMeta(slug: "link-alt", name: "Link (Alt)", category: "switching", aliases: ["link-new-alt"], tags: []),
        LogoMeta(slug: "link-old", name: "Link (Old)", category: "switching", aliases: [], tags: []),
        LogoMeta(slug: "linkaja", name: "LinkAja", category: "e-wallet", aliases: ["link-aja"], tags: []),
        LogoMeta(slug: "lion-parcel", name: "Lion Parcel", category: "logistic", aliases: ["lionparcel"], tags: []),
        LogoMeta(slug: "live-on", name: "Live.On", category: "mobile-telco", aliases: [], tags: []),
        LogoMeta(slug: "lotte", name: "Lotte", category: "supermarket", aliases: [], tags: []),
        LogoMeta(slug: "lotte-grosir", name: "Lotte Grosir", category: "supermarket", aliases: [], tags: []),
        LogoMeta(slug: "lotte-mart", name: "Lotte Mart", category: "supermarket", aliases: ["lottemart"], tags: []),
        LogoMeta(slug: "lps", name: "LPS", category: "regulatory", aliases: ["lembaga-penjamin-simpanan"], tags: []),
        LogoMeta(slug: "lrt-jakarta", name: "LRT Jakarta", category: "transportation", aliases: ["lrt"], tags: []),
        LogoMeta(slug: "maestro", name: "Maestro", category: "card-payment", aliases: [], tags: []),
        LogoMeta(slug: "mandiri", name: "Mandiri", category: "bank-logo", aliases: ["bank-mandiri", "bmriidja", "008"], tags: []),
        LogoMeta(slug: "mandiri-e-cash", name: "Mandiri E-Cash", category: "direct-debit", aliases: ["mandiri-ecash"], tags: []),
        LogoMeta(slug: "mandiri-e-money", name: "Mandiri e-money", category: "prepaid-card", aliases: ["mandiri-emoney", "emoney"], tags: []),
        LogoMeta(slug: "mandiri-inhealth", name: "Mandiri Inhealth", category: "insurance", aliases: [], tags: []),
        LogoMeta(slug: "mandiri-livin", name: "Livin' by Mandiri", category: "bank-app", aliases: ["mandiri-livin-new", "livin", "livin-by-mandiri"], tags: []),
        LogoMeta(slug: "mandiri-livin-old", name: "Livin' by Mandiri (Old)", category: "bank-app", aliases: [], tags: []),
        LogoMeta(slug: "mandiri-taspen", name: "Mandiri Taspen", category: "bank-logo", aliases: ["sihbidj1", "564", "bank-mandiri-taspen"], tags: []),
        LogoMeta(slug: "manulife", name: "Manulife", category: "insurance", aliases: [], tags: []),
        LogoMeta(slug: "manulife-alt", name: "Manulife (Alt)", category: "insurance", aliases: [], tags: []),
        LogoMeta(slug: "mastercard", name: "Mastercard", category: "card-payment", aliases: [], tags: []),
        LogoMeta(slug: "mastercard-black", name: "Mastercard Black", category: "card-payment", aliases: [], tags: []),
        LogoMeta(slug: "mastercard-contactless", name: "Mastercard Contactless", category: "card-payment", aliases: [], tags: []),
        LogoMeta(slug: "mastercard-contactless-alt", name: "Mastercard Contactless (Alt)", category: "card-payment", aliases: [], tags: []),
        LogoMeta(slug: "mastercard-debit", name: "Mastercard Debit", category: "card-payment", aliases: [], tags: []),
        LogoMeta(slug: "mastercard-debit-alt", name: "Mastercard Debit (Alt)", category: "card-payment", aliases: [], tags: []),
        LogoMeta(slug: "mastercard-securecode", name: "Mastercard SecureCode", category: "card-payment", aliases: ["mastercard-securecode-new", "securecode"], tags: []),
        LogoMeta(slug: "mastercard-securecode-old", name: "Mastercard SecureCode (Old)", category: "card-payment", aliases: [], tags: []),
        LogoMeta(slug: "masterpass", name: "Masterpass", category: "card-payment", aliases: [], tags: []),
        LogoMeta(slug: "masterpass-alt", name: "Masterpass (Alt)", category: "card-payment", aliases: [], tags: []),
        LogoMeta(slug: "maxstream", name: "Maxstream", category: "entertainment", aliases: [], tags: []),
        LogoMeta(slug: "maybank", name: "Maybank", category: "bank-logo", aliases: ["016", "ibbkidja", "bank-maybank", "bank-maybank-indonesia"], tags: []),
        LogoMeta(slug: "mega", name: "Mega", category: "bank-logo", aliases: ["bank-mega", "megaidja", "426"], tags: []),
        LogoMeta(slug: "mega-syariah", name: "Mega Syariah", category: "bank-logo", aliases: ["506", "butgidj1", "bank-mega-syariah"], tags: []),
        LogoMeta(slug: "melsa", name: "Melsa", category: "isp", aliases: [], tags: []),
        LogoMeta(slug: "mentari-ooredoo", name: "Mentari Ooredoo", category: "mobile-telco", aliases: ["mentari"], tags: []),
        LogoMeta(slug: "meps", name: "MEPS", category: "switching", aliases: [], tags: []),
        LogoMeta(slug: "midtrans", name: "Midtrans", category: "payment-gateway", aliases: [], tags: []),
        LogoMeta(slug: "mizuho-bank", name: "Mizuho Bank", category: "bank-logo", aliases: ["mhccidja", "048", "bank-mizuho", "bank-mizuho-indonesia"], tags: []),
        LogoMeta(slug: "mnc", name: "MNC", category: "bank-logo", aliases: [], tags: []),
        LogoMeta(slug: "mnc-bank", name: "MNC Bank", category: "bank-logo", aliases: ["485", "bumiidja", "bank-mnc-internasional"], tags: []),
        LogoMeta(slug: "mnc-vision", name: "MNC Vision", category: "entertainment", aliases: [], tags: []),
        LogoMeta(slug: "moneygram", name: "MoneyGram", category: "remittance", aliases: [], tags: []),
        LogoMeta(slug: "motion-banking", name: "Motion Banking", category: "bank-logo", aliases: [], tags: []),
        LogoMeta(slug: "motion-banking-alt", name: "Motion Banking (Alt)", category: "bank-logo", aliases: [], tags: []),
        LogoMeta(slug: "motion-pay", name: "Motion Pay", category: "e-wallet", aliases: ["motionpay"], tags: []),
        LogoMeta(slug: "mrt-jakarta", name: "MRT Jakarta", category: "transportation", aliases: ["mrt"], tags: []),
        LogoMeta(slug: "mtix", name: "m.tix", category: "entertainment", aliases: ["m-tix"], tags: []),
        LogoMeta(slug: "muamalat", name: "Bank Muamalat", category: "bank-logo", aliases: ["bank-muamalat", "mualamat", "muabidja", "147", "bank-muamalat-indonesia"], tags: []),
        LogoMeta(slug: "mufg", name: "MUFG", category: "bank-logo", aliases: ["042", "botkidjx", "mufg-bank-ltd"], tags: []),
        LogoMeta(slug: "mufg-alt", name: "MUFG (Alt)", category: "bank-logo", aliases: [], tags: []),
        LogoMeta(slug: "my-nintendo", name: "My Nintendo", category: "game", aliases: [], tags: []),
        LogoMeta(slug: "myrepublic", name: "MyRepublic", category: "isp", aliases: [], tags: []),
        LogoMeta(slug: "nanobank-syariah", name: "Nanobank Syariah", category: "bank-logo", aliases: ["nanoidj1", "253", "nano-bank", "bank-nano-syariah"], tags: []),
        LogoMeta(slug: "nanobank-syariah-alt", name: "Nanobank Syariah (Alt)", category: "bank-logo", aliases: [], tags: []),
        LogoMeta(slug: "ncs", name: "NCS", category: "logistic", aliases: [], tags: []),
        LogoMeta(slug: "neobank", name: "Neobank", category: "bank-app", aliases: [], tags: []),
        LogoMeta(slug: "netflix", name: "Netflix", category: "entertainment", aliases: [], tags: []),
        LogoMeta(slug: "netflix-alt", name: "Netflix (Alt)", category: "entertainment", aliases: [], tags: []),
        LogoMeta(slug: "nets", name: "NETS", category: "miscellaneous", aliases: [], tags: []),
        LogoMeta(slug: "netzme", name: "Netzme", category: "e-wallet", aliases: [], tags: []),
        LogoMeta(slug: "nex-parabola", name: "Nex Parabola", category: "entertainment", aliases: [], tags: []),
        LogoMeta(slug: "nickelodeon", name: "Nickelodeon", category: "entertainment", aliases: [], tags: []),
        LogoMeta(slug: "ninja-xpress", name: "Ninja Xpress", category: "logistic", aliases: ["ninja-express"], tags: []),
        LogoMeta(slug: "nintendo-online", name: "Nintendo Online", category: "game", aliases: [], tags: []),
        LogoMeta(slug: "nobu", name: "NOBU", category: "bank-logo", aliases: ["503", "lfibidj1", "bank-nationalnobu"], tags: []),
        LogoMeta(slug: "ocbc-nisp", name: "OCBC NISP", category: "bank-logo", aliases: ["nispidja", "028", "bank-ocbc-nisp"], tags: []),
        LogoMeta(slug: "ocbc-pay-anyone", name: "OCBC Pay Anyone", category: "miscellaneous", aliases: ["pay-anyone"], tags: []),
        LogoMeta(slug: "octo-clicks", name: "OCTO Clicks", category: "bank-app", aliases: ["octo"], tags: []),
        LogoMeta(slug: "ojk", name: "OJK", category: "regulatory", aliases: ["otoritas-jasa-keuangan"], tags: []),
        LogoMeta(slug: "ok-bank", name: "OK Bank", category: "bank-logo", aliases: ["lmanidj1", "526", "bank-oke", "bank-oke-indonesia"], tags: []),
        LogoMeta(slug: "oneklik", name: "OneKlik", category: "direct-debit", aliases: ["one-klik"], tags: []),
        LogoMeta(slug: "otto-pay", name: "OTTO Pay", category: "e-wallet", aliases: ["ottopay"], tags: []),
        LogoMeta(slug: "ovo", name: "OVO", category: "e-wallet", aliases: ["ovo-new"], tags: []),
        LogoMeta(slug: "ovo-alt", name: "OVO (Alt)", category: "e-wallet", aliases: ["ovo-new-alt"], tags: []),
        LogoMeta(slug: "ovo-old", name: "OVO (Old)", category: "e-wallet", aliases: [], tags: []),
        LogoMeta(slug: "ovo-old-alt", name: "OVO (Old Alt)", category: "e-wallet", aliases: [], tags: []),
        LogoMeta(slug: "oxygen-id", name: "Oxygen.id", category: "isp", aliases: [], tags: []),
        LogoMeta(slug: "oxygen-id-home", name: "Oxygen.id Home", category: "isp", aliases: [], tags: []),
        LogoMeta(slug: "pam-jaya", name: "PAM Jaya", category: "utilities", aliases: ["pam-jaya-new"], tags: []),
        LogoMeta(slug: "pam-jaya-old", name: "PAM Jaya (Old)", category: "utilities", aliases: [], tags: []),
        LogoMeta(slug: "pandu-logistics", name: "Pandu Logistics", category: "logistic", aliases: [], tags: []),
        LogoMeta(slug: "panin-dubai-syariah", name: "Panin Dubai Syariah", category: "bank-logo", aliases: ["517", "arfaidj1", "bank-panin-dubai-syariah"], tags: []),
        LogoMeta(slug: "paninbank", name: "PaninBank", category: "bank-logo", aliases: ["pinbidja", "019", "panin-bank"], tags: []),
        LogoMeta(slug: "paydia", name: "Paydia", category: "e-wallet", aliases: [], tags: []),
        LogoMeta(slug: "payoneer", name: "Payoneer", category: "remittance", aliases: [], tags: []),
        LogoMeta(slug: "paypal", name: "PayPal", category: "remittance", aliases: ["paypal-new"], tags: []),
        LogoMeta(slug: "paypal-old", name: "PayPal (Old)", category: "remittance", aliases: [], tags: []),
        LogoMeta(slug: "paytren", name: "Paytren", category: "e-wallet", aliases: [], tags: []),
        LogoMeta(slug: "pcp-express", name: "PCP Express", category: "logistic", aliases: [], tags: []),
        LogoMeta(slug: "pdam", name: "PDAM", category: "utilities", aliases: ["perusahaan-daerah-air-minum"], tags: []),
        LogoMeta(slug: "pdam-kota-surabaya", name: "PDAM Kota Surabaya", category: "utilities", aliases: [], tags: []),
        LogoMeta(slug: "pegadaian", name: "Pegadaian", category: "financing", aliases: [], tags: []),
        LogoMeta(slug: "perbankan-syariah-ib", name: "Perbankan Syariah (IB)", category: "regulatory", aliases: [], tags: []),
        LogoMeta(slug: "permata", name: "Permata Bank", category: "bank-logo", aliases: ["permata-bank-new", "bank-permata", "bbbaidja", "013"], tags: []),
        LogoMeta(slug: "permata-alt", name: "Permata Bank (Alt)", category: "bank-logo", aliases: ["permata-bank-alt"], tags: []),
        LogoMeta(slug: "permata-old", name: "Permata Bank (Old)", category: "bank-logo", aliases: [], tags: []),
        LogoMeta(slug: "pgn", name: "PGN", category: "utilities", aliases: ["perusahaan-gas-negara"], tags: []),
        LogoMeta(slug: "playstation-plus", name: "PlayStation Plus", category: "game", aliases: ["ps-plus"], tags: []),
        LogoMeta(slug: "playstation-store", name: "PlayStation Store", category: "game", aliases: ["ps-store"], tags: []),
        LogoMeta(slug: "pln", name: "PLN", category: "utilities", aliases: ["perusahaan-listrik-negara"], tags: []),
        LogoMeta(slug: "pos-indonesia", name: "Pos Indonesia", category: "logistic", aliases: ["pos-indonesia-new", "posindo"], tags: []),
        LogoMeta(slug: "pos-indonesia-old", name: "Pos Indonesia (Old)", category: "logistic", aliases: [], tags: []),
        LogoMeta(slug: "pospay", name: "Pospay", category: "e-wallet", aliases: ["pos-pay"], tags: []),
        LogoMeta(slug: "prima", name: "PRIMA", category: "switching", aliases: [], tags: []),
        LogoMeta(slug: "prima-bank", name: "PRIMA Bank", category: "bank-logo", aliases: [], tags: []),
        LogoMeta(slug: "prima-debit", name: "PRIMA Debit", category: "switching", aliases: [], tags: []),
        LogoMeta(slug: "prime-video", name: "Prime Video", category: "entertainment", aliases: ["amazon-prime-video"], tags: []),
        LogoMeta(slug: "prismalink", name: "PrismaLink", category: "payment-gateway", aliases: ["prisma-link"], tags: []),
        LogoMeta(slug: "prudential", name: "Prudential", category: "insurance", aliases: [], tags: []),
        LogoMeta(slug: "qnb", name: "QNB", category: "bank-logo", aliases: ["167", "awanidja", "bank-qnb", "bank-qnb-indonesia"], tags: []),
        LogoMeta(slug: "qoala", name: "Qoala", category: "insurance", aliases: [], tags: []),
        LogoMeta(slug: "qr-ph", name: "QR Ph", category: "qr-payment", aliases: [], tags: []),
        LogoMeta(slug: "qris", name: "QRIS", category: "qr-payment", aliases: ["quick-response-code-indonesian-standard"], tags: []),
        LogoMeta(slug: "rex", name: "REX", category: "logistic", aliases: [], tags: []),
        LogoMeta(slug: "ria-money", name: "Ria Money", category: "remittance", aliases: [], tags: []),
        LogoMeta(slug: "rpx", name: "RPX", category: "logistic", aliases: [], tags: []),
        LogoMeta(slug: "rumah-zakat", name: "Rumah Zakat", category: "donation", aliases: [], tags: []),
        LogoMeta(slug: "rumah-zakat-alt", name: "Rumah Zakat (Alt)", category: "donation", aliases: [], tags: []),
        LogoMeta(slug: "samsung-card", name: "Samsung Card", category: "card-payment", aliases: [], tags: []),
        LogoMeta(slug: "samsung-pay", name: "Samsung Pay", category: "miscellaneous", aliases: ["samsungpay"], tags: []),
        LogoMeta(slug: "samsung-pay-alt", name: "Samsung Pay (Alt)", category: "miscellaneous", aliases: [], tags: []),
        LogoMeta(slug: "sap-express", name: "SAP Express", category: "logistic", aliases: [], tags: []),
        LogoMeta(slug: "sbi-indonesia", name: "SBI Indonesia", category: "bank-logo", aliases: ["sbididja", "498", "bank-sbi", "bank-sbi-indonesia"], tags: []),
        LogoMeta(slug: "seabank", name: "SeaBank", category: "bank-logo", aliases: ["sspiidja", "535", "bank-seabank-indonesia"], tags: []),
        LogoMeta(slug: "seabank-alt", name: "SeaBank (Alt)", category: "bank-logo", aliases: [], tags: []),
        LogoMeta(slug: "sequis", name: "Sequis", category: "insurance", aliases: [], tags: []),
        LogoMeta(slug: "sgqr", name: "SGQR", category: "qr-payment", aliases: [], tags: []),
        LogoMeta(slug: "sgqr-plus", name: "SGQR+", category: "qr-payment", aliases: [], tags: []),
        LogoMeta(slug: "shinhan-bank", name: "Shinhan Bank", category: "bank-logo", aliases: ["152", "meekidj1", "bank-shinhan", "bank-shinhan-indonesia"], tags: []),
        LogoMeta(slug: "shinhan-bank-alt", name: "Shinhan Bank (Alt)", category: "bank-logo", aliases: [], tags: []),
        LogoMeta(slug: "shopee", name: "Shopee", category: "e-commerce", aliases: [], tags: []),
        LogoMeta(slug: "shopee-alt", name: "Shopee (Alt)", category: "e-commerce", aliases: [], tags: []),
        LogoMeta(slug: "shopee-pay", name: "Shopee Pay", category: "e-wallet", aliases: ["shopeepay"], tags: []),
        LogoMeta(slug: "sicepat-ekspres", name: "SiCepat Ekspres", category: "logistic", aliases: ["sicepat"], tags: []),
        LogoMeta(slug: "simpati", name: "simPATI", category: "mobile-telco", aliases: ["simpati-new"], tags: []),
        LogoMeta(slug: "simpati-old", name: "simPATI (Old)", category: "mobile-telco", aliases: [], tags: []),
        LogoMeta(slug: "sinarmas", name: "Sinarmas", category: "bank-logo", aliases: ["sbjkidja", "153", "bank-sinarmas"], tags: []),
        LogoMeta(slug: "sinarmas-syariah", name: "Sinarmas Syariah", category: "bank-logo", aliases: [], tags: []),
        LogoMeta(slug: "skrill", name: "Skrill", category: "remittance", aliases: [], tags: []),
        LogoMeta(slug: "smartfren", name: "Smartfren", category: "mobile-telco", aliases: ["smart-fren"], tags: []),
        LogoMeta(slug: "smartfren-old", name: "Smartfren (Old)", category: "mobile-telco", aliases: [], tags: []),
        LogoMeta(slug: "speedcash", name: "SpeedCash", category: "e-wallet", aliases: [], tags: []),
        LogoMeta(slug: "spotify", name: "Spotify", category: "entertainment", aliases: [], tags: []),
        LogoMeta(slug: "spotify-alt", name: "Spotify (Alt)", category: "entertainment", aliases: [], tags: []),
        LogoMeta(slug: "spx-express", name: "SPX Express", category: "logistic", aliases: ["shopee-express", "spx"], tags: []),
        LogoMeta(slug: "standard-chartered", name: "Standard Chartered", category: "bank-logo", aliases: ["050", "scblidjx", "standchard", "standard-chartered-bank"], tags: []),
        LogoMeta(slug: "steam", name: "Steam", category: "game", aliases: [], tags: []),
        LogoMeta(slug: "stripe", name: "Stripe", category: "payment-gateway", aliases: [], tags: []),
        LogoMeta(slug: "sun-life", name: "Sun Life", category: "insurance", aliases: [], tags: []),
        LogoMeta(slug: "super-indo", name: "Super Indo", category: "supermarket", aliases: ["superindo"], tags: []),
        LogoMeta(slug: "superbank", name: "Superbank", category: "bank-logo", aliases: ["famaidj1", "562", "super-bank", "super-bank-indonesia"], tags: []),
        LogoMeta(slug: "superbank-alt", name: "Superbank (Alt)", category: "bank-logo", aliases: [], tags: []),
        LogoMeta(slug: "swift", name: "SWIFT", category: "remittance", aliases: [], tags: []),
        LogoMeta(slug: "swift-alt", name: "SWIFT (Alt)", category: "remittance", aliases: [], tags: []),
        LogoMeta(slug: "taf-toyota-astra-financial", name: "TAF - Toyota Astra Financial", category: "financing", aliases: ["taf", "toyota-astra-financial"], tags: []),
        LogoMeta(slug: "taspen", name: "Taspen", category: "insurance", aliases: [], tags: []),
        LogoMeta(slug: "telkomsel", name: "Telkomsel", category: "mobile-telco", aliases: ["tsel"], tags: []),
        LogoMeta(slug: "telkomsel-alt", name: "Telkomsel (Alt)", category: "mobile-telco", aliases: [], tags: []),
        LogoMeta(slug: "telkomsel-halo", name: "Telkomsel Halo", category: "mobile-telco", aliases: [], tags: []),
        LogoMeta(slug: "telkomsel-orbit", name: "Telkomsel Orbit", category: "isp", aliases: ["orbit"], tags: []),
        LogoMeta(slug: "telkomsel-prabayar", name: "Telkomsel Prabayar", category: "mobile-telco", aliases: [], tags: []),
        LogoMeta(slug: "thai-qr-payment", name: "Thai QR Payment", category: "qr-payment", aliases: [], tags: []),
        LogoMeta(slug: "thai-qr-payment-alt", name: "Thai QR Payment (Alt)", category: "qr-payment", aliases: [], tags: []),
        LogoMeta(slug: "the-foodhall", name: "The Foodhall", category: "supermarket", aliases: ["foodhall"], tags: []),
        LogoMeta(slug: "tiki", name: "TIKI", category: "logistic", aliases: ["titipan-kilat"], tags: []),
        LogoMeta(slug: "tiktok-shop", name: "TikTok Shop", category: "e-commerce", aliases: ["tiktokshop"], tags: []),
        LogoMeta(slug: "tokopedia", name: "Tokopedia", category: "e-commerce", aliases: [], tags: []),
        LogoMeta(slug: "tokopedia-alt", name: "Tokopedia (Alt)", category: "e-commerce", aliases: [], tags: []),
        LogoMeta(slug: "topremit", name: "Topremit", category: "remittance", aliases: [], tags: []),
        LogoMeta(slug: "topremit-alt", name: "Topremit (Alt)", category: "remittance", aliases: ["topremit-1"], tags: []),
        LogoMeta(slug: "toserba-yogya", name: "Toserba Yogya", category: "supermarket", aliases: [], tags: []),
        LogoMeta(slug: "toyota-financial-service", name: "Toyota Financial Service", category: "financing", aliases: ["tfs"], tags: []),
        LogoMeta(slug: "transfez", name: "Transfez", category: "remittance", aliases: [], tags: []),
        LogoMeta(slug: "transjakarta", name: "TransJakarta", category: "transportation", aliases: ["trans-jakarta", "busway"], tags: []),
        LogoMeta(slug: "transmart", name: "Transmart", category: "supermarket", aliases: [], tags: []),
        LogoMeta(slug: "transvision", name: "TransVision", category: "entertainment", aliases: ["transvision-new"], tags: []),
        LogoMeta(slug: "transvision-old", name: "TransVision (Old)", category: "entertainment", aliases: [], tags: []),
        LogoMeta(slug: "tri", name: "Tri", category: "mobile-telco", aliases: ["three"], tags: []),
        LogoMeta(slug: "truemoney", name: "TrueMoney", category: "e-wallet", aliases: ["true-money"], tags: []),
        LogoMeta(slug: "uangku", name: "Uangku", category: "e-wallet", aliases: [], tags: []),
        LogoMeta(slug: "ubisoft-plus", name: "UBISOFT+", category: "game", aliases: [], tags: []),
        LogoMeta(slug: "union-pay", name: "UnionPay", category: "card-payment", aliases: ["unionpay"], tags: []),
        LogoMeta(slug: "union-pay-contactless", name: "UnionPay Contactless", category: "card-payment", aliases: ["unionpay-contactless"], tags: []),
        LogoMeta(slug: "union-pay-contactless-en", name: "UnionPay Contactless (EN)", category: "card-payment", aliases: [], tags: []),
        LogoMeta(slug: "union-pay-en", name: "UnionPay (EN)", category: "card-payment", aliases: [], tags: []),
        LogoMeta(slug: "uob", name: "UOB", category: "bank-logo", aliases: ["023", "bbijidja", "uob-indonesia", "bank-uob-indonesia"], tags: []),
        LogoMeta(slug: "uob-ez-pay", name: "UOB EZ Pay", category: "direct-debit", aliases: ["uob-ezpay"], tags: []),
        LogoMeta(slug: "uob-tmrw", name: "UOB TMRW", category: "bank-app", aliases: ["tmrw"], tags: []),
        LogoMeta(slug: "verified-by-visa", name: "Verified by VISA", category: "card-payment", aliases: ["verified-by-visa-new", "vbv"], tags: []),
        LogoMeta(slug: "verified-by-visa-old", name: "Verified by VISA (Old)", category: "card-payment", aliases: [], tags: []),
        LogoMeta(slug: "verifone", name: "Verifone", category: "miscellaneous", aliases: ["verifone-new"], tags: []),
        LogoMeta(slug: "verifone-old", name: "Verifone (Old)", category: "miscellaneous", aliases: [], tags: []),
        LogoMeta(slug: "vidio", name: "Vidio", category: "entertainment", aliases: [], tags: []),
        LogoMeta(slug: "vietqr", name: "VietQR", category: "qr-payment", aliases: ["viet-qr"], tags: []),
        LogoMeta(slug: "visa", name: "VISA", category: "card-payment", aliases: [], tags: []),
        LogoMeta(slug: "visa-checkout", name: "VISA Checkout", category: "card-payment", aliases: [], tags: []),
        LogoMeta(slug: "visa-debit", name: "VISA Debit", category: "card-payment", aliases: [], tags: []),
        LogoMeta(slug: "visa-pay", name: "VISA Pay", category: "card-payment", aliases: [], tags: []),
        LogoMeta(slug: "visa-paywave", name: "VISA PayWave", category: "card-payment", aliases: ["paywave"], tags: []),
        LogoMeta(slug: "visa-plus", name: "VISA Plus", category: "card-payment", aliases: [], tags: []),
        LogoMeta(slug: "visa-secure-3ds", name: "VISA Secure (3DS)", category: "card-payment", aliases: [], tags: []),
        LogoMeta(slug: "visa-signature", name: "VISA Signature", category: "card-payment", aliases: [], tags: []),
        LogoMeta(slug: "vision-plus", name: "Vision+", category: "entertainment", aliases: ["visionplus"], tags: []),
        LogoMeta(slug: "viu", name: "VIU", category: "entertainment", aliases: [], tags: []),
        LogoMeta(slug: "wahana-express", name: "Wahana Express", category: "logistic", aliases: [], tags: []),
        LogoMeta(slug: "wahana-express-alt", name: "Wahana Express (Alt)", category: "logistic", aliases: [], tags: []),
        LogoMeta(slug: "wechat-pay", name: "WeChat Pay", category: "miscellaneous", aliases: ["wechatpay", "weixin-pay"], tags: []),
        LogoMeta(slug: "wechat-pay-alt", name: "WeChat Pay (Alt)", category: "miscellaneous", aliases: [], tags: []),
        LogoMeta(slug: "welab-bank", name: "Welab Bank", category: "bank-logo", aliases: [], tags: []),
        LogoMeta(slug: "western-union", name: "Western Union", category: "remittance", aliases: ["wu"], tags: []),
        LogoMeta(slug: "whoosh", name: "Whoosh", category: "transportation", aliases: ["kcic"], tags: []),
        LogoMeta(slug: "wirecard", name: "Wirecard", category: "miscellaneous", aliases: [], tags: []),
        LogoMeta(slug: "wise", name: "Wise", category: "remittance", aliases: [], tags: []),
        LogoMeta(slug: "wom-finance", name: "WOM Finance", category: "financing", aliases: [], tags: []),
        LogoMeta(slug: "wondr-by-bni", name: "Wondr by BNI", category: "bank-app", aliases: ["wondr"], tags: []),
        LogoMeta(slug: "world-bank", name: "World Bank", category: "regulatory", aliases: ["bank-dunia"], tags: []),
        LogoMeta(slug: "world-bank-alt", name: "World Bank (Alt)", category: "regulatory", aliases: [], tags: []),
        LogoMeta(slug: "xbox-game-pass", name: "XBOX Game Pass", category: "game", aliases: ["game-pass"], tags: []),
        LogoMeta(slug: "xendit", name: "Xendit", category: "payment-gateway", aliases: [], tags: []),
        LogoMeta(slug: "xl", name: "XL", category: "mobile-telco", aliases: [], tags: []),
        LogoMeta(slug: "xl-prioritas", name: "XL Prioritas", category: "mobile-telco", aliases: [], tags: []),
        LogoMeta(slug: "xl-satu", name: "XL Satu", category: "isp", aliases: [], tags: []),
        LogoMeta(slug: "xl-smart", name: "XL Smart", category: "mobile-telco", aliases: [], tags: []),
        LogoMeta(slug: "xl-smart-alt", name: "XL SMART (Alt)", category: "mobile-telco", aliases: [], tags: []),
        LogoMeta(slug: "xxi-21", name: "XXI (21)", category: "entertainment", aliases: [], tags: []),
        LogoMeta(slug: "yomart", name: "Yomart", category: "supermarket", aliases: [], tags: []),
        LogoMeta(slug: "yukk", name: "Yukk", category: "e-wallet", aliases: [], tags: []),
        LogoMeta(slug: "zalora", name: "Zalora", category: "e-commerce", aliases: [], tags: []),
        LogoMeta(slug: "zurich", name: "Zurich", category: "insurance", aliases: [], tags: []),
        LogoMeta(slug: "zurich-alt", name: "Zurich (Alt)", category: "insurance", aliases: [], tags: []),
    ]

    static let categories: [Category] = [
        Category(slug: "bank-app", displayName: "Bank App", count: 17),
        Category(slug: "bank-logo", displayName: "Bank Logo", count: 160),
        Category(slug: "card-payment", displayName: "Card Payment", count: 37),
        Category(slug: "direct-debit", displayName: "Direct Debit", count: 6),
        Category(slug: "donation", displayName: "Donation", count: 7),
        Category(slug: "e-commerce", displayName: "E-Commerce", count: 12),
        Category(slug: "e-wallet", displayName: "E-Wallet", count: 27),
        Category(slug: "entertainment", displayName: "Entertainment", count: 26),
        Category(slug: "financing", displayName: "Financing", count: 27),
        Category(slug: "game", displayName: "Game", count: 15),
        Category(slug: "government", displayName: "Government", count: 5),
        Category(slug: "insurance", displayName: "Insurance", count: 29),
        Category(slug: "isp", displayName: "ISP", count: 15),
        Category(slug: "logistic", displayName: "Logistic", count: 33),
        Category(slug: "miscellaneous", displayName: "Miscellaneous", count: 21),
        Category(slug: "mobile-telco", displayName: "Mobile Telco", count: 20),
        Category(slug: "payment-gateway", displayName: "Payment Gateway", count: 10),
        Category(slug: "prepaid-card", displayName: "Prepaid Card", count: 9),
        Category(slug: "qr-payment", displayName: "QR Payment", count: 11),
        Category(slug: "regulatory", displayName: "Regulatory", count: 15),
        Category(slug: "remittance", displayName: "Remittance", count: 14),
        Category(slug: "supermarket", displayName: "Supermarket", count: 24),
        Category(slug: "switching", displayName: "Switching", count: 13),
        Category(slug: "transportation", displayName: "Transportation", count: 12),
        Category(slug: "utilities", displayName: "Utilities", count: 7),
    ]
}
