// Generated file — do not edit by hand.
// Source: data/logos.yml. Regenerate via `npm run build:ios`.
//
// Logo SVGs are licensed CC-BY-NC-4.0 (see LICENSE-ASSETS at repo root).
// This Swift code is licensed MIT (see LICENSE at repo root).

import Foundation

internal enum Catalog {
    static let version: String = "2.3.0"

    static let logos: [LogoMeta] = [
        LogoMeta(slug: "2c2p", name: "2c2p", category: "payment-gateway", aliases: [], tags: []),
        LogoMeta(slug: "2c2p-new", name: "2c2p (New)", category: "payment-gateway", aliases: [], tags: []),
        LogoMeta(slug: "2c2p-new-alt", name: "2c2p (New-Alt)", category: "payment-gateway", aliases: [], tags: []),
        LogoMeta(slug: "acc", name: "ACC", category: "financing", aliases: [], tags: []),
        LogoMeta(slug: "acc-alt", name: "ACC (Alt)", category: "financing", aliases: [], tags: []),
        LogoMeta(slug: "adakami", name: "AdaKami", category: "financing", aliases: [], tags: []),
        LogoMeta(slug: "adakami-alt", name: "AdaKami (Alt)", category: "financing", aliases: [], tags: []),
        LogoMeta(slug: "adira-finance", name: "Adira Finance", category: "financing", aliases: [], tags: []),
        LogoMeta(slug: "aeon", name: "AEON", category: "supermarket", aliases: [], tags: []),
        LogoMeta(slug: "aeon-credit-service", name: "AEON Credit Service", category: "financing", aliases: [], tags: []),
        LogoMeta(slug: "aetra-tangerang", name: "Aetra Tangerang", category: "utilities", aliases: [], tags: []),
        LogoMeta(slug: "afpi", name: "AFPI", category: "regulatory", aliases: [], tags: []),
        LogoMeta(slug: "aia", name: "AIA", category: "insurance", aliases: [], tags: []),
        LogoMeta(slug: "akulaku", name: "Akulaku", category: "financing", aliases: [], tags: []),
        LogoMeta(slug: "akulaku-paylater", name: "Akulaku Paylater", category: "financing", aliases: [], tags: []),
        LogoMeta(slug: "aladin", name: "Aladin", category: "bank-logo", aliases: [], tags: []),
        LogoMeta(slug: "alfa-express", name: "Alfa Express", category: "supermarket", aliases: [], tags: []),
        LogoMeta(slug: "alfamart", name: "Alfamart", category: "supermarket", aliases: [], tags: []),
        LogoMeta(slug: "alfamidi", name: "Alfamidi", category: "supermarket", aliases: [], tags: []),
        LogoMeta(slug: "alfamidi-super", name: "Alfamidi Super", category: "supermarket", aliases: [], tags: []),
        LogoMeta(slug: "alipay-new", name: "Alipay (New)", category: "miscellaneous", aliases: [], tags: []),
        LogoMeta(slug: "alipay-old", name: "Alipay (Old)", category: "miscellaneous", aliases: [], tags: []),
        LogoMeta(slug: "alipay-plus", name: "Alipay+", category: "miscellaneous", aliases: [], tags: []),
        LogoMeta(slug: "alipay-plus-old", name: "Alipay+ (Old)", category: "miscellaneous", aliases: [], tags: []),
        LogoMeta(slug: "alipay-plus-old-alt", name: "Alipay+ (Old Alt)", category: "miscellaneous", aliases: [], tags: []),
        LogoMeta(slug: "allianz", name: "Allianz", category: "insurance", aliases: [], tags: []),
        LogoMeta(slug: "allianz-alt", name: "Allianz (Alt)", category: "insurance", aliases: [], tags: []),
        LogoMeta(slug: "allo", name: "Allo", category: "bank-logo", aliases: [], tags: []),
        LogoMeta(slug: "alto", name: "ALTO", category: "switching", aliases: [], tags: []),
        LogoMeta(slug: "amar-bank", name: "Amar Bank", category: "bank-logo", aliases: [], tags: []),
        LogoMeta(slug: "amercian-express-alt", name: "Amercian Express (Alt)", category: "card-payment", aliases: [], tags: []),
        LogoMeta(slug: "american-express", name: "American Express", category: "card-payment", aliases: [], tags: []),
        LogoMeta(slug: "american-express-alt-2", name: "American Express (Alt-2)", category: "card-payment", aliases: [], tags: []),
        LogoMeta(slug: "anteraja", name: "Anteraja", category: "logistic", aliases: [], tags: []),
        LogoMeta(slug: "anz", name: "ANZ", category: "bank-logo", aliases: [], tags: []),
        LogoMeta(slug: "app-store", name: "App Store", category: "game", aliases: [], tags: []),
        LogoMeta(slug: "apple-arcade", name: "Apple Arcade", category: "game", aliases: [], tags: []),
        LogoMeta(slug: "apple-card", name: "Apple Card", category: "card-payment", aliases: [], tags: []),
        LogoMeta(slug: "apple-music", name: "Apple Music", category: "entertainment", aliases: [], tags: []),
        LogoMeta(slug: "apple-pay", name: "Apple Pay", category: "miscellaneous", aliases: [], tags: []),
        LogoMeta(slug: "aspi", name: "ASPI", category: "regulatory", aliases: [], tags: []),
        LogoMeta(slug: "assa", name: "ASSA", category: "logistic", aliases: [], tags: []),
        LogoMeta(slug: "astra-life", name: "Astra Life", category: "insurance", aliases: [], tags: []),
        LogoMeta(slug: "astra-life-alt", name: "Astra Life (Alt)", category: "insurance", aliases: [], tags: []),
        LogoMeta(slug: "astra-pay", name: "Astra Pay", category: "e-wallet", aliases: [], tags: []),
        LogoMeta(slug: "asuransi-sinarmas-insurtech", name: "Asuransi Sinarmas Insurtech", category: "insurance", aliases: [], tags: []),
        LogoMeta(slug: "atm-bersama", name: "ATM Bersama", category: "switching", aliases: [], tags: []),
        LogoMeta(slug: "axa", name: "AXA", category: "insurance", aliases: [], tags: []),
        LogoMeta(slug: "axis", name: "AXIS", category: "mobile-telco", aliases: [], tags: []),
        LogoMeta(slug: "ayo-ke-bank", name: "AYO ke Bank", category: "regulatory", aliases: [], tags: []),
        LogoMeta(slug: "bangkok-bank", name: "Bangkok Bank", category: "bank-logo", aliases: [], tags: []),
        LogoMeta(slug: "bank-artha-graha-internasional", name: "Bank Artha Graha Internasional", category: "bank-logo", aliases: [], tags: []),
        LogoMeta(slug: "bank-bengkulu", name: "Bank Bengkulu", category: "bank-logo", aliases: [], tags: []),
        LogoMeta(slug: "bank-bjb", name: "Bank BJB", category: "bank-logo", aliases: [], tags: []),
        LogoMeta(slug: "bank-bjb-syariah", name: "Bank BJB Syariah", category: "bank-logo", aliases: [], tags: []),
        LogoMeta(slug: "bank-bpd-aceh", name: "Bank BPD Aceh", category: "bank-logo", aliases: [], tags: []),
        LogoMeta(slug: "bank-bpd-bali", name: "Bank BPD Bali", category: "bank-logo", aliases: [], tags: []),
        LogoMeta(slug: "bank-bpd-banten", name: "Bank BPD Banten", category: "bank-logo", aliases: [], tags: []),
        LogoMeta(slug: "bank-bpd-diy", name: "Bank BPD DIY", category: "bank-logo", aliases: [], tags: []),
        LogoMeta(slug: "bank-bpd-jambi", name: "Bank BPD Jambi", category: "bank-logo", aliases: [], tags: []),
        LogoMeta(slug: "bank-bpd-jateng", name: "Bank BPD Jateng", category: "bank-logo", aliases: [], tags: []),
        LogoMeta(slug: "bank-bpd-jatim", name: "Bank BPD Jatim", category: "bank-logo", aliases: [], tags: []),
        LogoMeta(slug: "bank-bpd-kalbar", name: "Bank BPD Kalbar", category: "bank-logo", aliases: [], tags: []),
        LogoMeta(slug: "bank-bpd-kalbar-alt", name: "Bank BPD Kalbar (Alt)", category: "bank-logo", aliases: [], tags: []),
        LogoMeta(slug: "bank-bpd-kalimantan-timur", name: "Bank BPD Kalimantan Timur", category: "bank-logo", aliases: [], tags: []),
        LogoMeta(slug: "bank-bpd-kalsel", name: "Bank BPD Kalsel", category: "bank-logo", aliases: [], tags: []),
        LogoMeta(slug: "bank-bpd-kalteng", name: "Bank BPD Kalteng", category: "bank-logo", aliases: [], tags: []),
        LogoMeta(slug: "bank-bpd-lampung", name: "Bank BPD Lampung", category: "bank-logo", aliases: [], tags: []),
        LogoMeta(slug: "bank-bpd-maluku-malut", name: "Bank BPD Maluku Malut", category: "bank-logo", aliases: [], tags: []),
        LogoMeta(slug: "bank-bpd-ntb-syariah", name: "Bank BPD NTB Syariah", category: "bank-logo", aliases: [], tags: []),
        LogoMeta(slug: "bank-bpd-ntb-syariah-alt", name: "Bank BPD NTB Syariah (Alt)", category: "bank-logo", aliases: [], tags: []),
        LogoMeta(slug: "bank-bpd-ntt", name: "Bank BPD NTT", category: "bank-logo", aliases: [], tags: []),
        LogoMeta(slug: "bank-bpd-papua", name: "Bank BPD Papua", category: "bank-logo", aliases: [], tags: []),
        LogoMeta(slug: "bank-bpd-riau-kepri", name: "Bank BPD Riau Kepri", category: "bank-logo", aliases: [], tags: []),
        LogoMeta(slug: "bank-bpd-riau-kepri-syariah", name: "Bank BPD Riau Kepri Syariah", category: "bank-logo", aliases: [], tags: []),
        LogoMeta(slug: "bank-bpd-sulselbar", name: "Bank BPD Sulselbar", category: "bank-logo", aliases: [], tags: []),
        LogoMeta(slug: "bank-bpd-sulteng", name: "Bank BPD Sulteng", category: "bank-logo", aliases: [], tags: []),
        LogoMeta(slug: "bank-bpd-sultra", name: "Bank BPD Sultra", category: "bank-logo", aliases: [], tags: []),
        LogoMeta(slug: "bank-bpd-sulutgo", name: "Bank BPD Sulutgo", category: "bank-logo", aliases: [], tags: []),
        LogoMeta(slug: "bank-bpd-sumsel-babel", name: "Bank BPD Sumsel Babel", category: "bank-logo", aliases: [], tags: []),
        LogoMeta(slug: "bank-bpd-sumsel-babel-alt-1", name: "Bank BPD Sumsel Babel (Alt-1)", category: "bank-logo", aliases: [], tags: []),
        LogoMeta(slug: "bank-bpd-sumsel-babel-alt-2", name: "Bank BPD Sumsel Babel (Alt-2)", category: "bank-logo", aliases: [], tags: []),
        LogoMeta(slug: "bank-bpd-sumut", name: "Bank BPD Sumut", category: "bank-logo", aliases: [], tags: []),
        LogoMeta(slug: "bank-bumi-artha", name: "Bank Bumi Artha", category: "bank-logo", aliases: [], tags: []),
        LogoMeta(slug: "bank-capital", name: "Bank Capital", category: "bank-logo", aliases: [], tags: []),
        LogoMeta(slug: "bank-capital-alt", name: "Bank Capital (Alt)", category: "bank-logo", aliases: [], tags: []),
        LogoMeta(slug: "bank-dki", name: "Bank DKI", category: "bank-logo", aliases: [], tags: []),
        LogoMeta(slug: "bank-dki-1", name: "Bank DKI-1", category: "bank-logo", aliases: [], tags: []),
        LogoMeta(slug: "bank-ganesha", name: "Bank Ganesha", category: "bank-logo", aliases: [], tags: []),
        LogoMeta(slug: "bank-ina", name: "Bank INA", category: "bank-logo", aliases: [], tags: []),
        LogoMeta(slug: "bank-index-selindo", name: "Bank Index Selindo", category: "bank-logo", aliases: [], tags: []),
        LogoMeta(slug: "bank-index-selindo-alt", name: "Bank Index Selindo (Alt)", category: "bank-logo", aliases: [], tags: []),
        LogoMeta(slug: "bank-indonesia", name: "Bank Indonesia", category: "regulatory", aliases: [], tags: []),
        LogoMeta(slug: "bank-jasa-jakarta", name: "Bank Jasa Jakarta", category: "bank-logo", aliases: [], tags: []),
        LogoMeta(slug: "bank-lampung", name: "Bank Lampung", category: "bank-logo", aliases: [], tags: []),
        LogoMeta(slug: "bank-mas", name: "Bank Mas", category: "bank-logo", aliases: [], tags: []),
        LogoMeta(slug: "bank-maspion", name: "Bank Maspion", category: "bank-logo", aliases: [], tags: []),
        LogoMeta(slug: "bank-maspion-alt", name: "Bank Maspion (Alt)", category: "bank-logo", aliases: [], tags: []),
        LogoMeta(slug: "bank-mayapada", name: "Bank Mayapada", category: "bank-logo", aliases: [], tags: []),
        LogoMeta(slug: "bank-mayapada-alt", name: "Bank Mayapada (Alt)", category: "bank-logo", aliases: [], tags: []),
        LogoMeta(slug: "bank-mayora", name: "Bank Mayora", category: "bank-logo", aliases: [], tags: []),
        LogoMeta(slug: "bank-mestika-dharma", name: "Bank Mestika Dharma", category: "bank-logo", aliases: [], tags: []),
        LogoMeta(slug: "bank-nagari", name: "Bank Nagari", category: "bank-logo", aliases: [], tags: []),
        LogoMeta(slug: "bank-of-america", name: "Bank of America", category: "bank-logo", aliases: [], tags: []),
        LogoMeta(slug: "bank-of-china", name: "Bank of China", category: "bank-logo", aliases: [], tags: []),
        LogoMeta(slug: "bank-of-india", name: "Bank of India", category: "bank-logo", aliases: [], tags: []),
        LogoMeta(slug: "bank-of-india-indonesia", name: "Bank of India Indonesia", category: "bank-logo", aliases: [], tags: []),
        LogoMeta(slug: "bank-raya", name: "Bank Raya", category: "bank-logo", aliases: [], tags: []),
        LogoMeta(slug: "bank-resona-perdania", name: "Bank Resona Perdania", category: "bank-logo", aliases: [], tags: []),
        LogoMeta(slug: "bank-resona-perdania-alt", name: "Bank Resona Perdania (Alt)", category: "bank-logo", aliases: [], tags: []),
        LogoMeta(slug: "bank-sahabat-sampoerna", name: "Bank Sahabat Sampoerna", category: "bank-logo", aliases: [], tags: []),
        LogoMeta(slug: "bank-saqu", name: "Bank Saqu", category: "bank-logo", aliases: [], tags: []),
        LogoMeta(slug: "bank-saqu-alt", name: "Bank Saqu (Alt)", category: "bank-logo", aliases: [], tags: []),
        LogoMeta(slug: "bank-smbc-indonesia", name: "Bank SMBC Indonesia", category: "bank-logo", aliases: [], tags: []),
        LogoMeta(slug: "bank-victoria", name: "Bank Victoria", category: "bank-logo", aliases: [], tags: []),
        LogoMeta(slug: "bank-victoria-syariah", name: "Bank Victoria Syariah", category: "bank-logo", aliases: [], tags: []),
        LogoMeta(slug: "bank-woori-saudara", name: "Bank Woori Saudara", category: "bank-logo", aliases: [], tags: []),
        LogoMeta(slug: "bappebti", name: "BAPPEBTI", category: "regulatory", aliases: [], tags: []),
        LogoMeta(slug: "baznas", name: "BAZNAS", category: "donation", aliases: [], tags: []),
        LogoMeta(slug: "bca", name: "BCA", category: "bank-logo", aliases: [], tags: []),
        LogoMeta(slug: "bca-atm", name: "BCA ATM", category: "switching", aliases: [], tags: []),
        LogoMeta(slug: "bca-debit", name: "BCA Debit", category: "switching", aliases: [], tags: []),
        LogoMeta(slug: "bca-digital", name: "BCA Digital", category: "bank-logo", aliases: [], tags: []),
        LogoMeta(slug: "bca-finance", name: "BCA Finance", category: "financing", aliases: [], tags: []),
        LogoMeta(slug: "bca-flazz", name: "BCA Flazz", category: "prepaid-card", aliases: [], tags: []),
        LogoMeta(slug: "bca-flazz-alt", name: "BCA Flazz (Alt)", category: "prepaid-card", aliases: [], tags: []),
        LogoMeta(slug: "bca-flazz-new", name: "BCA Flazz (New)", category: "prepaid-card", aliases: [], tags: []),
        LogoMeta(slug: "bca-klikpay", name: "BCA KlikPay", category: "direct-debit", aliases: [], tags: []),
        LogoMeta(slug: "bca-life", name: "BCA Life", category: "insurance", aliases: [], tags: []),
        LogoMeta(slug: "bca-mobile", name: "BCA Mobile", category: "bank-app", aliases: [], tags: []),
        LogoMeta(slug: "bca-syariah", name: "BCA Syariah", category: "bank-logo", aliases: [], tags: []),
        LogoMeta(slug: "bea-cukai", name: "Bea Cukai", category: "government", aliases: [], tags: []),
        LogoMeta(slug: "bfi-finance", name: "BFI Finance", category: "financing", aliases: [], tags: []),
        LogoMeta(slug: "bhinneka", name: "Bhinneka", category: "e-commerce", aliases: [], tags: []),
        LogoMeta(slug: "bi-fast", name: "BI-FAST", category: "switching", aliases: [], tags: []),
        LogoMeta(slug: "biznet", name: "Biznet", category: "isp", aliases: [], tags: []),
        LogoMeta(slug: "biznet-home", name: "Biznet Home", category: "isp", aliases: [], tags: []),
        LogoMeta(slug: "blibli", name: "Blibli", category: "e-commerce", aliases: [], tags: []),
        LogoMeta(slug: "blu-bca", name: "Blu BCA", category: "bank-logo", aliases: [], tags: []),
        LogoMeta(slug: "bluepay", name: "Bluepay", category: "e-wallet", aliases: [], tags: []),
        LogoMeta(slug: "bnc", name: "BNC", category: "bank-logo", aliases: [], tags: []),
        LogoMeta(slug: "bni", name: "BNI", category: "bank-logo", aliases: [], tags: []),
        LogoMeta(slug: "bni-mobile-banking", name: "BNI Mobile Banking", category: "bank-app", aliases: [], tags: []),
        LogoMeta(slug: "bni-tapcash", name: "BNI TapCash", category: "prepaid-card", aliases: [], tags: []),
        LogoMeta(slug: "bnp-paribas", name: "BNP Paribas", category: "bank-logo", aliases: [], tags: []),
        LogoMeta(slug: "bpd", name: "BPD", category: "regulatory", aliases: [], tags: []),
        LogoMeta(slug: "bpjs", name: "BPJS", category: "insurance", aliases: [], tags: []),
        LogoMeta(slug: "bpjs-alt", name: "BPJS (Alt)", category: "insurance", aliases: [], tags: []),
        LogoMeta(slug: "bpjs-ketenagakerjaan", name: "BPJS Ketenagakerjaan", category: "insurance", aliases: [], tags: []),
        LogoMeta(slug: "bri", name: "BRI", category: "bank-logo", aliases: [], tags: []),
        LogoMeta(slug: "bri-alt", name: "BRI (Alt)", category: "bank-logo", aliases: [], tags: []),
        LogoMeta(slug: "bri-brizzi", name: "BRI BRIZZI", category: "prepaid-card", aliases: [], tags: []),
        LogoMeta(slug: "bri-brizzi-alt", name: "BRI BRIZZI (Alt)", category: "prepaid-card", aliases: [], tags: []),
        LogoMeta(slug: "bri-direct-debit", name: "BRI Direct Debit", category: "direct-debit", aliases: [], tags: []),
        LogoMeta(slug: "bri-finance", name: "BRI Finance", category: "financing", aliases: [], tags: []),
        LogoMeta(slug: "bri-insurance", name: "BRI Insurance", category: "insurance", aliases: [], tags: []),
        LogoMeta(slug: "bri-life", name: "BRI Life", category: "insurance", aliases: [], tags: []),
        LogoMeta(slug: "bri-new", name: "BRI (New)", category: "bank-logo", aliases: [], tags: []),
        LogoMeta(slug: "bri-vertical", name: "BRI (Vertical)", category: "bank-logo", aliases: [], tags: []),
        LogoMeta(slug: "bright", name: "Bright", category: "supermarket", aliases: [], tags: []),
        LogoMeta(slug: "brimo", name: "BRImo", category: "bank-app", aliases: [], tags: []),
        LogoMeta(slug: "brins", name: "BRINS", category: "insurance", aliases: [], tags: []),
        LogoMeta(slug: "bsi", name: "BSI", category: "bank-logo", aliases: [], tags: []),
        LogoMeta(slug: "bsi-mobile", name: "BSI Mobile", category: "bank-app", aliases: [], tags: []),
        LogoMeta(slug: "bsn", name: "BSN", category: "bank-logo", aliases: [], tags: []),
        LogoMeta(slug: "bsn-alt", name: "BSN (Alt)", category: "bank-logo", aliases: [], tags: []),
        LogoMeta(slug: "btn", name: "BTN", category: "bank-logo", aliases: [], tags: []),
        LogoMeta(slug: "btn-alt", name: "BTN (Alt)", category: "bank-logo", aliases: [], tags: []),
        LogoMeta(slug: "btn-new", name: "BTN (New)", category: "bank-logo", aliases: [], tags: []),
        LogoMeta(slug: "btn-syariah", name: "BTN Syariah", category: "bank-logo", aliases: [], tags: []),
        LogoMeta(slug: "btn-syariah-new", name: "BTN Syariah (New)", category: "bank-logo", aliases: [], tags: []),
        LogoMeta(slug: "btpn", name: "BTPN", category: "bank-logo", aliases: [], tags: []),
        LogoMeta(slug: "btpn-syariah", name: "BTPN Syariah", category: "bank-logo", aliases: [], tags: []),
        LogoMeta(slug: "bukalapak", name: "Bukalapak", category: "e-commerce", aliases: [], tags: []),
        LogoMeta(slug: "bukalapak-alt", name: "Bukalapak (Alt)", category: "e-commerce", aliases: [], tags: []),
        LogoMeta(slug: "bukalapak-new", name: "Bukalapak (New)", category: "e-commerce", aliases: [], tags: []),
        LogoMeta(slug: "bumiputera", name: "Bumiputera", category: "insurance", aliases: [], tags: []),
        LogoMeta(slug: "bussan-auto-finance", name: "Bussan Auto Finance", category: "financing", aliases: [], tags: []),
        LogoMeta(slug: "by-u", name: "by.U", category: "mobile-telco", aliases: [], tags: []),
        LogoMeta(slug: "byond-bsi", name: "BYOND BSI", category: "bank-app", aliases: [], tags: []),
        LogoMeta(slug: "byond-bsi-alt", name: "BYOND BSI (Alt)", category: "bank-app", aliases: [], tags: []),
        LogoMeta(slug: "catchplay", name: "Catchplay", category: "entertainment", aliases: [], tags: []),
        LogoMeta(slug: "cbn", name: "CBN", category: "isp", aliases: [], tags: []),
        LogoMeta(slug: "ccb-indonesia", name: "CCB Indonesia", category: "bank-logo", aliases: [], tags: []),
        LogoMeta(slug: "ccb-indonesia-alt", name: "CCB Indonesia (Alt)", category: "bank-logo", aliases: [], tags: []),
        LogoMeta(slug: "cgv", name: "CGV", category: "entertainment", aliases: [], tags: []),
        LogoMeta(slug: "chubb", name: "CHUBB", category: "insurance", aliases: [], tags: []),
        LogoMeta(slug: "cimb-niaga", name: "CIMB Niaga", category: "bank-logo", aliases: [], tags: []),
        LogoMeta(slug: "cimb-niaga-syariah", name: "CIMB Niaga Syariah", category: "bank-logo", aliases: [], tags: []),
        LogoMeta(slug: "cinepolis", name: "Cinepolis", category: "entertainment", aliases: [], tags: []),
        LogoMeta(slug: "circle-k", name: "Circle K", category: "supermarket", aliases: [], tags: []),
        LogoMeta(slug: "circle-k-alt", name: "Circle K (Alt)", category: "supermarket", aliases: [], tags: []),
        LogoMeta(slug: "cirrus", name: "Cirrus", category: "card-payment", aliases: [], tags: []),
        LogoMeta(slug: "citibank", name: "Citibank", category: "bank-logo", aliases: [], tags: []),
        LogoMeta(slug: "citibank-alt", name: "Citibank (Alt)", category: "bank-logo", aliases: [], tags: []),
        LogoMeta(slug: "cititrans", name: "Cititrans", category: "transportation", aliases: [], tags: []),
        LogoMeta(slug: "commonwealth", name: "Commonwealth", category: "bank-logo", aliases: [], tags: []),
        LogoMeta(slug: "commonwealth-life", name: "Commonwealth Life", category: "insurance", aliases: [], tags: []),
        LogoMeta(slug: "contactless", name: "Contactless", category: "card-payment", aliases: [], tags: []),
        LogoMeta(slug: "contactless-alt", name: "Contactless (Alt)", category: "card-payment", aliases: [], tags: []),
        LogoMeta(slug: "credit-suisse", name: "Credit Suisse", category: "bank-logo", aliases: [], tags: []),
        LogoMeta(slug: "ctbc-bank", name: "CTBC Bank", category: "bank-logo", aliases: [], tags: []),
        LogoMeta(slug: "daihatsu-financial-service", name: "Daihatsu Financial Service", category: "financing", aliases: [], tags: []),
        LogoMeta(slug: "dakota-cargo", name: "Dakota Cargo", category: "logistic", aliases: [], tags: []),
        LogoMeta(slug: "dakota-logistik", name: "Dakota Logistik", category: "logistic", aliases: [], tags: []),
        LogoMeta(slug: "damri", name: "DAMRI", category: "transportation", aliases: [], tags: []),
        LogoMeta(slug: "dan-plus-dan", name: "Dan+Dan", category: "supermarket", aliases: [], tags: []),
        LogoMeta(slug: "dana", name: "DANA", category: "e-wallet", aliases: [], tags: []),
        LogoMeta(slug: "danamon", name: "Danamon", category: "bank-logo", aliases: [], tags: []),
        LogoMeta(slug: "danamon-mufg", name: "Danamon (MUFG)", category: "bank-logo", aliases: [], tags: []),
        LogoMeta(slug: "danamon-syariah", name: "Danamon Syariah", category: "bank-logo", aliases: [], tags: []),
        LogoMeta(slug: "daytrans", name: "DayTrans", category: "transportation", aliases: [], tags: []),
        LogoMeta(slug: "dbs", name: "DBS", category: "bank-logo", aliases: [], tags: []),
        LogoMeta(slug: "dbs-paylah", name: "DBS Paylah", category: "miscellaneous", aliases: [], tags: []),
        LogoMeta(slug: "deutsche-bank", name: "Deutsche Bank", category: "bank-logo", aliases: [], tags: []),
        LogoMeta(slug: "dhl-express", name: "DHL Express", category: "logistic", aliases: [], tags: []),
        LogoMeta(slug: "digibank", name: "Digibank", category: "bank-app", aliases: [], tags: []),
        LogoMeta(slug: "digibank-alt", name: "Digibank (Alt)", category: "bank-app", aliases: [], tags: []),
        LogoMeta(slug: "dipay", name: "Dipay", category: "e-wallet", aliases: [], tags: []),
        LogoMeta(slug: "discover", name: "Discover", category: "card-payment", aliases: [], tags: []),
        LogoMeta(slug: "discover-alt", name: "Discover (Alt)", category: "card-payment", aliases: [], tags: []),
        LogoMeta(slug: "disney-plus", name: "Disney+", category: "entertainment", aliases: [], tags: []),
        LogoMeta(slug: "disney-plus-hotstar", name: "Disney+ Hotstar", category: "entertainment", aliases: [], tags: []),
        LogoMeta(slug: "djp-online", name: "DJP Online", category: "government", aliases: [], tags: []),
        LogoMeta(slug: "djp-online-alt", name: "DJP Online (Alt)", category: "government", aliases: [], tags: []),
        LogoMeta(slug: "doku", name: "DOKU", category: "e-wallet", aliases: [], tags: []),
        LogoMeta(slug: "dompet-dhuafa", name: "Dompet Dhuafa", category: "donation", aliases: [], tags: []),
        LogoMeta(slug: "dompet-dhuafa-alt", name: "Dompet Dhuafa (Alt)", category: "donation", aliases: [], tags: []),
        LogoMeta(slug: "duitnow", name: "DuitNow", category: "qr-payment", aliases: [], tags: []),
        LogoMeta(slug: "duitnow-qr", name: "DuitNow QR", category: "qr-payment", aliases: [], tags: []),
        LogoMeta(slug: "dutamoney", name: "Dutamoney", category: "e-wallet", aliases: [], tags: []),
        LogoMeta(slug: "e-toll-card", name: "e-Toll Card", category: "prepaid-card", aliases: [], tags: []),
        LogoMeta(slug: "ea-play", name: "EA Play", category: "game", aliases: [], tags: []),
        LogoMeta(slug: "ea-play-alt", name: "EA Play (Alt)", category: "game", aliases: [], tags: []),
        LogoMeta(slug: "ekonomi-syariah", name: "Ekonomi Syariah", category: "regulatory", aliases: [], tags: []),
        LogoMeta(slug: "ekonomi-syariah-alt", name: "Ekonomi Syariah (Alt)", category: "regulatory", aliases: [], tags: []),
        LogoMeta(slug: "ems", name: "EMS", category: "logistic", aliases: [], tags: []),
        LogoMeta(slug: "epic-games", name: "Epic Games", category: "game", aliases: [], tags: []),
        LogoMeta(slug: "epic-games-store", name: "Epic Games Store", category: "game", aliases: [], tags: []),
        LogoMeta(slug: "esl-express", name: "ESL Express", category: "logistic", aliases: [], tags: []),
        LogoMeta(slug: "espay", name: "Espay", category: "payment-gateway", aliases: [], tags: []),
        LogoMeta(slug: "family-mart", name: "Family Mart", category: "supermarket", aliases: [], tags: []),
        LogoMeta(slug: "fedex-express", name: "FedEx Express", category: "logistic", aliases: [], tags: []),
        LogoMeta(slug: "fif-astra", name: "FIF Astra", category: "financing", aliases: [], tags: []),
        LogoMeta(slug: "finmas", name: "Finmas", category: "financing", aliases: [], tags: []),
        LogoMeta(slug: "finpay", name: "Finpay", category: "payment-gateway", aliases: [], tags: []),
        LogoMeta(slug: "first-logistic", name: "First Logistic", category: "logistic", aliases: [], tags: []),
        LogoMeta(slug: "first-media", name: "First Media", category: "isp", aliases: [], tags: []),
        LogoMeta(slug: "flip", name: "Flip", category: "remittance", aliases: [], tags: []),
        LogoMeta(slug: "fwd", name: "FWD", category: "insurance", aliases: [], tags: []),
        LogoMeta(slug: "generali", name: "Generali", category: "insurance", aliases: [], tags: []),
        LogoMeta(slug: "giant", name: "Giant", category: "supermarket", aliases: [], tags: []),
        LogoMeta(slug: "google-pay", name: "Google Pay", category: "miscellaneous", aliases: [], tags: []),
        LogoMeta(slug: "google-play", name: "Google Play", category: "game", aliases: [], tags: []),
        LogoMeta(slug: "google-play-alt", name: "Google Play (Alt)", category: "game", aliases: [], tags: []),
        LogoMeta(slug: "gopay", name: "Gopay", category: "e-wallet", aliases: [], tags: []),
        LogoMeta(slug: "gopay-alt", name: "Gopay (Alt)", category: "e-wallet", aliases: [], tags: []),
        LogoMeta(slug: "gopaylater", name: "Gopaylater", category: "financing", aliases: [], tags: []),
        LogoMeta(slug: "gpn", name: "GPN", category: "card-payment", aliases: [], tags: []),
        LogoMeta(slug: "grab-pay", name: "Grab Pay", category: "miscellaneous", aliases: [], tags: []),
        LogoMeta(slug: "hbo-go", name: "HBO GO", category: "entertainment", aliases: [], tags: []),
        LogoMeta(slug: "hero", name: "Hero", category: "supermarket", aliases: [], tags: []),
        LogoMeta(slug: "hibank", name: "hibank", category: "bank-logo", aliases: [], tags: []),
        LogoMeta(slug: "home-credit", name: "Home Credit", category: "financing", aliases: [], tags: []),
        LogoMeta(slug: "hoox", name: "HOOX", category: "entertainment", aliases: [], tags: []),
        LogoMeta(slug: "hsbc", name: "HSBC", category: "bank-logo", aliases: [], tags: []),
        LogoMeta(slug: "hypermart", name: "Hypermart", category: "supermarket", aliases: [], tags: []),
        LogoMeta(slug: "i-saku", name: "I.Saku", category: "e-wallet", aliases: [], tags: []),
        LogoMeta(slug: "ibk-bank", name: "IBK Bank", category: "bank-logo", aliases: [], tags: []),
        LogoMeta(slug: "icbc", name: "ICBC", category: "bank-logo", aliases: [], tags: []),
        LogoMeta(slug: "icbc-alt", name: "ICBC (Alt)", category: "bank-logo", aliases: [], tags: []),
        LogoMeta(slug: "iconnet", name: "Iconnet", category: "isp", aliases: [], tags: []),
        LogoMeta(slug: "id-express", name: "ID Express", category: "logistic", aliases: [], tags: []),
        LogoMeta(slug: "im3", name: "IM3", category: "mobile-telco", aliases: [], tags: []),
        LogoMeta(slug: "indah-cargo", name: "Indah Cargo", category: "logistic", aliases: [], tags: []),
        LogoMeta(slug: "indihome-new", name: "IndiHome (New)", category: "isp", aliases: [], tags: []),
        LogoMeta(slug: "indihome-old", name: "IndiHome (Old)", category: "isp", aliases: [], tags: []),
        LogoMeta(slug: "indodana", name: "Indodana", category: "financing", aliases: [], tags: []),
        LogoMeta(slug: "indogrosir", name: "Indogrosir", category: "supermarket", aliases: [], tags: []),
        LogoMeta(slug: "indomaret", name: "Indomaret", category: "supermarket", aliases: [], tags: []),
        LogoMeta(slug: "indosat-hifi", name: "Indosat Hifi", category: "isp", aliases: [], tags: []),
        LogoMeta(slug: "indosat-m2", name: "Indosat M2", category: "isp", aliases: [], tags: []),
        LogoMeta(slug: "ing-bank", name: "ING Bank", category: "bank-logo", aliases: [], tags: []),
        LogoMeta(slug: "inklusi-keuangan", name: "Inklusi Keuangan", category: "regulatory", aliases: [], tags: []),
        LogoMeta(slug: "interlink", name: "Interlink", category: "miscellaneous", aliases: [], tags: []),
        LogoMeta(slug: "ipay88", name: "ipay88", category: "payment-gateway", aliases: [], tags: []),
        LogoMeta(slug: "j-and-t-cargo", name: "J&T Cargo", category: "logistic", aliases: [], tags: []),
        LogoMeta(slug: "j-and-t-express", name: "J&T Express", category: "logistic", aliases: [], tags: []),
        LogoMeta(slug: "j-trust-bank", name: "J Trust Bank", category: "bank-logo", aliases: [], tags: []),
        LogoMeta(slug: "jago", name: "Jago", category: "bank-logo", aliases: [], tags: []),
        LogoMeta(slug: "jago-app", name: "Jago", category: "bank-app", aliases: [], tags: []),
        LogoMeta(slug: "jakcard", name: "Jakcard", category: "prepaid-card", aliases: [], tags: []),
        LogoMeta(slug: "jaklingko", name: "JakLingko", category: "transportation", aliases: [], tags: []),
        LogoMeta(slug: "jakone-mobile", name: "JakOne Mobile", category: "bank-app", aliases: [], tags: []),
        LogoMeta(slug: "jakone-pay", name: "JakOne Pay", category: "e-wallet", aliases: [], tags: []),
        LogoMeta(slug: "jalin", name: "Jalin", category: "switching", aliases: [], tags: []),
        LogoMeta(slug: "jcb", name: "JCB", category: "card-payment", aliases: [], tags: []),
        LogoMeta(slug: "jenius", name: "Jenius", category: "bank-logo", aliases: [], tags: []),
        LogoMeta(slug: "jenius-app", name: "Jenius", category: "bank-app", aliases: [], tags: []),
        LogoMeta(slug: "jenius-pay", name: "Jenius Pay", category: "direct-debit", aliases: [], tags: []),
        LogoMeta(slug: "jne", name: "JNE", category: "logistic", aliases: [], tags: []),
        LogoMeta(slug: "jne-alt", name: "JNE (Alt)", category: "logistic", aliases: [], tags: []),
        LogoMeta(slug: "joox", name: "JOOX", category: "entertainment", aliases: [], tags: []),
        LogoMeta(slug: "jp-morgan-chase", name: "JP Morgan Chase", category: "bank-logo", aliases: [], tags: []),
        LogoMeta(slug: "kai", name: "KAI", category: "transportation", aliases: [], tags: []),
        LogoMeta(slug: "kai-bandara", name: "KAI Bandara", category: "transportation", aliases: [], tags: []),
        LogoMeta(slug: "kai-commuter-new", name: "KAI Commuter (New)", category: "transportation", aliases: [], tags: []),
        LogoMeta(slug: "kai-commuter-old", name: "KAI Commuter (Old)", category: "transportation", aliases: [], tags: []),
        LogoMeta(slug: "kai-logistik", name: "KAI Logistik", category: "logistic", aliases: [], tags: []),
        LogoMeta(slug: "kartu-as", name: "Kartu As", category: "mobile-telco", aliases: [], tags: []),
        LogoMeta(slug: "kartu-halo", name: "Kartu Halo", category: "mobile-telco", aliases: [], tags: []),
        LogoMeta(slug: "kaspro", name: "Kaspro", category: "e-wallet", aliases: [], tags: []),
        LogoMeta(slug: "kb-bukopin", name: "KB Bukopin", category: "bank-logo", aliases: [], tags: []),
        LogoMeta(slug: "kb-bukopin-alt", name: "KB Bukopin (Alt)", category: "bank-logo", aliases: [], tags: []),
        LogoMeta(slug: "kb-bukopin-syariah", name: "KB Bukopin Syariah", category: "bank-logo", aliases: [], tags: []),
        LogoMeta(slug: "keb-hana-bank", name: "KEB Hana Bank", category: "bank-logo", aliases: [], tags: []),
        LogoMeta(slug: "keb-hana-bank-alt", name: "KEB Hana Bank (Alt)", category: "bank-logo", aliases: [], tags: []),
        LogoMeta(slug: "kemenkeu", name: "Kemenkeu", category: "government", aliases: [], tags: []),
        LogoMeta(slug: "khqr", name: "KHQR", category: "qr-payment", aliases: [], tags: []),
        LogoMeta(slug: "kitabisa", name: "Kitabisa", category: "donation", aliases: [], tags: []),
        LogoMeta(slug: "kitabisa-alt", name: "Kitabisa (Alt)", category: "donation", aliases: [], tags: []),
        LogoMeta(slug: "kominfo", name: "KOMINFO", category: "regulatory", aliases: [], tags: []),
        LogoMeta(slug: "korlantas-polri", name: "Korlantas Polri", category: "government", aliases: [], tags: []),
        LogoMeta(slug: "kredit-pintar", name: "Kredit Pintar", category: "financing", aliases: [], tags: []),
        LogoMeta(slug: "kreditplus", name: "KreditPlus", category: "financing", aliases: [], tags: []),
        LogoMeta(slug: "kredivo", name: "Kredivo", category: "financing", aliases: [], tags: []),
        LogoMeta(slug: "krom", name: "Krom", category: "bank-logo", aliases: [], tags: []),
        LogoMeta(slug: "lalamove", name: "Lalamove", category: "logistic", aliases: [], tags: []),
        LogoMeta(slug: "langitmusik", name: "Langitmusik", category: "entertainment", aliases: [], tags: []),
        LogoMeta(slug: "lao-qr", name: "LAO QR", category: "qr-payment", aliases: [], tags: []),
        LogoMeta(slug: "lawson", name: "Lawson", category: "supermarket", aliases: [], tags: []),
        LogoMeta(slug: "lazada", name: "Lazada", category: "e-commerce", aliases: [], tags: []),
        LogoMeta(slug: "lazada-express", name: "Lazada Express", category: "logistic", aliases: [], tags: []),
        LogoMeta(slug: "lexus-financial-service", name: "Lexus Financial Service", category: "financing", aliases: [], tags: []),
        LogoMeta(slug: "lexus-financial-service-1", name: "Lexus Financial Service-1", category: "financing", aliases: [], tags: []),
        LogoMeta(slug: "line-bank", name: "LINE Bank", category: "bank-logo", aliases: [], tags: []),
        LogoMeta(slug: "line-bank-alt", name: "LINE Bank (Alt)", category: "bank-logo", aliases: [], tags: []),
        LogoMeta(slug: "line-pay", name: "LINE Pay", category: "miscellaneous", aliases: [], tags: []),
        LogoMeta(slug: "line-pay-alt", name: "LINE Pay (Alt)", category: "miscellaneous", aliases: [], tags: []),
        LogoMeta(slug: "link", name: "Link", category: "switching", aliases: [], tags: []),
        LogoMeta(slug: "link-new", name: "Link (New)", category: "switching", aliases: [], tags: []),
        LogoMeta(slug: "link-new-alt", name: "Link (New Alt)", category: "switching", aliases: [], tags: []),
        LogoMeta(slug: "link-old", name: "Link (Old)", category: "switching", aliases: [], tags: []),
        LogoMeta(slug: "linkaja", name: "LinkAja", category: "e-wallet", aliases: [], tags: []),
        LogoMeta(slug: "lion-parcel", name: "Lion Parcel", category: "logistic", aliases: [], tags: []),
        LogoMeta(slug: "live-on", name: "Live.On", category: "mobile-telco", aliases: [], tags: []),
        LogoMeta(slug: "lotte", name: "Lotte", category: "supermarket", aliases: [], tags: []),
        LogoMeta(slug: "lotte-grosir", name: "Lotte Grosir", category: "supermarket", aliases: [], tags: []),
        LogoMeta(slug: "lotte-mart", name: "Lotte Mart", category: "supermarket", aliases: [], tags: []),
        LogoMeta(slug: "lps", name: "LPS", category: "regulatory", aliases: [], tags: []),
        LogoMeta(slug: "lrt-jakarta", name: "LRT Jakarta", category: "transportation", aliases: [], tags: []),
        LogoMeta(slug: "maestro", name: "Maestro", category: "card-payment", aliases: [], tags: []),
        LogoMeta(slug: "mandiri", name: "Mandiri", category: "bank-logo", aliases: [], tags: []),
        LogoMeta(slug: "mandiri-e-cash", name: "Mandiri E-Cash", category: "direct-debit", aliases: [], tags: []),
        LogoMeta(slug: "mandiri-e-money", name: "Mandiri e-money", category: "prepaid-card", aliases: [], tags: []),
        LogoMeta(slug: "mandiri-inhealth", name: "Mandiri Inhealth", category: "insurance", aliases: [], tags: []),
        LogoMeta(slug: "mandiri-livin", name: "Mandiri Livin", category: "bank-app", aliases: [], tags: []),
        LogoMeta(slug: "mandiri-livin-new", name: "Mandiri Livin (New)", category: "bank-app", aliases: [], tags: []),
        LogoMeta(slug: "mandiri-taspen", name: "Mandiri Taspen", category: "bank-logo", aliases: [], tags: []),
        LogoMeta(slug: "manulife", name: "Manulife", category: "insurance", aliases: [], tags: []),
        LogoMeta(slug: "manulife-alt", name: "Manulife (Alt)", category: "insurance", aliases: [], tags: []),
        LogoMeta(slug: "mastercard", name: "Mastercard", category: "card-payment", aliases: [], tags: []),
        LogoMeta(slug: "mastercard-black", name: "Mastercard Black", category: "card-payment", aliases: [], tags: []),
        LogoMeta(slug: "mastercard-contactless", name: "Mastercard Contactless", category: "card-payment", aliases: [], tags: []),
        LogoMeta(slug: "mastercard-contactless-alt", name: "Mastercard Contactless (Alt)", category: "card-payment", aliases: [], tags: []),
        LogoMeta(slug: "mastercard-debit", name: "Mastercard Debit", category: "card-payment", aliases: [], tags: []),
        LogoMeta(slug: "mastercard-debit-alt", name: "Mastercard Debit (Alt)", category: "card-payment", aliases: [], tags: []),
        LogoMeta(slug: "mastercard-securecode", name: "Mastercard SecureCode", category: "card-payment", aliases: [], tags: []),
        LogoMeta(slug: "mastercard-securecode-new", name: "Mastercard SecureCode (New)", category: "card-payment", aliases: [], tags: []),
        LogoMeta(slug: "masterpass", name: "Masterpass", category: "card-payment", aliases: [], tags: []),
        LogoMeta(slug: "masterpass-alt", name: "Masterpass (Alt)", category: "card-payment", aliases: [], tags: []),
        LogoMeta(slug: "maxstream", name: "Maxstream", category: "entertainment", aliases: [], tags: []),
        LogoMeta(slug: "maybank", name: "Maybank", category: "bank-logo", aliases: [], tags: []),
        LogoMeta(slug: "mega", name: "Mega", category: "bank-logo", aliases: [], tags: []),
        LogoMeta(slug: "mega-syariah", name: "Mega Syariah", category: "bank-logo", aliases: [], tags: []),
        LogoMeta(slug: "melsa", name: "Melsa", category: "isp", aliases: [], tags: []),
        LogoMeta(slug: "mentari-ooredoo", name: "Mentari Ooredoo", category: "mobile-telco", aliases: [], tags: []),
        LogoMeta(slug: "meps", name: "MEPS", category: "switching", aliases: [], tags: []),
        LogoMeta(slug: "midtrans", name: "Midtrans", category: "payment-gateway", aliases: [], tags: []),
        LogoMeta(slug: "mizuho-bank", name: "Mizuho Bank", category: "bank-logo", aliases: [], tags: []),
        LogoMeta(slug: "mnc", name: "MNC", category: "bank-logo", aliases: [], tags: []),
        LogoMeta(slug: "mnc-bank", name: "MNC Bank", category: "bank-logo", aliases: [], tags: []),
        LogoMeta(slug: "mnc-vision", name: "MNC Vision", category: "entertainment", aliases: [], tags: []),
        LogoMeta(slug: "moneygram", name: "MoneyGram", category: "remittance", aliases: [], tags: []),
        LogoMeta(slug: "motion-banking", name: "Motion Banking", category: "bank-logo", aliases: [], tags: []),
        LogoMeta(slug: "motion-banking-alt", name: "Motion Banking (Alt)", category: "bank-logo", aliases: [], tags: []),
        LogoMeta(slug: "motion-pay", name: "Motion Pay", category: "e-wallet", aliases: [], tags: []),
        LogoMeta(slug: "mrt-jakarta", name: "MRT Jakarta", category: "transportation", aliases: [], tags: []),
        LogoMeta(slug: "mtix", name: "MTIX", category: "entertainment", aliases: [], tags: []),
        LogoMeta(slug: "mualamat", name: "Mualamat", category: "bank-logo", aliases: [], tags: []),
        LogoMeta(slug: "mufg", name: "MUFG", category: "bank-logo", aliases: [], tags: []),
        LogoMeta(slug: "mufg-alt", name: "MUFG (Alt)", category: "bank-logo", aliases: [], tags: []),
        LogoMeta(slug: "my-nintendo", name: "My Nintendo", category: "game", aliases: [], tags: []),
        LogoMeta(slug: "myrepublic", name: "MyRepublic", category: "isp", aliases: [], tags: []),
        LogoMeta(slug: "nanobank-syariah", name: "Nanobank Syariah", category: "bank-logo", aliases: [], tags: []),
        LogoMeta(slug: "nanobank-syariah-alt", name: "Nanobank Syariah (Alt)", category: "bank-logo", aliases: [], tags: []),
        LogoMeta(slug: "ncs", name: "NCS", category: "logistic", aliases: [], tags: []),
        LogoMeta(slug: "neobank", name: "Neobank", category: "bank-app", aliases: [], tags: []),
        LogoMeta(slug: "netflix", name: "Netflix", category: "entertainment", aliases: [], tags: []),
        LogoMeta(slug: "netflix-alt", name: "Netflix (Alt)", category: "entertainment", aliases: [], tags: []),
        LogoMeta(slug: "nets", name: "NETS", category: "miscellaneous", aliases: [], tags: []),
        LogoMeta(slug: "netzme", name: "Netzme", category: "e-wallet", aliases: [], tags: []),
        LogoMeta(slug: "nex-parabola", name: "Nex Parabola", category: "entertainment", aliases: [], tags: []),
        LogoMeta(slug: "nickelodeon", name: "Nickelodeon", category: "entertainment", aliases: [], tags: []),
        LogoMeta(slug: "ninja-xpress", name: "Ninja Xpress", category: "logistic", aliases: [], tags: []),
        LogoMeta(slug: "nintendo-online", name: "Nintendo Online", category: "game", aliases: [], tags: []),
        LogoMeta(slug: "nobu", name: "NOBU", category: "bank-logo", aliases: [], tags: []),
        LogoMeta(slug: "ocbc-nisp", name: "OCBC NISP", category: "bank-logo", aliases: [], tags: []),
        LogoMeta(slug: "ocbc-pay-anyone", name: "OCBC Pay Anyone", category: "miscellaneous", aliases: [], tags: []),
        LogoMeta(slug: "octo-clicks", name: "OCTO Clicks", category: "bank-app", aliases: [], tags: []),
        LogoMeta(slug: "ojk", name: "OJK", category: "regulatory", aliases: [], tags: []),
        LogoMeta(slug: "ok-bank", name: "OK Bank", category: "bank-logo", aliases: [], tags: []),
        LogoMeta(slug: "oneklik", name: "OneKlik", category: "direct-debit", aliases: [], tags: []),
        LogoMeta(slug: "otto-pay", name: "OTTO Pay", category: "e-wallet", aliases: [], tags: []),
        LogoMeta(slug: "ovo-new", name: "OVO (New)", category: "e-wallet", aliases: [], tags: []),
        LogoMeta(slug: "ovo-new-alt", name: "OVO (New Alt)", category: "e-wallet", aliases: [], tags: []),
        LogoMeta(slug: "ovo-old", name: "OVO (Old)", category: "e-wallet", aliases: [], tags: []),
        LogoMeta(slug: "ovo-old-alt", name: "OVO (Old Alt)", category: "e-wallet", aliases: [], tags: []),
        LogoMeta(slug: "oxygen-id", name: "Oxygen.id", category: "isp", aliases: [], tags: []),
        LogoMeta(slug: "oxygen-id-home", name: "Oxygen.id Home", category: "isp", aliases: [], tags: []),
        LogoMeta(slug: "pam-jaya-new", name: "PAM Jaya (New)", category: "utilities", aliases: [], tags: []),
        LogoMeta(slug: "pam-jaya-old", name: "PAM Jaya (Old)", category: "utilities", aliases: [], tags: []),
        LogoMeta(slug: "pandu-logistics", name: "Pandu Logistics", category: "logistic", aliases: [], tags: []),
        LogoMeta(slug: "panin-dubai-syariah", name: "Panin Dubai Syariah", category: "bank-logo", aliases: [], tags: []),
        LogoMeta(slug: "paninbank", name: "PaninBank", category: "bank-logo", aliases: [], tags: []),
        LogoMeta(slug: "paydia", name: "Paydia", category: "e-wallet", aliases: [], tags: []),
        LogoMeta(slug: "payoneer", name: "Payoneer", category: "remittance", aliases: [], tags: []),
        LogoMeta(slug: "paypal", name: "PayPal", category: "remittance", aliases: [], tags: []),
        LogoMeta(slug: "paypal-new", name: "PayPal (New)", category: "remittance", aliases: [], tags: []),
        LogoMeta(slug: "paytren", name: "Paytren", category: "e-wallet", aliases: [], tags: []),
        LogoMeta(slug: "pcp-express", name: "PCP Express", category: "logistic", aliases: [], tags: []),
        LogoMeta(slug: "pdam", name: "PDAM", category: "utilities", aliases: [], tags: []),
        LogoMeta(slug: "pdam-kota-surabaya", name: "PDAM Kota Surabaya", category: "utilities", aliases: [], tags: []),
        LogoMeta(slug: "pegadaian", name: "Pegadaian", category: "financing", aliases: [], tags: []),
        LogoMeta(slug: "perbankan-syariah-ib", name: "Perbankan Syariah (IB)", category: "regulatory", aliases: [], tags: []),
        LogoMeta(slug: "permata", name: "Permata", category: "bank-logo", aliases: [], tags: []),
        LogoMeta(slug: "permata-bank-alt", name: "Permata Bank (Alt)", category: "bank-logo", aliases: [], tags: []),
        LogoMeta(slug: "permata-bank-new", name: "Permata Bank (New)", category: "bank-logo", aliases: [], tags: []),
        LogoMeta(slug: "pgn", name: "PGN", category: "utilities", aliases: [], tags: []),
        LogoMeta(slug: "playstation-plus", name: "Playstation Plus", category: "game", aliases: [], tags: []),
        LogoMeta(slug: "playstation-store", name: "Playstation Store", category: "game", aliases: [], tags: []),
        LogoMeta(slug: "pln", name: "PLN", category: "utilities", aliases: [], tags: []),
        LogoMeta(slug: "pos-indonesia-new", name: "Pos Indonesia (New)", category: "logistic", aliases: [], tags: []),
        LogoMeta(slug: "pos-indonesia-old", name: "Pos Indonesia (Old)", category: "logistic", aliases: [], tags: []),
        LogoMeta(slug: "pospay", name: "Pospay", category: "e-wallet", aliases: [], tags: []),
        LogoMeta(slug: "prima", name: "PRIMA", category: "switching", aliases: [], tags: []),
        LogoMeta(slug: "prima-bank", name: "PRIMA Bank", category: "bank-logo", aliases: [], tags: []),
        LogoMeta(slug: "prima-debit", name: "PRIMA Debit", category: "switching", aliases: [], tags: []),
        LogoMeta(slug: "prime-video", name: "Prime Video", category: "entertainment", aliases: [], tags: []),
        LogoMeta(slug: "prismalink", name: "PrismaLink", category: "payment-gateway", aliases: [], tags: []),
        LogoMeta(slug: "prudential", name: "Prudential", category: "insurance", aliases: [], tags: []),
        LogoMeta(slug: "qnb", name: "QNB", category: "bank-logo", aliases: [], tags: []),
        LogoMeta(slug: "qoala", name: "Qoala", category: "insurance", aliases: [], tags: []),
        LogoMeta(slug: "qr-ph", name: "QR Ph", category: "qr-payment", aliases: [], tags: []),
        LogoMeta(slug: "qris", name: "QRIS", category: "qr-payment", aliases: [], tags: []),
        LogoMeta(slug: "rex", name: "REX", category: "logistic", aliases: [], tags: []),
        LogoMeta(slug: "ria-money", name: "Ria Money", category: "remittance", aliases: [], tags: []),
        LogoMeta(slug: "rpx", name: "RPX", category: "logistic", aliases: [], tags: []),
        LogoMeta(slug: "rumah-zakat", name: "Rumah Zakat", category: "donation", aliases: [], tags: []),
        LogoMeta(slug: "rumah-zakat-alt", name: "Rumah Zakat (Alt)", category: "donation", aliases: [], tags: []),
        LogoMeta(slug: "samsung-card", name: "Samsung Card", category: "card-payment", aliases: [], tags: []),
        LogoMeta(slug: "samsung-pay", name: "Samsung Pay", category: "miscellaneous", aliases: [], tags: []),
        LogoMeta(slug: "samsung-pay-alt", name: "Samsung Pay (Alt)", category: "miscellaneous", aliases: [], tags: []),
        LogoMeta(slug: "sap-express", name: "SAP Express", category: "logistic", aliases: [], tags: []),
        LogoMeta(slug: "sbi-indonesia", name: "SBI Indonesia", category: "bank-logo", aliases: [], tags: []),
        LogoMeta(slug: "seabank", name: "SeaBank", category: "bank-logo", aliases: [], tags: []),
        LogoMeta(slug: "seabank-alt", name: "SeaBank (Alt)", category: "bank-logo", aliases: [], tags: []),
        LogoMeta(slug: "sequis", name: "Sequis", category: "insurance", aliases: [], tags: []),
        LogoMeta(slug: "sgqr", name: "SGQR", category: "qr-payment", aliases: [], tags: []),
        LogoMeta(slug: "sgqr-plus", name: "SGQR+", category: "qr-payment", aliases: [], tags: []),
        LogoMeta(slug: "shinhan-bank", name: "Shinhan Bank", category: "bank-logo", aliases: [], tags: []),
        LogoMeta(slug: "shinhan-bank-alt", name: "Shinhan Bank (Alt)", category: "bank-logo", aliases: [], tags: []),
        LogoMeta(slug: "shopee", name: "Shopee", category: "e-commerce", aliases: [], tags: []),
        LogoMeta(slug: "shopee-alt", name: "Shopee (Alt)", category: "e-commerce", aliases: [], tags: []),
        LogoMeta(slug: "shopee-pay", name: "Shopee Pay", category: "e-wallet", aliases: [], tags: []),
        LogoMeta(slug: "sicepat-ekspres", name: "Sicepat Ekspres", category: "logistic", aliases: [], tags: []),
        LogoMeta(slug: "simpati", name: "Simpati", category: "mobile-telco", aliases: [], tags: []),
        LogoMeta(slug: "simpati-new", name: "Simpati (New)", category: "mobile-telco", aliases: [], tags: []),
        LogoMeta(slug: "sinarmas", name: "Sinarmas", category: "bank-logo", aliases: [], tags: []),
        LogoMeta(slug: "sinarmas-syariah", name: "Sinarmas Syariah", category: "bank-logo", aliases: [], tags: []),
        LogoMeta(slug: "skrill", name: "Skrill", category: "remittance", aliases: [], tags: []),
        LogoMeta(slug: "smartfren", name: "Smartfren", category: "mobile-telco", aliases: [], tags: []),
        LogoMeta(slug: "smartfren-old", name: "Smartfren (Old)", category: "mobile-telco", aliases: [], tags: []),
        LogoMeta(slug: "speedcash", name: "SpeedCash", category: "e-wallet", aliases: [], tags: []),
        LogoMeta(slug: "spotify", name: "Spotify", category: "entertainment", aliases: [], tags: []),
        LogoMeta(slug: "spotify-alt", name: "Spotify (Alt)", category: "entertainment", aliases: [], tags: []),
        LogoMeta(slug: "spx-express", name: "SPX Express", category: "logistic", aliases: [], tags: []),
        LogoMeta(slug: "standard-chartered", name: "Standard Chartered", category: "bank-logo", aliases: [], tags: []),
        LogoMeta(slug: "steam", name: "Steam", category: "game", aliases: [], tags: []),
        LogoMeta(slug: "stripe", name: "Stripe", category: "payment-gateway", aliases: [], tags: []),
        LogoMeta(slug: "sun-life", name: "Sun Life", category: "insurance", aliases: [], tags: []),
        LogoMeta(slug: "super-indo", name: "Super Indo", category: "supermarket", aliases: [], tags: []),
        LogoMeta(slug: "superbank", name: "Superbank", category: "bank-logo", aliases: [], tags: []),
        LogoMeta(slug: "superbank-alt", name: "Superbank (Alt)", category: "bank-logo", aliases: [], tags: []),
        LogoMeta(slug: "swift", name: "SWIFT", category: "remittance", aliases: [], tags: []),
        LogoMeta(slug: "swift-alt", name: "SWIFT (Alt)", category: "remittance", aliases: [], tags: []),
        LogoMeta(slug: "taf-toyota-astra-financial", name: "TAF - Toyota Astra Financial", category: "financing", aliases: [], tags: []),
        LogoMeta(slug: "taspen", name: "Taspen", category: "insurance", aliases: [], tags: []),
        LogoMeta(slug: "telkomsel", name: "Telkomsel", category: "mobile-telco", aliases: [], tags: []),
        LogoMeta(slug: "telkomsel-alt", name: "Telkomsel (Alt)", category: "mobile-telco", aliases: [], tags: []),
        LogoMeta(slug: "telkomsel-halo", name: "Telkomsel Halo", category: "mobile-telco", aliases: [], tags: []),
        LogoMeta(slug: "telkomsel-orbit", name: "Telkomsel Orbit", category: "isp", aliases: [], tags: []),
        LogoMeta(slug: "telkomsel-prabayar", name: "Telkomsel Prabayar", category: "mobile-telco", aliases: [], tags: []),
        LogoMeta(slug: "thai-qr-payment", name: "Thai QR Payment", category: "qr-payment", aliases: [], tags: []),
        LogoMeta(slug: "thai-qr-payment-alt", name: "Thai QR Payment (Alt)", category: "qr-payment", aliases: [], tags: []),
        LogoMeta(slug: "the-foodhall", name: "The Foodhall", category: "supermarket", aliases: [], tags: []),
        LogoMeta(slug: "tiki", name: "TIKI", category: "logistic", aliases: [], tags: []),
        LogoMeta(slug: "tiktok-shop", name: "TikTok Shop", category: "e-commerce", aliases: [], tags: []),
        LogoMeta(slug: "tokopedia", name: "Tokopedia", category: "e-commerce", aliases: [], tags: []),
        LogoMeta(slug: "tokopedia-alt", name: "Tokopedia (Alt)", category: "e-commerce", aliases: [], tags: []),
        LogoMeta(slug: "topremit", name: "Topremit", category: "remittance", aliases: [], tags: []),
        LogoMeta(slug: "topremit-1", name: "Topremit-1", category: "remittance", aliases: [], tags: []),
        LogoMeta(slug: "toserba-yogya", name: "Toserba Yogya", category: "supermarket", aliases: [], tags: []),
        LogoMeta(slug: "toyota-financial-service", name: "Toyota Financial Service", category: "financing", aliases: [], tags: []),
        LogoMeta(slug: "transfez", name: "Transfez", category: "remittance", aliases: [], tags: []),
        LogoMeta(slug: "transjakarta", name: "TransJakarta", category: "transportation", aliases: [], tags: []),
        LogoMeta(slug: "transmart", name: "Transmart", category: "supermarket", aliases: [], tags: []),
        LogoMeta(slug: "transvision-new", name: "TransVision (New)", category: "entertainment", aliases: [], tags: []),
        LogoMeta(slug: "transvision-old", name: "TransVision (Old)", category: "entertainment", aliases: [], tags: []),
        LogoMeta(slug: "tri", name: "Tri", category: "mobile-telco", aliases: [], tags: []),
        LogoMeta(slug: "truemoney", name: "TrueMoney", category: "e-wallet", aliases: [], tags: []),
        LogoMeta(slug: "uangku", name: "Uangku", category: "e-wallet", aliases: [], tags: []),
        LogoMeta(slug: "ubisoft-plus", name: "UBISOFT+", category: "game", aliases: [], tags: []),
        LogoMeta(slug: "union-pay", name: "Union Pay", category: "card-payment", aliases: [], tags: []),
        LogoMeta(slug: "union-pay-contactless", name: "Union Pay Contactless", category: "card-payment", aliases: [], tags: []),
        LogoMeta(slug: "union-pay-contactless-en", name: "Union Pay Contactless (EN)", category: "card-payment", aliases: [], tags: []),
        LogoMeta(slug: "union-pay-en", name: "Union Pay (EN)", category: "card-payment", aliases: [], tags: []),
        LogoMeta(slug: "uob", name: "UOB", category: "bank-logo", aliases: [], tags: []),
        LogoMeta(slug: "uob-ez-pay", name: "UOB EZ Pay", category: "direct-debit", aliases: [], tags: []),
        LogoMeta(slug: "uob-tmrw", name: "UOB TMRW", category: "bank-app", aliases: [], tags: []),
        LogoMeta(slug: "verified-by-visa", name: "Verified by VISA", category: "card-payment", aliases: [], tags: []),
        LogoMeta(slug: "verified-by-visa-new", name: "Verified by VISA (New)", category: "card-payment", aliases: [], tags: []),
        LogoMeta(slug: "verifone", name: "Verifone", category: "miscellaneous", aliases: [], tags: []),
        LogoMeta(slug: "verifone-new", name: "Verifone (New)", category: "miscellaneous", aliases: [], tags: []),
        LogoMeta(slug: "vidio", name: "Vidio", category: "entertainment", aliases: [], tags: []),
        LogoMeta(slug: "vietqr", name: "VietQR", category: "qr-payment", aliases: [], tags: []),
        LogoMeta(slug: "visa", name: "VISA", category: "card-payment", aliases: [], tags: []),
        LogoMeta(slug: "visa-checkout", name: "VISA Checkout", category: "card-payment", aliases: [], tags: []),
        LogoMeta(slug: "visa-debit", name: "VISA Debit", category: "card-payment", aliases: [], tags: []),
        LogoMeta(slug: "visa-pay", name: "VISA Pay", category: "card-payment", aliases: [], tags: []),
        LogoMeta(slug: "visa-paywave", name: "VISA PayWave", category: "card-payment", aliases: [], tags: []),
        LogoMeta(slug: "visa-plus", name: "VISA Plus", category: "card-payment", aliases: [], tags: []),
        LogoMeta(slug: "visa-secure-3ds", name: "VISA Secure (3DS)", category: "card-payment", aliases: [], tags: []),
        LogoMeta(slug: "visa-signature", name: "VISA Signature", category: "card-payment", aliases: [], tags: []),
        LogoMeta(slug: "vision-plus", name: "Vision+", category: "entertainment", aliases: [], tags: []),
        LogoMeta(slug: "viu", name: "VIU", category: "entertainment", aliases: [], tags: []),
        LogoMeta(slug: "wahana-express", name: "Wahana Express", category: "logistic", aliases: [], tags: []),
        LogoMeta(slug: "wahana-express-alt", name: "Wahana Express (Alt)", category: "logistic", aliases: [], tags: []),
        LogoMeta(slug: "wechat-pay", name: "WeChat Pay", category: "miscellaneous", aliases: [], tags: []),
        LogoMeta(slug: "wechat-pay-alt", name: "WeChat Pay (Alt)", category: "miscellaneous", aliases: [], tags: []),
        LogoMeta(slug: "welab-bank", name: "Welab Bank", category: "bank-logo", aliases: [], tags: []),
        LogoMeta(slug: "western-union", name: "Western Union", category: "remittance", aliases: [], tags: []),
        LogoMeta(slug: "whoosh", name: "Whoosh", category: "transportation", aliases: [], tags: []),
        LogoMeta(slug: "wirecard", name: "Wirecard", category: "miscellaneous", aliases: [], tags: []),
        LogoMeta(slug: "wise", name: "Wise", category: "remittance", aliases: [], tags: []),
        LogoMeta(slug: "wom-finance", name: "WOM Finance", category: "financing", aliases: [], tags: []),
        LogoMeta(slug: "wondr-by-bni", name: "Wondr by BNI", category: "bank-app", aliases: [], tags: []),
        LogoMeta(slug: "world-bank", name: "World Bank", category: "regulatory", aliases: [], tags: []),
        LogoMeta(slug: "world-bank-alt", name: "World Bank (Alt)", category: "regulatory", aliases: [], tags: []),
        LogoMeta(slug: "xbox-game-pass", name: "XBOX Game Pass", category: "game", aliases: [], tags: []),
        LogoMeta(slug: "xendit", name: "Xendit", category: "payment-gateway", aliases: [], tags: []),
        LogoMeta(slug: "xl", name: "XL", category: "mobile-telco", aliases: [], tags: []),
        LogoMeta(slug: "xl-prioritas", name: "XL Prioritas", category: "mobile-telco", aliases: [], tags: []),
        LogoMeta(slug: "xl-satu", name: "XL Satu", category: "isp", aliases: [], tags: []),
        LogoMeta(slug: "xl-smart", name: "XL Smart", category: "mobile-telco", aliases: [], tags: []),
        LogoMeta(slug: "xl-smart-alt", name: "XL SMART (Alt)", category: "mobile-telco", aliases: [], tags: []),
        LogoMeta(slug: "xxi-21", name: "XXI (21)", category: "entertainment", aliases: [], tags: []),
        LogoMeta(slug: "yomart", name: "Yomart", category: "supermarket", aliases: [], tags: []),
        LogoMeta(slug: "yukk", name: "Yukk", category: "e-wallet", aliases: [], tags: []),
        LogoMeta(slug: "zalora", name: "Zalora", category: "e-commerce", aliases: [], tags: []),
        LogoMeta(slug: "zurich", name: "Zurich", category: "insurance", aliases: [], tags: []),
        LogoMeta(slug: "zurich-alt", name: "Zurich (Alt)", category: "insurance", aliases: [], tags: []),
    ]

    static let categories: [Category] = [
        Category(slug: "bank-app", displayName: "Bank App", count: 17),
        Category(slug: "bank-logo", displayName: "Bank Logo", count: 160),
        Category(slug: "card-payment", displayName: "Card Payment", count: 37),
        Category(slug: "direct-debit", displayName: "Direct Debit", count: 6),
        Category(slug: "donation", displayName: "Donation", count: 7),
        Category(slug: "e-commerce", displayName: "E-Commerce", count: 12),
        Category(slug: "e-wallet", displayName: "E-Wallet", count: 27),
        Category(slug: "entertainment", displayName: "Entertainment", count: 26),
        Category(slug: "financing", displayName: "Financing", count: 27),
        Category(slug: "game", displayName: "Game", count: 15),
        Category(slug: "government", displayName: "Government", count: 5),
        Category(slug: "insurance", displayName: "Insurance", count: 29),
        Category(slug: "isp", displayName: "ISP", count: 15),
        Category(slug: "logistic", displayName: "Logistic", count: 33),
        Category(slug: "miscellaneous", displayName: "Miscellaneous", count: 21),
        Category(slug: "mobile-telco", displayName: "Mobile Telco", count: 20),
        Category(slug: "payment-gateway", displayName: "Payment Gateway", count: 10),
        Category(slug: "prepaid-card", displayName: "Prepaid Card", count: 9),
        Category(slug: "qr-payment", displayName: "QR Payment", count: 11),
        Category(slug: "regulatory", displayName: "Regulatory", count: 15),
        Category(slug: "remittance", displayName: "Remittance", count: 14),
        Category(slug: "supermarket", displayName: "Supermarket", count: 24),
        Category(slug: "switching", displayName: "Switching", count: 13),
        Category(slug: "transportation", displayName: "Transportation", count: 12),
        Category(slug: "utilities", displayName: "Utilities", count: 7),
    ]
}
